### ISSUE TITLE
Connecting to ms sql server

### ISSUE THREAD

**Issue by morenoh149** [schemaspy/schemaspy#105]
I'm running
```
» java -jar schemaSpy_5.0.0.jar -t mssql -db <my db> -u <my user> -host <ip address> -o <output dir> -dp sqljdbc42.jar -port <my port>
Using database properties:
  [schemaSpy_5.0.0.jar]/net/sourceforge/schemaspy/dbTypes/mssql.properties
java.lang.ClassNotFoundException: com.microsoft.jdbc.sqlserver.SQLServerDriver

Failed to load driver 'com.microsoft.jdbc.sqlserver.SQLServerDriver'from: [file:/Users/harrymoreno/programming/databases/sqljdbc42.jar]
These entries don't point to valid files/directories: [C, /Program Files/Microsoft SQL Server 2000 Driver for JDBC/lib/msbase.jar;C, /Program Files/Microsoft SQL Server 2000 Driver for JDBC/lib/mssqlserver.jar;C, /Program Files/Microsoft SQL Server 2000 Driver for JDBC/lib/msutil.jar]

Use the -dp option to specify the location of the database
drivers for your database (usually in a .jar or .zip/.Z).
```
thoughts? I used the driver from https://www.microsoft.com/en-us/download/details.aspx?id=11774 using jre8 on mac

**Comment by npetzall** [comment]
@morenoh149 a bit of a long shot, could you test `-t mssql05` it should be for mysql 2005 and newer.

**Comment by npetzall** [comment]
Reason seems they changed the package name for newer drivers.

**Comment by morenoh149** [comment]
actually turns out the db is sql server. I'll report back if I get it working.

**Comment by morenoh149** [comment]
now I get
```
» java -jar schemaSpy_5.0.0.jar -t sqlserver -db myDB -u myUser -host 1.1.1.1 -o schemaSpy -s "public" -dp ../sqljdbc42.jar
java.util.MissingResourceException: Can't find bundle for base name net/sourceforge/schemaspy/dbTypes/sqlserver, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at net.sourceforge.schemaspy.Config.getDbProperties(Config.java:1242)
	at net.sourceforge.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:137)
	at net.sourceforge.schemaspy.Main.main(Main.java:42)
java.io.FileNotFoundException: sqlserver.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at net.sourceforge.schemaspy.Config.getDbProperties(Config.java:1232)
	at net.sourceforge.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:137)
	at net.sourceforge.schemaspy.Main.main(Main.java:42)
java.io.FileNotFoundException: sqlserver (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at net.sourceforge.schemaspy.Config.getDbProperties(Config.java:1227)
	at net.sourceforge.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:137)
	at net.sourceforge.schemaspy.Main.main(Main.java:42)
```

**Comment by npetzall** [comment]
@morenoh149 
> actually turns out the db is sql server. I'll report back if I get it working.
So its not Microsoft SQL Server? Sometimes known as mssql

Did you try `-t mssql05` it has more to do with the drivers you are using than actual version of MS SQL Server. But it would help if you knew the version of SQL Server.

-t [dbType] sets up both which JDBC Driver to use and stuff regarding connecting to it, but also which queries to use to get information about tables, views and stuff.

**Comment by morenoh149** [comment]
it's `Microsoft SQL Server 12.00.4232`

**Comment by npetzall** [comment]
Just realized your using 5.0.0, I need to check the sources if the new drivers are supported.
Else if possible use 6.0.0-rc1 with `-t mssql05`

**Comment by npetzall** [comment]
I downloaded the driver and -t mssql05 should be able to connect.
If the output or generation is incorrect (missing tables, columns, view, comments) let us know so that we can try to create a more up-to-date dbTyp for mssql than 2005.

**Comment by morenoh149** [comment]
amazing it worked! now I need to figure which schemas I can access!
```
» java -jar schemaspy-6.0.0-rc1.jar -t mssql05 -host 1.1.1.1 -port 12345 -db database -o outDir -u myUser -p myPass -s Person -dp ../sqljdbc42.jar`
