### ISSUE TITLE
graphviz version 2.26.0 not supported (while it should be according to documentation)

### ISSUE THREAD

**Issue by hjoukl** [schemaspy/schemaspy#108]
Thanks for taking up work on the original schemaSpy - looks great!

While it says that graphviz 2.26 or >2.31 are supported graphviz versions SchemaSpy does not accept 2.26.0:

```
0 $ java -jar ./schemaspy-6.0.0-rc1.jar -configFile sqlite.properties -o ndm_html -u $USER -meta ndm.meta.xml
Jun 13, 2017 5:15:38 PM org.springframework.context.annotation.AnnotationConfigApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7cd84586: startup date [Tue Jun 13 17:15:38 CEST 2017]; root of context hierarchy
17:15:39.599 WARNING: Config.getPort - null
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.schemaspy.Config.getPort(Config.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.schemaspy.Config.populate(Config.java:1647)
	at org.schemaspy.Config.getRemainingParameters(Config.java:1465)
	at org.schemaspy.util.ConnectionURLBuilder.<init>(ConnectionURLBuilder.java:47)
	at org.schemaspy.service.SqlService.connect(SqlService.java:46)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:197)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
	at org.schemaspy.Main.main(Main.java:52)
17:15:39.646 WARNING: Config.getPort - null
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.schemaspy.Config.getPort(Config.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.schemaspy.Config.populate(Config.java:1647)
	at org.schemaspy.Config.getRemainingParameters(Config.java:1465)
	at org.schemaspy.util.ConnectionURLBuilder.<init>(ConnectionURLBuilder.java:53)
	at org.schemaspy.service.SqlService.connect(SqlService.java:46)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:197)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
	at org.schemaspy.Main.main(Main.java:52)
17:15:39.647 WARNING: Config.getPort - null
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.schemaspy.Config.getPort(Config.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.schemaspy.Config.populate(Config.java:1647)
	at org.schemaspy.Config.getRemainingParameters(Config.java:1465)
	at org.schemaspy.service.SqlService.connect(SqlService.java:50)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:197)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
	at org.schemaspy.Main.main(Main.java:52)
17:15:39.647 WARNING: Config.getPort - null
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.schemaspy.Config.getPort(Config.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.schemaspy.Config.populate(Config.java:1647)
	at org.schemaspy.Config.getRemainingParameters(Config.java:1465)
	at org.schemaspy.service.SqlService.connect(SqlService.java:52)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:197)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
	at org.schemaspy.Main.main(Main.java:52)
17:15:39.648 WARNING: SqlService.connect - Unrecognized option(s): -configFile sqlite.properties db /ae/data/tmp/hjoukl/ndm.db connectionSpec jdbc:sqlite:<db> description SQLite  driver org.sqlite.JDBC driverPath sqlite-jdbc-3.18.0.jar
Using database properties:
  /ae/data/pydev/hjoukl/tmp/ER_from_db/schemaspy/github_fork/sqlite.properties
Gathering schema details.....(0sec)
Connecting relationships.....(0sec)
Writing/graphing summary....
Warning: Invalid version of Graphviz dot detected (2.26.0).
   SchemaSpy requires dot graphvizVersion 2.26 or versions greater than 2.31. from www.graphviz.org.
   Generated pages will not contain a diagramatic view of table relationships.
......(1sec)
Writing/diagramming details.Table -> Deal
.Table -> DealCost
(0sec)
Wrote relationship details of 2 tables/views to directory 'ndm_html' in 3 seconds.
View the results by opening ndm_html/index.html
0  $ dot -V
dot - graphviz version 2.26.0 (20091210.2329)
0 $ 
```

As far as I know there is no such graphviz version "2.26" but only "2.26.0", at least of what I can tell from http://www.graphviz.org/pub/graphviz/ARCHIVE/

I suggest correcting the version string to 2.26.0 as the supported version (https://github.com/schemaspy/schemaspy/blob/9388f2e7a2324d638737cced900d2e4b0fe3f282/src/main/java/org/schemaspy/util/Dot.java#L35) or maybe adapting the regexp used to find the version from the dot -V command line to only consider the (major, minor) parts of the version.

If anyone has this issue and can't upgrade to a modern graphviz easily (e.g. corporate env) here's a hack: I'm currently tricking SchemaSpy into accepting 2.26.0 by using a dumb script:
```
$ cat bin/dot 
#!/bin/bash

MODIFIED_VERSION_OUTPUT="dot - graphviz version 2.26 (20091210.2329)"

if [ "$1" == "-V" ]; then
    >&2 echo "$MODIFIED_VERSION_OUTPUT"
else
    dot $@
fi
```

... and run the command with the -gv command line option to point to my (fake) graphviz installation dir:

```
$ java -jar ./schemaspy-6.0.0-rc1.jar -configFile sqlite.properties -o ndm_html -u $USER -meta ndm.meta.xml -gv /var/tmp/fake_graphviz # fake_graphviz contains bin/dot
```

**Comment by npetzall** [comment]
Nice workaround.

Looking at the archives, we should parse major.minor.patch and if patch is absent default to 0.
Might be a good idea to use something like [semver lib](https://github.com/zafarkhaja/jsemver)

**Comment by npetzall** [comment]
@rafalkasa simple fix is to just care about major, minor and drop the patch version? If we want to use patch is it ok to add semver lib?

**Comment by rafalkasa** [comment]
@npetzallI agree with you patch version can be removed

**Comment by npetzall** [comment]
I'll fix this.
