### ISSUE TITLE
NullPointerException SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:349)

### ISSUE THREAD

**Issue by gzahl** [schemaspy/schemaspy#1101]
I am trying to execute Schemaspy on my database but i get a NullPointerException here:
SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:349)

Any idea what is going on?
I am running currently on git-bash, java8, using vizjs. But it also happens in my pipeline with Java 17, linux etc.

```bash
$ java -jar schemaspy.jar -configFile C:/Sandbox/cpe-report-model/cpe-report-model-integrationtest/target/test-classes/schemaspy/schemaspy.properties -host jdbc:oracle:thin:@//localhost:1521/PDB1 -dp C:/Users/maju/.m2/repository/com/oracle/database/jdbc/ojdbc8/21.7.0.0/ojdbc8-21.7.0.0.jar -u CPEREP_TEST_U -p CPEREP_TEST_U -o C:/Sandbox/cpe-report-model/cpe-report-model-integrationtest/target/schemaspy-reports
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.2.1

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.2.1 on NBAG0153 with PID 21632 (C:\Sandbox\cpe-report-model\cpe-report-model-integrationtest\target\test-classes\schemaspy\schemaspy.jar started by maju in C:\Sandbox\cpe-report-model\cpe-report-model-integrationtest\target\test-classes\schemaspy)
INFO  - The following profiles are active: default
INFO  - Found configuration file: C:/Sandbox/cpe-report-model/cpe-report-model-integrationtest/target/test-classes/schemaspy/schemaspy.properties
INFO  - Started Main in 1.391 seconds (JVM running for 1.909)
INFO  - Starting schema analysis
INFO  - Connected to Oracle - Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.14.0.0.0
INFO  - Gathering schema details
Gathering schema details...............................................................................................................................................................................................................................................................(5sec)
Connecting relationships...............................................................................................................................................................................................................................................................(3sec)
Writing/graphing summary.INFO  - Gathered schema details in 3 seconds
INFO  - Writing/graphing summary
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.NullPointerException
        at org.schemaspy.util.Jar.<init>(Jar.java:30)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:349)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:288)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:134)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
```

**Comment by npetzall** [comment]
I'll try to reproduce this. I suspect it has to do with classpath in some way or the usage of template folder.

**Comment by gzahl** [comment]
I have tried with and without specifying a template folder, but i get the same error both times.
The log is from a try without specifying a template folder. Let me know if you need any of the other parameters, but i removed all i could (all but the ones specifying the database connection and schema).

**Comment by npetzall** [comment]
Only would be if you get the same problem with 6.2.0 there were no major changes. Between 6.2.1 and 6.2.0 just if there is any problem with the jar-file

**Comment by gzahl** [comment]
Same problem with 6.2.0:
```
$ /c/Program\ Files/Eclipse\ Adoptium/jdk-17.0.5.8-hotspot/bin/java.exe  -jar schemaspy-6.2.0.jar -configFile C:/Sandbox/cpe-report-model/cpe-report-model-integrationtest/target/test-classes/schemaspy/schemaspy.properties -host jdbc:oracle:thin:@//localhost:1521/PDB1 -dp C:/Users/maju/.m2/repository/com/oracle/database/jdbc/ojdbc8/21.7.0.0/ojdbc8-21.7.0.0.jar -u CPEREP_TEST_U -p CPEREP_TEST_U -o C:/Sandbox/cpe-report-model/cpe-report-model-integrationtest/target/schemaspy-reports
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.2.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.2.0 on NBAG0153 with PID 50832 (C:\Sandbox\cpe-report-model\cpe-report-model-integrationtest\target\test-classes\schemaspy\schemaspy-6.2.0.jar started by maju in C:\Sandbox\cpe-report-model\cpe-report-model-integrationtest\target\test-classes\schemaspy)
INFO  - The following profiles are active: default
INFO  - Found configuration file: C:/Sandbox/cpe-report-model/cpe-report-model-integrationtest/target/test-classes/schemaspy/schemaspy.properties
INFO  - Started Main in 1.446 seconds (JVM running for 1.97)
INFO  - Starting schema analysis
INFO  - Connected to Oracle - Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.14.0.0.0
INFO  - Gathering schema details
Gathering schema details................................................................................................................................................................................................................................................................(5sec)
Connecting relationships................................................................................................................................................................................................................................................................(2sec)
Writing/graphing summary.INFO  - Gathered schema details in 2 seconds
INFO  - Writing/graphing summary
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.openConnection()" because "resourceUrl" is null
        at org.schemaspy.util.Jar.<init>(Jar.java:30)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:349)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:288)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:134)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
```

**Comment by npetzall** [comment]
I found the issue.....

There is some code that excludes the layout if the path contains test-classes, you will need to move schemaSpy.jar to a different folder.

I'll see if we can improve on the exclusion, so that it won't be an issue inte future.

**Comment by gzahl** [comment]
You are right. I changed the path so "test-classes" is not part of it anymore and the error went away. Thanks a lot!
