### ISSUE TITLE
java.lang.UnsupportedOperationException when using Docker container

### ISSUE THREAD

**Issue by zam6ak** [schemaspy/schemaspy#1103]
Using Docker containers (snapshot,latest,6.2.1) is causing an exception during processing
Using version 6.1.0 works.

## Expected Behavior
Running should produce output folder

## Current Behavior
When container start exception is thrown:

```
Using drivers:postgresql-42.6.0.jar
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.2.1

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.2.1 on 2c2fbf29f425 with PID 1 (/usr/local/lib/schemaspy/schemaspy-6.2.1-app.jar started by java in /)
INFO  - The following profiles are active: default
INFO  - Found configuration file: schemaspy.properties
INFO  - Started Main in 1.942 seconds (JVM running for 2.8)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.UnsupportedOperationException
        at java.base/java.util.AbstractList.add(AbstractList.java:153)
        at java.base/java.util.AbstractList.add(AbstractList.java:111)
        at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336)
        at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:253)
        at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:218)
        at com.beust.jcommander.JCommander.initializeDefaultValue(JCommander.java:620)
        at com.beust.jcommander.JCommander.initializeDefaultValues(JCommander.java:328)
        at com.beust.jcommander.JCommander.parse(JCommander.java:311)
        at com.beust.jcommander.JCommander.parse(JCommander.java:291)
        at org.schemaspy.cli.CommandLineArgumentParser.parse(CommandLineArgumentParser.java:76)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:78)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
```

## Steps to Reproduce (for bugs)
1. Prepare "schemaspy" directory with appropriate files (driver. properties file, subfolders)
2. Run Docker command

```
docker run --name schemaspy --rm \
--network=devnet \
-v "X:/schemaspy/output:/output" \
-v "X:/schemaspy/drivers:/drivers" \
-v "X:/schemaspy/schemaspy.properties:/schemaspy.properties" \
schemaspy/schemaspy:snapshot
```

## Context
Here is my `schemaspy.properties` file

```
schemaspy.t=pgsql11
schemaspy.host=development-postgresql-1
schemaspy.port=5432
schemaspy.db=test_db
schemaspy.u=postgres
schemaspy.p=***OMMITED***
schemaspy.schemas=app,public,extensions
schemaspy.norows=true
schemaspy.desc=DB Schema - development
schemaspy.nopages=true
schemaspy.hq=true
#schemaspy.vizjs=true
schemaspy.imageformat=svg
```

## Your Environment
Windows 10 Pro
Git Bash for Windows
Docker Desktop 4.17.1

**Comment by npetzall** [comment]
I think I know what the problem is.

It's the schemas argument. It's a list but it seems that instead of replacing the default list it tries to add to it.

And the default list is `Collections.emptyList()`, so it needs to be replaced with a `new ArrayList<>()`

**Comment by zam6ak** [comment]
> 

I can confirm that problem goes away if I comment out 
`#schemaspy.schemas=app,public,extensions`

**Comment by npetzall** [comment]
@zam6ak Could you `docker pull schemaspy/schemaspy:snapshot` and giv it another go with the snapshot it has been updated with the fix, if it's working I'll do a new release.

**Comment by zam6ak** [comment]
@npetzall I can confirm that latest snapshot resolves this issue

**Comment by npetzall** [comment]
@zam6ak awesome thanks for reporting and verifying, I'll do a new release ASAP (will be in a couple of hours)
