### ISSUE TITLE
"Failed to query Graphviz version using 'dot -V'" error

### ISSUE THREAD

**Issue by anothermh** [schemaspy/schemaspy#1153]
When running schemaspy through Docker with `schemaspy/schemaspy:latest` or `:snapshot` the application fails with:

```
This command is not for general use and should only be run as the result of a call to
WARN  - Failed to query Graphviz version using 'dot -V'
Cannot run program "dot": error=0, Failed to exec spawn helper: pid: 54, exit value: 1
INFO  - Graphviz renderer set to ''
..ERROR - RelationShipDiagramError
```

## Expected Behavior

I expect that the command completes successfully, as it does when using the Docker image `schemaspy/schemaspy:6.1.0`:

```
Connecting relationships....................(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
INFO  - Graphviz rendered set to ''
........(1sec)
Writing/diagramming detailsINFO  - Completed summary in 1 seconds
INFO  - Writing/diagramming details
.................(2sec)
Wrote relationship details of 17 tables/views to directory '/output' in 5 seconds.
View the results by opening /output/index.html
INFO  - Wrote table details in 2 seconds
INFO  - Wrote relationship details of 17 tables/views to directory '/output' in 5 seconds.
INFO  - View the results by opening /output/index.html
INFO  - StackTraces have been omitted, use `-debug` when executing SchemaSpy to see them
```

## Current Behavior

The application fails with:

```
Connecting relationships....................(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
This command is not for general use and should only be run as the result of a call to
WARN  - Failed to query Graphviz version using 'dot -V'
Cannot run program "dot": error=0, Failed to exec spawn helper: pid: 54, exit value: 1
INFO  - Graphviz renderer set to ''
..ERROR - RelationShipDiagramError
Failed to produce diagram for: /output/diagrams/summary/relationships.real.compact.dot
ERROR - RelationShipDiagramError
Failed to produce diagram for: /output/diagrams/summary/relationships.real.large.dot
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.schemaspy.output.html.HtmlException: Failed to generate Orphan diagram
    at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.writeDiagram(OrphanDiagram.java:80)
    at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.html(OrphanDiagram.java:56)
    at org.schemaspy.view.HtmlOrphansPage.createPageData(HtmlOrphansPage.java:68)
    at org.schemaspy.view.HtmlOrphansPage.write(HtmlOrphansPage.java:57)
    at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:426)
    at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:289)
    at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:135)
    at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
    at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
    at org.schemaspy.Main.main(Main.java:55)
    ... 8 more
Caused by: org.schemaspy.output.diagram.RenderException: Dot missing or invalid version
    at org.schemaspy.output.diagram.graphviz.GraphvizDot.render(GraphvizDot.java:198)
    at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.writeDiagram(OrphanDiagram.java:73)
    ... 17 more
```

## Possible Solution

Downgrade to 6.1.0.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Database type (e.g. MySQL): Postgres
* Database driver version (is you use a special one): n/a
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

```shell
schemaspy -t pgsql -db my_database -host postgres -port 5432 -u my_user -nopages -hq -imageformat svg -font HelveticaNeue -renderer :cairo -rails
```

## Your Environment

* Version used: https://hub.docker.com/layers/schemaspy/schemaspy/latest/images/sha256-943adb52e54f1981aa895e924be03335fc93ea3fa00a992248b31a43dc039418?context=explore
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10):
* Java version:

---

Second, what's the deal with Docker image versions disappearing? There are multiple issues referencing this same problem with `dot` and the answer is "use 6.1.1-snapshot" which doesn't exist because apparently Docker images aren't kept, they're just overwritten, which makes it impossible for me to use anything newer than a version from 2019 unless I want to roll my own image.

**Comment by npetzall** [comment]
I'll look into it shortly, it hasn't been a problem. But there might be upstream updates in the FROM image.

Regarding the versions "-SNAPSHOT" is development "version" so it changes with every build. It's mainly inherited from Maven and the way it managed versions that's why you have `6.1.1-SNAPSHOT`. Docker doesn't care that much about versions it only has tags so we have a single tag `snapshot` that is always the latest build other than that we have `latest` which is latest release and then we should have one for each released version.

So there has never been a 6.1.1-snapshot on Docker hub. The one we hade available earlier was on GitHub pages and it was overwritten each nu build even when changing version numbers so `6.2.1-SNAPSHOT` has replaced `6.1.1-SNAPSHOT`. We have since moved to deployment to maven central and I think snapshots are kept longer but they are in the OSSHR snapshot repository. 

But basically the last 6.1.1-snapshot was the same as the 6.2.0 release.

**Comment by npetzall** [comment]
So had a quick check and it works for me both with SNAPSHOT and 6.2.2

So I have some follow up questions:
What operating system are you using?
Are you using docker or an alternative like podman, rancher desktop?
It would be useful if you could include the line which i similar to: 
`INFO  - Starting Main v6.2.0 on 0cb3f785e977 with PID 1 (/usr/local/lib/schemaspy/schemaspy-6.2.0-app.jar started by java in /)`
it's one of the first line after the banner.

A caveat with using `latest` and `snapshot` since they are tags in docker, they can be matched locally and nothing will be downloaded, so you need to do a docker pull to make sure that you local `latest`/`snapshot` is the same as on docker hub.

You can check your local digest with
`docker image inspect schemaspy/schemaspy:latest -f '{{ .RepoDigests }}'`
`docker image inspect schemaspy/schemaspy:snapshot -f '{{ .RepoDigests }}'`

**Comment by anothermh** [comment]
I'm using Docker Desktop 4.17.0 (99724) with Engine 20.10.23 and Compose v2.15.1 on macOS 13.3.1 with Apple Silicon.

Prior to creating this issue I ran the following commands to completely clear Docker and ensure it was reproducible with a fresh pull:

```shell
docker rm $(docker ps -a -q) ; docker rmi $(docker images -q) ; docker builder prune --all --force
```

Here are the digests as requested:

```
[schemaspy/schemaspy@sha256:943adb52e54f1981aa895e924be03335fc93ea3fa00a992248b31a43dc039418]
[schemaspy/schemaspy@sha256:314478c10341eda8297ab136c08e3b765c59c0fedc701f419bb950e3e21be808]
```

Here's the complete output from Docker Compose for the schemaspy container, omitting the output from the other containers:

```
schemaspy-1  | Using drivers:jtds-1.3.1.jar, mariadb-java-client-1.1.10.jar
schemaspy-1  | mysql-connector-java-8.0.28.jar, postgresql-42.3.8.jar
schemaspy-1  |   ____       _                          ____
schemaspy-1  |  / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
schemaspy-1  |  \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
schemaspy-1  |   ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
schemaspy-1  |  |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
schemaspy-1  |                                              |_|    |___/
schemaspy-1  | 
schemaspy-1  |                                               6.2.3-SNAPSHOT
schemaspy-1  | 
schemaspy-1  | SchemaSpy generates an HTML representation of a database schema's relationships.
schemaspy-1  | SchemaSpy comes with ABSOLUTELY NO WARRANTY.
schemaspy-1  | SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
schemaspy-1  | http://www.gnu.org/licenses/
schemaspy-1  | 
schemaspy-1  | INFO  - Starting Main v6.2.3-SNAPSHOT on e69e3723ab8e with PID 1 (/usr/local/lib/schemaspy/schemaspy-6.2.3-SNAPSHOT-app.jar started by java in /)
schemaspy-1  | INFO  - The following profiles are active: default
schemaspy-1  | INFO  - Started Main in 3.008 seconds (JVM running for 4.566)
schemaspy-1  | INFO  - Starting schema analysis
schemaspy-1  | INFO  - Connected to PostgreSQL - 14.7
schemaspy-1  | INFO  - Gathering schema details
schemaspy-1  | Gathering schema details....................WARN  - Failed to retrieve stored procedure/function details using sql 'select r.routine_name || '(' || oidvectortypes(p.proargtypes) || ')' as routine_name, case when p.proisagg then 'AGGREGATE' else 'FUNCTION' end as routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body,r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on r.specific_name = p.proname || '_' || p.oid left join pg_description d on d.objoid = p.oid where r.routine_schema = :schema'
schemaspy-1  | ERROR: column p.proisagg does not exist
schemaspy-1  |   Hint: Perhaps you meant to reference the column "p.prolang".
schemaspy-1  |   Position: 97
schemaspy-1  | (0sec)
schemaspy-1  | Connecting relationships....................(0sec)
schemaspy-1  | Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
schemaspy-1  | INFO  - Writing/graphing summary
schemaspy-1  | This command is not for general use and should only be run as the result of a call to
schemaspy-1  | WARN  - Failed to query Graphviz version using 'dot -V'
schemaspy-1  | Cannot run program "dot": error=0, Failed to exec spawn helper: pid: 53, exit value: 1
schemaspy-1  | INFO  - Graphviz renderer set to ''
schemaspy-1  | ..ERROR - RelationShipDiagramError
schemaspy-1  | Failed to produce diagram for: /output/diagrams/summary/relationships.real.compact.dot
schemaspy-1  | ERROR - RelationShipDiagramError
schemaspy-1  | Failed to produce diagram for: /output/diagrams/summary/relationships.real.large.dot
schemaspy-1  | Exception in thread "main" java.lang.reflect.InvocationTargetException
schemaspy-1  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
schemaspy-1  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
schemaspy-1  |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
schemaspy-1  |     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
schemaspy-1  |     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
schemaspy-1  |     at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
schemaspy-1  |     at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
schemaspy-1  |     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
schemaspy-1  | Caused by: org.schemaspy.output.html.HtmlException: Failed to generate Orphan diagram
schemaspy-1  |     at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.writeDiagram(OrphanDiagram.java:80)
schemaspy-1  |     at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.html(OrphanDiagram.java:56)
schemaspy-1  |     at org.schemaspy.view.HtmlOrphansPage.createPageData(HtmlOrphansPage.java:68)
schemaspy-1  |     at org.schemaspy.view.HtmlOrphansPage.write(HtmlOrphansPage.java:57)
schemaspy-1  |     at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:426)
schemaspy-1  |     at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:289)
schemaspy-1  |     at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:135)
schemaspy-1  |     at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
schemaspy-1  |     at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
schemaspy-1  |     at org.schemaspy.Main.main(Main.java:55)
schemaspy-1  |     ... 8 more
schemaspy-1  | Caused by: org.schemaspy.output.diagram.RenderException: Dot missing or invalid version
schemaspy-1  |     at org.schemaspy.output.diagram.graphviz.GraphvizDot.render(GraphvizDot.java:198)
schemaspy-1  |     at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.writeDiagram(OrphanDiagram.java:73)
schemaspy-1  |     ... 17 more
schemaspy-1 exited with code 1
Aborting on container exit...
```

To simplify troubleshooting and ensure it's reproducible I've created a repository that demonstrates the issue. The README contains instructions for reproducing:

https://github.com/anothermh/schemaspy-repro

**Comment by npetzall** [comment]
Unrelated but `-t pgsql11` for pgsql 11 or never will fix the query error.

Only difference here is Apple Silicon so it's running on Arm earlier we hade an issues with Java not working. We don't do cross builds yet, probably should put in an effort for that.

**Comment by anothermh** [comment]
`-t pgsql11` has removed the unmentioned error, thanks.

`-vizjs` does indeed work -- much more slowly, but it does work and the generation completes successfully. And I'm able to view diagrams by opening `index.html`.

As you noted I would recommend making [multi-platform images](https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images) if possible. I'm happy to test and get back to you on it if you publish them.
