### ISSUE TITLE
NullPointerException after upgrading to 6.2.2

### ISSUE THREAD

**Issue by pyrocks** [schemaspy/schemaspy#1166]
We started getting NullPointerException after upgrading from 6.1.0 to 6.2.2

## Expected Behavior

it should work

## Current Behavior

```
INFO - Analyzing 'public'
INFO - Starting schema analysis
INFO - Connected to PostgreSQL - 12.4
INFO - Gathering schema details
Exception in thread "main" java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "key" is null
at org.schemaspy.util.CaseInsensitiveMap.put(CaseInsensitiveMap.java:59)
at org.schemaspy.util.CaseInsensitiveMap.put(CaseInsensitiveMap.java:35)
at org.schemaspy.input.dbms.service.RoutineService.initRoutines(RoutineService.java:95)
at org.schemaspy.input.dbms.service.RoutineService.gatherRoutines(RoutineService.java:46)
at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(DatabaseService.java:132)
at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:269)
at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:185)
at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:126)
at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
at org.schemaspy.Main.main(Main.java:55)
... 8 more
```

## Context

schemaspy fails and doesn't generate the files for all schemas

* Database type (e.g. MySQL): postgres
* Database driver version (is you use a special one): default
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:
```
java -jar ./schemaspy-6.2.2.jar \
        -t pgsql11_partitions.properties \
        -db $DBNAME \
        -host $DBHOST \
        -port $DBPORT \
        -u $DBUSER \
        -p $SCHEMASPY_PG_PASSWORD \
        -o /output_tmp/$DBNAME \
        -dp /drivers \
        -schemas $LIST_OF_SCHEMAS \
        -noimplied \
        -nopages \
        -norows \
        -noexportedkeys
```

where `pgsql11_partitions.properties` is
```
extends=pgsql11

# relkind IN ('r','p') --> regular or partitioned \
# NOT relispartition --> not a partition
selectTablesSql=SELECT relname table_name, current_database() table_catalog, ns.nspname table_schema, description table_comment, 0 table_rows \
FROM pg_class obj \
INNER JOIN pg_namespace ns ON (obj.relnamespace=ns.oid) \
LEFT JOIN pg_catalog.pg_description ON (objoid=obj.oid AND objsubid =0) \
WHERE nspname = :schema \
AND relkind IN ('r','p') \
AND NOT relispartition
```

## Your Environment

* Version used: 6.2.2
* Operating System and version (e.g. Windows 10): linux
* Java version: openjdk:17-alpine3.14
* JDBC version 42.2.25

**Comment by npetzall** [comment]
Can you check if this is a duplicate of #1115

**Comment by pyrocks** [comment]
Indeed seems to be a duplicate - I had a procedure 57 chars long and in the original query `routine_name` returned null for it.
This is no longer the case with the updated queries in the linked issue.
Thanks for the quick assistance (and on a Sunday) 🙇
