### ISSUE TITLE
Failed to produce diagram

### ISSUE THREAD

**Issue by katiuszas** [schemaspy/schemaspy#1178]
Hi,

I am struggling with creating my DB documentation. I am having this config file:

schemaspy.host=LPT910
schemaspy.port=1433
schemaspy.db=GO_050_DEV_UAT;encrypt=true;trustServerCertificate=true
schemaspy.t=mssql08
schemaspy.dp=C:/Users/KatarzynaSulowska/Documents/DOCUMENTATION/schemaspy/JDBC driver/sqljdbc_12.2.0.0_enu/sqljdbc_12.2/enu/mssql-jdbc-12.2.0.jre8.jar
schemaspy.u=ks
schemaspy.p=[password]
schemaspy.o=C:/Users/KatarzynaSulowska/Documents/DOCUMENTATION/schemaspy/output
schemaspy.s=dbo

And running in cmd:
 java -jar C:/Users/KatarzynaSulowska/Documents/DOCUMENTATION/schemaspy/schemaspy-6.2.2.jar -configFile C:/Users/KatarzynaSulowska/Documents/DOCUMENTATION/schemaspy/config_file.txt -vizjs

And getting this error: 

INFO  - Writing/graphing summary
..ERROR - RelationShipDiagramError
Failed to produce diagram for: C:\Users\KatarzynaSulowska\Documents\DOCUMENTATION\schemaspy\output\diagrams\summary\relationships.implied.compact.dot
ERROR - RelationShipDiagramError
Failed to produce diagram for: C:\Users\KatarzynaSulowska\Documents\DOCUMENTATION\schemaspy\output\diagrams\summary\relationships.implied.large.dot
.Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.schemaspy.output.html.HtmlException: Failed to generate Orphan diagram
        at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.writeDiagram(OrphanDiagram.java:80)
        at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.html(OrphanDiagram.java:56)
        at org.schemaspy.view.HtmlOrphansPage.createPageData(HtmlOrphansPage.java:68)
        at org.schemaspy.view.HtmlOrphansPage.write(HtmlOrphansPage.java:57)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:428)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:288)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:134)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
        at org.schemaspy.Main.main(Main.java:55)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 5 more
Caused by: org.schemaspy.output.diagram.RenderException: javax.script.ScriptException: Error: syntax error in line 17839 scanning a HTML string (missing '>'? bad nesting? longer than 16384?)
String starting:<
    <TABLE BORDER="2" CELLBORDER="1" CELLSPACING="0" BGCOLOR="#ffffff">

 in <eval> at line number 94 at column number 4
        at org.schemaspy.output.diagram.vizjs.VizJSDot.render(VizJSDot.java:74)
        at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.writeDiagram(OrphanDiagram.java:73)
        ... 15 more

My Environment
* SchemaSpy version v6.2.2
* Microsoft SQL Server 2019
* Windows 11
* Java version: java 20.0.1 

Any piece of the advice is more than appreciated. Thanks!

**Comment by npetzall** [comment]
There can be multiple things, but I'm unsure.

Do you have any column or table names containing `<`? 
I seems like it finds `<` than tries to scan it like html but never finds the `>`.
Do you have table names that are really long(extremely)?

**Comment by CalderonRigoberto** [comment]
I'm getting same error. In my case there are tables like have more than 50 characteres that work with uuids so the names usually are very long.

There are something that I could do?

**Comment by npetzall** [comment]
@CalderonRigoberto the problem is not yet identified. With long names I think we are talking extremely long names.

But it would be good to identify the problematic table diagram also if it`s a syntax error in dot-lang or visjs.

So if you have any logs you can share with scrubbed sensitive information that would be a good start.

**Comment by npetzall** [comment]
Note for self, trace the error in the reported logs, it fails with summary but doesn't break. But breaks with orphan diagram.

**Comment by CalderonRigoberto** [comment]
@npetzall  This is the log error that I'm getting. 

```java
INFO  - Writing/graphing summary
..ERROR - RelationShipDiagramError
Failed to produce diagram for: /schemaspy/output/visedb/diagrams/summary/relationships.implied.compact.dot
.Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.schemaspy.output.html.HtmlException: Failed to generate Orphan diagram
        at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.writeDiagram(OrphanDiagram.java:80)
        at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.html(OrphanDiagram.java:56)
        at org.schemaspy.view.HtmlOrphansPage.createPageData(HtmlOrphansPage.java:68)
        at org.schemaspy.view.HtmlOrphansPage.write(HtmlOrphansPage.java:57)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:424)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:289)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:135)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
Caused by: org.schemaspy.output.diagram.RenderException: javax.script.ScriptException: Error: syntax error in line 22815 scanning a HTML string (missing '>'? bad nesting? longer than 16384?)
String starting:<
    <TABLE BORDER="2" CELLBORDER="1" CELLSPACING="0" BGCOLOR="#ffffff">
      <
 in <eval> at line number 94 at column number 4
        at org.schemaspy.output.diagram.vizjs.VizJSDot.render(VizJSDot.java:74)
        at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.writeDiagram(OrphanDiagram.java:73)
        ... 17 more
```

However, there are some examples of tables names that Identified that could be the problem, I mentioned because when I excluded this tables I have no problems.

NAMSE$Ess_ Business Headline Per Usr$2809f298-7ffd-44a5-a7ce-e08dac98axce
NAMSE$Essential Business Headline$2a09fs788-8zfd-94b4-r7ce-pX08dac98axce

**Comment by npetzall** [comment]
@CalderonRigoberto did you only exclude them or more. This gives me enough to start troubleshooting.

**Comment by CalderonRigoberto** [comment]
@npetzall I use -I argument and replace for "", to document also this kind of tables that had this names. Nonetheless,  almost all the databases where I got  this problem have the same structures on the table names.

**Comment by npetzall** [comment]
Length of name is not valid for mysql. Just manually creating a dot-file with such a long name doesn't cause an issue.
Might be how it's read and produced by the mssql driver, so need to test with mssql.

Other possible issue would be that it's not the table name that is the issue. But some other data in the dot file, column name or similare.

Having a reproducable sample would help. But I'll try to recreate when I get mssql working.

**Comment by npetzall** [comment]
So got mssql server working on my MBA M1. I used the long name but had no issues with that.

I've recreated the problem by just adding a dangling start element `<` in the dot file.

I've added both table with `<` in the name and column with it, but they are all escaped and works as expected with no issues.

So sadly the issue hasn't been isolated. I'll continue to think about it.

If someone is up for the task and is affected by the issue. You can use lower case i to include a single table in the output and try to find the offending table. Example from above `-i ".*NAMSE\$Ess_\sBusiness\sHeadline\sPer\sUsr\$2809f298-7ffd-44a5-a7ce-e08dac98axce"`

`-i` takes a regular expression (java flavour) and I think it matches the fully qualified name, so it needs to start with `.*` to avoid having to write catalog and schema.

**Comment by CalderonRigoberto** [comment]
@npetzall I'll try to isolate those database documentation processes by using the argument you mentioned above to reproduce the error and start troubleshooting.

**Comment by npetzall** [comment]
@CalderonRigoberto thank you. It's really appreciated.

**Comment by CalderonRigoberto** [comment]
Hi @npetzall  I tried by using this argument -i. But I got two cases.

The first one when I use for example with a table name called User Group Member as follows ".*User\sGroup\sMember" the docs it's generated without any issue.

The second one it's with the table name that has a name such a big for example as follows ".*EMP\\\$Activities\sCue\\\$96582bfa-4693-4bc2-ae1c-0979c29fd9e0". In this specific case I got the follow log. That seems weird. don't know if I'm making some mistakes on this kind of regex?


```java
ERROR - The schema exists in the database, but the user you specified 'java'might not have rights to read its contents.
ERROR - Another possibility is that the regular expression that you specified for what to include (via -i) didn't match any tables.
WARN  - Empty schema
null

```

**Comment by CalderonRigoberto** [comment]
Hi @npetzall  I tried by using this argument -i. But I got two cases.

The first one when I use for example with a table name called User Group Member as follows ".*User\sGroup\sMember" the docs it's generated without any issue.

The second one it's with the table name that has a name such a big for example as follows ".*EMP\\\$Activities\sCue\\\$96582bfa-4693-4bc2-ae1c-0979c29fd9e0". In this specific case I got the follow log. That seems weird to me and I don't know if I'm making some mistakes on this kind of regex?


```java
ERROR - The schema exists in the database, but the user you specified 'user_dbo' might not have rights to read its contents.
ERROR - Another possibility is that the regular expression that you specified for what to include (via -i) didn't match any tables.
WARN  - Empty schema
null

```

**Comment by CalderonRigoberto** [comment]
@npetzall  I used -debug argument, on general the docs was generating until doc.dbo.EMP$XML Schema Restriction that has stopped the process and I got this error on console.

```java
DEBUG - Adding foreign key constraint 'Implied Constraint' to doc.dbo.EMP$XML Schema Restriction
.ERROR - RelationShipDiagramError
org.schemaspy.output.OutputException: Failed to produce diagram for: /schemaspy/output/doc/diagrams/summary/relationships.implied.compact.dot
        at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateImpliedCompact(MustacheSummaryDiagramFactory.java:129)
        at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateSummaryDiagrams(MustacheSummaryDiagramFactory.java:96)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:395)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:289)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:135)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
        at org.schemaspy.Main.main(Main.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.schemaspy.output.diagram.RenderException: Failed to generate summary diagram
        at org.schemaspy.output.diagram.SummaryDiagram.generateSummaryDiagram(SummaryDiagram.java:24)
        at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateImpliedCompact(MustacheSummaryDiagramFactory.java:123)
        ... 15 common frames omitted
Caused by: org.schemaspy.output.diagram.RenderException: javax.script.ScriptException: java.lang.StackOverflowError in <eval> at line number 27 at column number 596797
        at org.schemaspy.output.diagram.vizjs.VizJSDot.render(VizJSDot.java:74)
        at org.schemaspy.output.diagram.SummaryDiagram.generateSummaryDiagram(SummaryDiagram.java:21)
        ... 16 common frames omitted
ERROR - RelationShipDiagramError
org.schemaspy.output.OutputException: Failed to produce diagram for: /schemaspy/output/doc/diagrams/summary/relationships.implied.large.dot
        at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateImpliedLarge(MustacheSummaryDiagramFactory.java:143)
        at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateSummaryDiagrams(MustacheSummaryDiagramFactory.java:97)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:395)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:289)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:135)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
        at org.schemaspy.Main.main(Main.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.schemaspy.output.diagram.RenderException: Failed to generate summary diagram
        at org.schemaspy.output.diagram.SummaryDiagram.generateSummaryDiagram(SummaryDiagram.java:24)
        at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateImpliedLarge(MustacheSummaryDiagramFactory.java:137)
        ... 15 common frames omitted
Caused by: org.schemaspy.output.diagram.RenderException: javax.script.ScriptException: java.lang.StackOverflowError in <eval> at line number 27 at column number 596334
        at org.schemaspy.output.diagram.vizjs.VizJSDot.render(VizJSDot.java:74)
        at org.schemaspy.output.diagram.SummaryDiagram.generateSummaryDiagram(SummaryDiagram.java:21)
        ... 16 common frames omitted
.Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.schemaspy.output.html.HtmlException: Failed to generate Orphan diagram
        at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.writeDiagram(OrphanDiagram.java:80)
        at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.html(OrphanDiagram.java:56)
        at org.schemaspy.view.HtmlOrphansPage.createPageData(HtmlOrphansPage.java:68)
        at org.schemaspy.view.HtmlOrphansPage.write(HtmlOrphansPage.java:57)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:424)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:289)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:135)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
Caused by: org.schemaspy.output.diagram.RenderException: javax.script.ScriptException: Error: syntax error in line 22101 scanning a HTML string (missing '>'? bad nesting? longer than 16384?)
String starting:<
    <TABLE BORDER="2" CELLBORDER="1" CELLSPACING="0" BGCOLOR="#ffffff">
      <
 in <eval> at line number 94 at column number 4
        at org.schemaspy.output.diagram.vizjs.VizJSDot.render(VizJSDot.java:74)
        at org.schemaspy.output.html.mustache.diagrams.OrphanDiagram.writeDiagram(OrphanDiagram.java:73)
        ... 17 more
```

**Comment by npetzall** [comment]
@CalderonRigoberto the stackoverflow is mentioned in #462, stack size can be increased. This I related to vizjs. Not sure if it recovers from it or if the stackoverflow is the root cause. Switching to graphviz would remove stackoverflow issue.

Not sure but it complains about `/schemaspy/output/doc/diagrams/orphans/orphans.dot` this could be checked, it will contain all tables that lack relationships. So it might contain few or many tables.

I'll try to think of a good way to validate it, if possible.

One way would be to search for `<` to see if any such character seems to be in a strange place, not expected as in the label and the "html" syntax.

Another would be to remove table by table until the malformed is found.
