### ISSUE TITLE
6.2.x crash on my postgres 13 DB, 6.1.0 was fine

### ISSUE THREAD

**Issue by jflambert** [schemaspy/schemaspy#1195]
I've been using 6.1.0 for years and I'm looking forward to using the latest 6.2.x branch but right out of the box I get a crash during "Gathering schema details..."

## Expected Behavior
DB that worked just fine in 6.1.0 should also be compatible with 6.2.x

## Current Behavior
(see context below for versions and command)

When running schemaspy I get a crash when it tries to process something that looks like a system view

```
DEBUG - SELECT datname AS catalog_name, pg_catalog.shobj_description(oid, 'pg_database') AS catalog_comment FROM pg_catalog.pg_database WHERE datname = ? [reporting]
DEBUG - SELECT nspname AS schema_name, pg_catalog.obj_description(oid, 'pg_namespace') AS schema_comment FROM pg_catalog.pg_namespace where nspname = ? [public]
DEBUG - select tc.table_name, tc.constraint_name, cc.check_clause as text from information_schema.check_constraints cc left join information_schema.table_constraints tc on tc.constraint_catalog = cc.constraint_catalog and tc.constraint_schema = cc.constraint_schema and tc.constraint_name = cc.constraint_name where cc.constraint_name not like '%not_null' and tc.constraint_schema = ? [public]
DEBUG - select r.routine_name || '(' || oidvectortypes(p.proargtypes) || ')' as routine_name, case p.prokind when 'f' then 'FUNCTION' when 'p' then 'PROCEDURE' when 'a' then 'AGGREGATE' when 'w' then 'WINDOW' else 'UNKNOWN' end as routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body,r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on r.specific_name = p.proname || '_' || p.oid left join pg_description d on d.objoid = p.oid where r.routine_schema = ? [public]
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "key" is null
	at org.schemaspy.util.CaseInsensitiveMap.put(CaseInsensitiveMap.java:59)
	at org.schemaspy.util.CaseInsensitiveMap.put(CaseInsensitiveMap.java:35)
	at org.schemaspy.input.dbms.service.RoutineService.initRoutines(RoutineService.java:95)
	at org.schemaspy.input.dbms.service.RoutineService.gatherRoutines(RoutineService.java:46)
	at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(DatabaseService.java:132)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:269)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:134)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
	at org.schemaspy.Main.main(Main.java:55)
	... 8 more
```

## Context
* Database type (e.g. MySQL): PostgreSQL 13.11
* Your DDL (sample how to reproduce the issue): will try to provide an anonymized subset if required
* Full command including arguments how you run SchemaSpy: `docker run -v "$PWD:/output" schemaspy/schemaspy:6.2.2 -debug -t pgsql11 -db XXX -u XXX -host XXX -p XXX`

## Your Environment

* Version used: 6.1.0 (works), 6.2.x (doesn't work)
* Environment name and version (e.g. Chrome 39): Docker 24.x 
* Operating System and version (e.g. Windows 10): Ubuntu 22.04 
* Java version: Whatever's in docker...

**Comment by jflambert** [comment]
It looks like my issue is a duplicate of #1115, and the fix has been merged but not yet released.

Please confirm @npetzall, would love to try 6.2.3 when it's out. Thanks.

**Comment by jflambert** [comment]
yes @npetzall  it works! thanks

**Comment by npetzall** [comment]
Release has been create, you can find it under releases, maven is pending the sync to central.
