### ISSUE TITLE
Sqlite Generated Columns fire InconsistencyException and create wrong diagrams

### ISSUE THREAD

**Issue by s-nt-s** [schemaspy/schemaspy#1235]
[sqlite Generated Columns](https://www.sqlite.org/gencol.html):

* fire `InconsistencyException`  when ` java -jar schemaspy-6.2.4.jar`
* show path of file in some name of table in diagrams (ej: `/tmp/schemaspy/example.sqlite.SEGURO`)
* doesn't show some tables in diagrams (it only happens some times)

## Steps to Reproduce (for bugs)

```
$ wget "https://github.com/xerial/sqlite-jdbc/releases/download/3.32.3.2/sqlite-jdbc-3.32.3.2.jar"
$ wget "https://github.com/schemaspy/schemaspy/releases/download/v6.2.4/schemaspy-6.2.4.jar"
$ touch schemaspy.properties sqlite.properties
$ rm -rf out/ example.sqlite && mkdir -p out && cat example.sql | sqlite3 example.sqlite
$ java -jar schemaspy-6.2.4.jar -o "$PWD/out" -dp "$PWD/" -db "$PWD/example.sqlite" -cat example -s example -u example -noviews

  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.2.4

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.2.4 on bot with PID 190127 (/home/*****/wks/tmp/schemaspy/schemaspy-6.2.4.jar started by ****** in /home/*****/wks/tmp/schemaspy)
INFO  - The following profiles are active: default
INFO  - Found configuration file: schemaspy.properties
INFO  - Started Main in 1.284 seconds (JVM running for 1.735)
INFO  - Starting schema analysis
INFO  - Connected to SQLite - 3.32.3
INFO  - Gathering schema details
Gathering schema details...INFO  - Found PK without index name created index 'ASEGURADO_s_pk' for table 'ASEGURADO'
.INFO  - Found PK without index name created index 'COD_RIESGO_s_pk' for table 'COD_RIESGO'
INFO  - Found PK without index name created index 'COD_PROVINCIA_s_pk' for table 'COD_PROVINCIA'
INFO  - Found PK without index name created index 'COD_CULTIVO_s_pk' for table 'COD_CULTIVO'
...INFO  - Found PK without index name created index 'CULTIVO_s_pk' for table 'CULTIVO'
.INFO  - Found PK without index name created index 'POLIZA_s_pk' for table 'POLIZA'
.Exception in thread "Thread-9" org.schemaspy.input.dbms.service.InconsistencyException: Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: 'densidad' in columns['id','poliza','hoja','numero_parcela','plantacion','recinto','modulo','coberturas','arboles','superficie','prod_principal','prod_complementaria','precio','prod_real_esperada','prod_real_final'] of table: "SEGURO"
	at org.schemaspy.input.dbms.service.ColumnService.initColumnAutoUpdate(ColumnService.java:148)
	at org.schemaspy.input.dbms.service.ColumnService.gatherColumns(ColumnService.java:49)
	at org.schemaspy.input.dbms.service.TableService.gatheringTableDetails(TableService.java:95)
	at org.schemaspy.input.dbms.service.DatabaseService$TableCreator.createImpl(DatabaseService.java:357)
	at org.schemaspy.input.dbms.service.DatabaseService$ThreadedTableCreator$1.run(DatabaseService.java:402)
INFO  - Found PK without index name created index 'PLANTACION_s_pk' for table 'PLANTACION'
.INFO  - Found PK without index name created index 'PARCELA_s_pk' for table 'PARCELA'
.INFO  - Found PK without index name created index 'PRIMA_s_pk' for table 'PRIMA'
.INFO  - Found PK without index name created index 'SINIESTRO_s_pk' for table 'SINIESTRO'
.(0sec)
Connecting relationships.............(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
INFO  - Graphviz renderer set to ':cairo'
.ERROR - dot -Tpng:cairo relationships.real.compact.dot -orelationships.real.compact.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo relationships.real.compact.dot -orelationships.real.compact.png -Tcmapx: in label of node PRIMA
ERROR - dot -Tpng:cairo relationships.real.large.dot -orelationships.real.large.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo relationships.real.large.dot -orelationships.real.large.png -Tcmapx: in label of node PRIMA
.......(1sec)
Writing/diagramming detailsINFO  - Completed summary in 1 seconds
INFO  - Writing/diagramming details
ERROR - dot -Tpng:cairo ASEGURADO.2degrees.dot -oASEGURADO.2degrees.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo ASEGURADO.2degrees.dot -oASEGURADO.2degrees.png -Tcmapx: in label of node PRIMA
.ERROR - dot -Tpng:cairo COD_PROVINCIA.1degree.dot -oCOD_PROVINCIA.1degree.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo COD_PROVINCIA.1degree.dot -oCOD_PROVINCIA.1degree.png -Tcmapx: in label of node PRIMA
ERROR - dot -Tpng:cairo COD_PROVINCIA.2degrees.dot -oCOD_PROVINCIA.2degrees.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo COD_PROVINCIA.2degrees.dot -oCOD_PROVINCIA.2degrees.png -Tcmapx: in label of node PRIMA
.ERROR - dot -Tpng:cairo SINIESTRO.2degrees.dot -oSINIESTRO.2degrees.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo SINIESTRO.2degrees.dot -oSINIESTRO.2degrees.png -Tcmapx: in label of node PRIMA
.ERROR - dot -Tpng:cairo POLIZA.1degree.dot -oPOLIZA.1degree.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo POLIZA.1degree.dot -oPOLIZA.1degree.png -Tcmapx: in label of node PRIMA
ERROR - dot -Tpng:cairo POLIZA.2degrees.dot -oPOLIZA.2degrees.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo POLIZA.2degrees.dot -oPOLIZA.2degrees.png -Tcmapx: in label of node PRIMA
..ERROR - dot -Tpng:cairo PRIMA.1degree.dot -oPRIMA.1degree.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo PRIMA.1degree.dot -oPRIMA.1degree.png -Tcmapx: in label of node PRIMA
ERROR - dot -Tpng:cairo PRIMA.2degrees.dot -oPRIMA.2degrees.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo PRIMA.2degrees.dot -oPRIMA.2degrees.png -Tcmapx: in label of node PRIMA
.ERROR - dot -Tpng:cairo PARCELA.2degrees.dot -oPARCELA.2degrees.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo PARCELA.2degrees.dot -oPARCELA.2degrees.png -Tcmapx: in label of node PRIMA
...ERROR - dot -Tpng:cairo COD_RIESGO.1degree.dot -oCOD_RIESGO.1degree.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo COD_RIESGO.1degree.dot -oCOD_RIESGO.1degree.png -Tcmapx: in label of node PRIMA
ERROR - dot -Tpng:cairo COD_RIESGO.2degrees.dot -oCOD_RIESGO.2degrees.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo COD_RIESGO.2degrees.dot -oCOD_RIESGO.2degrees.png -Tcmapx: in label of node PRIMA
.(1sec)
Wrote relationship details of 10 tables/views to directory '/tmp/schemaspy/out' in 3 seconds.
View the results by opening /tmp/schemaspy/out/index.html
INFO  - Wrote table details in 1 seconds
INFO  - Wrote relationship details of 10 tables/views to directory '/tmp/schemaspy/out' in 3 seconds.
INFO  - View the results by opening /tmp/schemaspy/out/index.html
```

![imagen](https://github.com/schemaspy/schemaspy/assets/5998601/2f17f8e1-f057-4a2f-ba93-2ac931bff896)

## Context

`schemaspy.properties` is:

```
schemaspy.t=sqlite
schemaspy.sso=true
```

`sqlite.properties` is:

```
driver=org.sqlite.JDBC
description=SQLite
driverPath=sqlite-jdbc-3.32.3.2.jar
connectionSpec=jdbc:sqlite:<db>
```

`example.sql` is:

```sql
CREATE TABLE COD_PROVINCIA (
    provincia int NOT NULL PRIMARY KEY,
    nombre nvarchar(20)
);

CREATE TABLE COD_CULTIVO (
    cultivo int NOT NULL PRIMARY KEY,
    nombre nvarchar(20)
);

CREATE TABLE ASEGURADO (
    nif nvarchar(9) NOT NULL PRIMARY KEY
);

CREATE TABLE CULTIVO (
    id int IDENTITY(1,1) PRIMARY KEY,
    cultivo int NOT NULL,
    grupo_varietal nvarchar(5) NOT NULL,
    variedad int NOT NULL,
    CONSTRAINT UQ_GRUPO_VARIETAL UNIQUE(cultivo, grupo_varietal, variedad),
    FOREIGN KEY(cultivo) REFERENCES COD_CULTIVO(cultivo)
);

CREATE TABLE PARCELA (
    id int IDENTITY(1,1) PRIMARY KEY,
    provincia int not NULL,
    comarca int,
    termino int NOT NULL,
    agregacion int NOT NULL,
    zona int NOT NULL,
    poligono int NOT NULL,
    parcela int NOT NULL,
    CONSTRAINT UQ_SIGPAC UNIQUE(provincia, comarca, termino, agregacion, zona, poligono, parcela),
    FOREIGN KEY(provincia) REFERENCES COD_PROVINCIA(provincia)
);

CREATE TABLE PLANTACION (
    id int IDENTITY(1,1) PRIMARY KEY,
    parcela int not NULL,
    cultivo int NOT NULL, 
    anio int NOT NULL,
    CONSTRAINT UQ_PLANTACION UNIQUE(parcela, cultivo, anio),
    FOREIGN KEY(parcela) REFERENCES PARCELA(id),
    FOREIGN KEY(cultivo) REFERENCES CULTIVO(id)
);

CREATE TABLE POLIZA (
    referencia nvarchar(7) NOT NULL PRIMARY KEY,
    anio int NOT NULL,
    nif nvarchar(9) NOT NULL,
    FOREIGN KEY(nif) REFERENCES ASEGURADO(nif)
);

CREATE TABLE SEGURO (
    id int IDENTITY(1,1) PRIMARY KEY,
    poliza nvarchar(7) not NULL,
    hoja int NOT NULL,
    numero_parcela int not NULL,
    plantacion int not NULL,
    recinto int NOT NULL,
    modulo nvarchar(2) NOT NULL,
    coberturas int NOT NULL,
    arboles int NOT NULL,
    superficie numeric(7,2) NOT NULL,
    prod_principal int NOT NULL,
    prod_complementaria int,
    precio numeric(7,4) NOT NULL,
    prod_real_esperada int,
    prod_real_final int,
    prod_asegurada FLOAT AS (prod_principal+IFNULL(prod_complementaria, 0)),
    rend_asegurado FLOAT AS ((prod_principal+IFNULL(prod_complementaria, 0))/superficie),
    rend_arbol     FLOAT AS ((prod_principal+IFNULL(prod_complementaria, 0))/arboles),
    densidad       FLOAT AS (arboles/superficie),
    CONSTRAINT UQ_SEGURO UNIQUE(poliza, numero_parcela, hoja),
    FOREIGN KEY(poliza) REFERENCES POLIZA(referencia),
    FOREIGN KEY(plantacion) REFERENCES PLANTACION(id)
);

CREATE TABLE COD_RIESGO (
    riesgo int not NULL PRIMARY KEY,
    nombre nvarchar(34)
);

CREATE TABLE SINIESTRO (
    id int IDENTITY(1,1) PRIMARY KEY,
    seguro int not NULL,
    riesgo int not NULL,
    kg_perdidos int not NULL,
    danio_calidad numeric(5,2) not null,
    danio_cantidad numeric(5,2) not null,
    indemnizacion  numeric(8,2) not null,
    CONSTRAINT UQ_SINIESTRO UNIQUE(seguro, riesgo),
    FOREIGN KEY(seguro) REFERENCES SEGURO(id),
    FOREIGN KEY(riesgo) REFERENCES COD_RIESGO(riesgo)
);

CREATE TABLE PRIMA (
    id int IDENTITY(1,1) PRIMARY KEY,
    poliza nvarchar(7) not NULL,
    riesgo int not NULL,
    prima_riesgo_recargada numeric(13,5) not NULL,
    prima_pura numeric(13,5) not NULL,
    indemnizacion numeric(13,5) not null,
    provincia int,
    FOREIGN KEY(poliza) REFERENCES POLIZA(referencia),
    FOREIGN KEY(riesgo) REFERENCES COD_RIESGO(riesgo),
    FOREIGN KEY(provincia) REFERENCES COD_PROVINCIA(provincia)
);

pragma integrity_check;
VACUUM;
```

## Your Environment

* Version used: schemaspy-6.2.4.jar
* Operating System and version: Linux Mint 21.2
* Java version: 

```
$ java --version
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing)
```

**Comment by npetzall** [comment]
Hi,

I tested it I have a Mac M1 and for support I always use the latest versions of things. So I had no issue.
I went over and looked at the change logs.
[Release 3.39.2.1](https://github.com/xerial/sqlite-jdbc/releases/tag/3.39.2.1)
Has an interesting fix.
[05c45bb](https://github.com/xerial/sqlite-jdbc/commits/05c45bb) return generated columns in DatabaseMetaData.getColumns

Would you mind testing with that version or maybe [Release 3.42.0.0](https://github.com/xerial/sqlite-jdbc/releases/tag/3.42.0.0)

Since I'm not sure I can get your version to work on my M1.

**Comment by s-nt-s** [comment]
You are right, It is working with [3.42.0.0](https://github.com/xerial/sqlite-jdbc/releases/tag/3.42.0.0)

Thanks.
