### ISSUE TITLE
"-all" parameter and multiple schemas usage broken for MSSQL/jtds

### ISSUE THREAD

**Issue by michaelklotz** [schemaspy/schemaspy#129]
When upgrading from version 5 to version 6 RC, I am experiencing the following issue with JTDS for Microsoft SQL Server when using the "-sso" option.

using JTDS v 1.3.1 (current)
ntlmauth.dll file location `C:\Program Files (x86)\Java\jre1.8.0_40\bin\ntlmauth.dll`

example commands
```
# old command, working...
"C:\Program Files (x86)\Java\jre1.8.0_40\bin\java.exe" -jar "Z:\Common\SchemaSpy\dependencies\schemaspy_5.0.0.jar" -t jtds -db AdventureWorks2012 -o "Z:\Common\SchemaSpy\local\AdventureWorks2012" -host localhost -port 1433 -dp "Z:\Common\SchemaSpy\dependencies\jtds-1.3.1-dist\jtds-1.3.1.jar" -sso -all -noimplied
# new command, not working...
"C:\Program Files (x86)\Java\jre1.8.0_40\bin\java.exe" -jar "Z:\Common\SchemaSpy\dependencies\schemaspy-6.0.0-rc1.jar" -t jtds -db AdventureWorks2012 -o "Z:\Common\SchemaSpy\local\AdventureWorks2012" -host localhost -port 1433 -dp "Z:\Common\SchemaSpy\dependencies\jtds-1.3.1-dist\jtds-1.3.1.jar" -sso -all -noimplied
```
Output
```
$ java -jar "Z:\Common\SchemaSpy\dependencies\schemaspy-6.0.0-rc1.jar" -t jtds -db AdventureWorks2012 -o "Z:\Common\SchemaSpy\local\AdventureWorks2012" -host localhost -port 1433 -dp "Z:\Common\SchemaSpy\dependencies\jtds-1.3.1-dist\jtds-1.3.1.jar" -sso -all -noimplied
Aug 01, 2017 11:10:17 AM org.springframework.context.annotation.AnnotationConfigApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@b1bc7ed: startup date [Tue Aug 01 11:10:17 CDT 2017]; root of context hierarchy
Aug 01, 2017 11:10:17 AM org.schemaspy.Config loadProperties
INFO: Configuration file not found
Aug 01, 2017 11:10:18 AM org.schemaspy.DbDriverLoader getConnection
INFO: Using database properties:
Aug 01, 2017 11:10:18 AM org.schemaspy.DbDriverLoader getConnection
INFO:   [Z:\Common\SchemaSpy\dependencies\schemaspy-6.0.0-rc1.jar]/org/schemaspy/types/jtds.properties
Analyzing schemas that match regular expression '.*':
(use -schemaSpec on command line or in .properties to exclude other schemas)
Analyzing schemas: [HumanResources, INFORMATION_SCHEMA, Person, Production, Purchasing, Sales, dbo, sys]
Analyzing HumanResources
Using database properties:
  [Z:\Common\SchemaSpy\dependencies\schemaspy-6.0.0-rc1.jar]/org/schemaspy/types/jtds.properties

Failed to connect to database URL [jdbc:jtds:sqlserver://localhost:1433;databaseName=AdventureWorks2012;progName=schemaSpy]

java.sql.SQLException: I/O Error: SSO Failed: Native SSPI library not loaded. Check the java.library.path system property.
        at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.java:654)
        at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:371)
        at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:184)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:66)
        at org.schemaspy.service.SqlService.connect(SqlService.java:65)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:197)
        at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:130)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:82)
        at org.schemaspy.Main.main(Main.java:52)
Caused by: java.io.IOException: SSO Failed: Native SSPI library not loaded. Check the java.library.path system property.
        at net.sourceforge.jtds.jdbc.TdsCore.sendMSLoginPkt(TdsCore.java:1963)
        at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.java:617)
        ... 8 more
11:10:18.818 WARNING: Main.main - Connection Failure
org.schemaspy.model.ConnectionFailure: java.sql.SQLException: I/O Error: SSO Failed: Native SSPI library not loaded. Check the java.library.path system property.
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:92)
        at org.schemaspy.service.SqlService.connect(SqlService.java:65)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:197)
        at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:130)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:82)
        at org.schemaspy.Main.main(Main.java:52)
Caused by: java.sql.SQLException: I/O Error: SSO Failed: Native SSPI library not loaded. Check the java.library.path system property.
        at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.java:654)
        at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:371)
        at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:184)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:66)
        ... 5 more
Caused by: java.io.IOException: SSO Failed: Native SSPI library not loaded. Check the java.library.path system property.
        at net.sourceforge.jtds.jdbc.TdsCore.sendMSLoginPkt(TdsCore.java:1963)
        at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.java:617)
        ... 8 more
```

**Comment by msimanga** [comment]
I also had issues getting SSO to work. Some items that helped in my case.

1. I explictly included path to dll in command to run jar file. No matter what I did I kept getting _Native SSPI library not loaded._ So my final command was
`java -Djava.library.path=D:\Path\To\jtds-1.3.1-dist\x64\SSO -jar schemaspy-6.0.0-rc1.jar -configFile my _config.properties`

2. Here is redacted copy of my config file

> schemaspy.t=mssql-jtds
> schemaspy.host=my_db_host 
> schemaspy.port=#### 
> schemaspy.db=my_db 
> schemaspy.sso 
> schemaspy.u 
> schemaspy.o=D:\path\to\documentation 
> schemaspy.s=dbo 

Hope this helps

**Comment by michaelklotz** [comment]
With the help of @msimanga comment, I am able to isolate the issue to the usage of the "-all" parameter.  That is to say, when using it, I get the `java.sql.SQLException: I/O Error: SSO Failed: Native SSPI library not loaded.` - and when I don't, it runs just fine.

**Comment by npetzall** [comment]
@rafalkasa Ok if i investigate this issue or have you started?

First `-s`doesn't support list of schemas, one needs to use `-schemas` so in the example above it tries to find schema `HumanResources,Person`which doesn't exist.

It's really weird it actually able to connect and list all schemas it finds but than is unable to analyze them.

@michaelklotz 
1, Without specifying `-Djava.library.path`it work with single schema? Yes/No
2, Specifying `-Djava.library.path`it works but not with `-all`? Yes/No
2, Doesn't work at all with -all? Yes/No

**Comment by npetzall** [comment]
Created new issue #243 since -sso option isnt working after jCommander introduction.

**Comment by npetzall** [comment]
Reproduced, validate an assumption. Made it work, don't know why. Will work on a fix with a reason why the fix works.

**Comment by npetzall** [comment]
java.lang.UnsatisfiedLinkError: Native Library ......SSO\ntlmauth.dll already loaded in another classloader

Is the root cause of problems and this has to do with multiple different classloaders used to connect to DB.
When -all is used it will create a first DbDriverLoader and new Classloader, it will load jtds and ntlmauth and set a flag that it has been loaded and also provide a static instance. That static instance lives in the newly created classloader.

When individual schemas are to be analysed, a new DbDriverLoader together with a new static instance will be created. Since a new instance is created the previously set loaded flag is now reset and jtds tries to load ntlmauth again but with a different class loader.

So the solution is probably to refactor so that Driver is either cached or have DbDriverLoader as a singleton. Will hopefully work on this tomorrow.
