### ISSUE TITLE
No fontmanager in java.library.path exception

### ISSUE THREAD

**Issue by Mihailoff** [schemaspy/schemaspy#133]
```
Writing/graphing summary..........Exception in thread "main" java.lang.UnsatisfiedLinkError: no fontmanager in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
	at sun.font.SunFontManager$1.run(SunFontManager.java:339)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<clinit>(SunFontManager.java:335)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:82)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Font.getFont2D(Font.java:491)
	at java.awt.Font.access$000(Font.java:224)
	at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)
	at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)
	at sun.font.StandardGlyphVector.initFontData(StandardGlyphVector.java:1126)
	at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1115)
	at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:172)
	at java.awt.Font.getStringBounds(Font.java:2421)
	at java.awt.Font.getStringBounds(Font.java:2331)
	at org.schemaspy.view.DotNode.getTextWidth(DotNode.java:230)
	at org.schemaspy.view.DotNode.getColumnMaxWidth(DotNode.java:215)
	at org.schemaspy.view.DotNode.toString(DotNode.java:126)
	at org.schemaspy.view.DotFormatter.writeOrphan(DotFormatter.java:341)
	at org.schemaspy.view.HtmlOrphansPage.write(HtmlOrphansPage.java:98)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:428)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:267)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
	at org.schemaspy.Main.main(Main.java:52)
```

Alpine Linux / schemaspy-6.0.0-rc1.jar / MySQL
```
apk add openjdk8-jre-base graphviz mysql-client fontconfig ttf-dejavu unzip openssl
unzip open-sans.zip -d /usr/share/fonts
fc-cache -fv
```

**Comment by npetzall** [comment]
Is this an issue with docker image? If so could you supply the sha for the image you used?

**Comment by Mihailoff** [comment]
No, I'm downloading the `schemaspy-6.0.0-rc1.jar` file and run in.

**Comment by npetzall** [comment]
So actually not a bug in the software, more of documentation on how to get it running on alpine.

The docker image we have is based on alpine. So I sort of know about the issue. I would classify it as documentation and at the same time I sort of think this is more of a how-to get a fully functional Java runtime on alpine and as such I see it as out-of-scope for schemaspy.

**Comment by npetzall** [comment]
Yeah I assume you got it running or do you need help. You can check the Dockerfile at the root of the repo on how to get it running. I also know of a change in openjdk 8 that killed something on alpine.

**Comment by Mihailoff** [comment]
Yes, it's not a bug.

Got it working by changing Alpine package from `openjdk8-jre-base` to `openjdk8-jre`.

This is working code to set up the environment
```
apk add openjdk8-jre graphviz mysql-client fontconfig ttf-dejavu unzip openssl
curl https://www.fontsquirrel.com/fonts/download/open-sans -J -O
unzip open-sans.zip -d /usr/share/fonts
fc-cache -fv
```
