### ISSUE TITLE
Driver Error

### ISSUE THREAD

**Issue by KhemrajShankarappa** [schemaspy/schemaspy#1414]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Database type (e.g. MySQL):
* Database driver version (is you use a special one):
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):  Chrome
* Operating System and version (e.g. Windows 10): Windows 10
* Java version: Java 8

Please help to resolve below error:
INFO  - Starting schema analysis
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.NoClassDefFoundError: oracle/dms/console/DMSConsole
        at oracle.jdbc.driver.DMSFactory.<clinit>(DMSFactory.java:48)
        at oracle.jdbc.driver.PhysicalConnection.createDMSSensors(PhysicalConnection.java:1742)
        at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:868)
        at oracle.jdbc.driver.T2CConnection.<init>(T2CConnection.java:228)
        at oracle.jdbc.driver.T2CDriverExtension.getConnection(T2CDriverExtension.java:56)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:828)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:628)
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:123)
        at org.schemaspy.input.dbms.service.SqlService.connect(SqlService.java:69)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:244)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:135)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more

**Comment by npetzall** [comment]
What `-t` argument are you using?
What `-dp` argument are you using?

The error seems to indicate that the driver is split into multiple jars. Driver has dependencies and they are not loaded.

All required driver jars can be put in a folder and that folder can be specified with `-dp`

**Comment by KhemrajShankarappa** [comment]
java -jar schemaspy-6.2.4.jar -t ora -dp E:\oracle\product\19.0.0.0\dbhome_1\jdbc\lib -host 1.....

i see this "ojdbc8dms " and other files at this location

**Comment by npetzall** [comment]
I'm not an Oracle expert and the support for Oracle was added before I joined. But there are two different configurations and 1 sub configuration

So there is the `-t ora`, `-t orathin` and `-t orathin-service`.

I've used the thin with just a single downloaded jar file. But I'll see if I can do a little research on the std ora option.

**Comment by KhemrajShankarappa** [comment]
I tried above options but still same issue

**Comment by npetzall** [comment]
We have automatic test that we run against oracle.

We use the thin driver downloaded from maven central https://search.maven.org/artifact/com.oracle.database.jdbc/ojdbc8/21.1.0.0/jar

And we have the following basic config when running SchemaSpy.

```
-t orathin -cat % -db xe
```

`-db` is the SID for the database instance, in the above example we use a container which has the SID set to `xe`

**Comment by KhemrajShankarappa** [comment]
this new driver with cat % helped. thanks a lot. i could able to generate report. 
Report has all the data except ER diagram, Relationships tab is empty. i see below message 
 cell size too small for content
any suggestions pls

**Comment by KhemrajShankarappa** [comment]
Sorry for wrong update: i see diagrams.  

It will be great help if you can tell me how can i fix this "cell size too small for content"
