### ISSUE TITLE
java.awt.AWTError: Can't connect to X11 window server

### ISSUE THREAD

**Issue by mapausch** [schemaspy/schemaspy#142]
Currently I am trying schemaspy-6.0.0-rc1.

During the run I get a exception that says "Can't conect to X11 window server":

```
Aug 30, 2017 10:50:37 AM org.springframework.context.annotation.AnnotationConfigApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@30dae81: startup date [Wed Aug 30 10:50:37 CEST 2017]; root of context hierarchy
Aug 30, 2017 10:50:38 AM org.schemaspy.Config loadProperties
INFO: Configuration file not found
10:50:38.410 WARNING: Config.getPort - null
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.valueOf(Integer.java:766)
        at org.schemaspy.Config.getPort(Config.java:367)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.schemaspy.Config.populate(Config.java:1647)
        at org.schemaspy.Config.getRemainingParameters(Config.java:1465)
        at org.schemaspy.util.ConnectionURLBuilder.<init>(ConnectionURLBuilder.java:47)
        at org.schemaspy.service.SqlService.connect(SqlService.java:46)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:197)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
        at org.schemaspy.Main.main(Main.java:52)
10:50:38.416 WARNING: Config.getPort - null
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.valueOf(Integer.java:766)
        at org.schemaspy.Config.getPort(Config.java:367)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.schemaspy.Config.populate(Config.java:1647)
        at org.schemaspy.Config.getRemainingParameters(Config.java:1465)
        at org.schemaspy.util.ConnectionURLBuilder.<init>(ConnectionURLBuilder.java:53)
        at org.schemaspy.service.SqlService.connect(SqlService.java:46)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:197)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
        at org.schemaspy.Main.main(Main.java:52)
10:50:38.419 WARNING: Config.getPort - null
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.valueOf(Integer.java:766)
        at org.schemaspy.Config.getPort(Config.java:367)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.schemaspy.Config.populate(Config.java:1647)
        at org.schemaspy.Config.getRemainingParameters(Config.java:1465)
        at org.schemaspy.service.SqlService.connect(SqlService.java:50)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:197)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
        at org.schemaspy.Main.main(Main.java:52)
Using database properties:
  /srv/www/vhosts/schemaspy/scripts/f/./db_dev.properties
Gathering schema details...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................(64sec)
Connecting relationships...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................(223sec)
Writing/graphing summary..........Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at sun.awt.X11FontManager.isHeadless(X11FontManager.java:509)
        at sun.awt.X11FontManager.getFileNameFromPlatformName(X11FontManager.java:189)
        at sun.font.SunFontManager.initCompositeFonts(SunFontManager.java:3481)
        at sun.font.SunFontManager.access$700(SunFontManager.java:65)
        at sun.font.SunFontManager$2.run(SunFontManager.java:545)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.SunFontManager.<init>(SunFontManager.java:376)
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at java.awt.Font.getFont2D(Font.java:491)
        at java.awt.Font.access$000(Font.java:224)
        at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)
        at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)
        at sun.font.StandardGlyphVector.initFontData(StandardGlyphVector.java:1126)
        at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1115)
        at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:172)
        at java.awt.Font.getStringBounds(Font.java:2421)
        at java.awt.Font.getStringBounds(Font.java:2331)
        at org.schemaspy.view.DotNode.getTextWidth(DotNode.java:230)
        at org.schemaspy.view.DotNode.getColumnMaxWidth(DotNode.java:215)
        at org.schemaspy.view.DotNode.toString(DotNode.java:126)
        at org.schemaspy.view.DotFormatter.writeOrphan(DotFormatter.java:341)
        at org.schemaspy.view.HtmlOrphansPage.write(HtmlOrphansPage.java:98)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:428)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:267)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
        at org.schemaspy.Main.main(Main.java:52)
```

I'm connected via SSH to a linux server that provides the outputs of schemaspy via http.
I run schemaspy with following command:

`java -jar schemaspy-6.0.0-rc1.jar -dp ojdbc8.jar -t  db_dev.properties -s MYSCHEMA -u MYDBUSER -p MYDBPASS -o schemas/db_dev`

Why does schemaspy need a graphics interface?

**Comment by mapausch** [comment]
Sorry, just recognised that downloading schemaspy@latest gives a more current version than downloading RC1.
in schemaspy@latest the error does not occur anymore.
So from my view this issue can be closed.
