### ISSUE TITLE
Connection Issue with Postgres16

### ISSUE THREAD

**Issue by ohanubhavkumar** [schemaspy/schemaspy#1532]
We are using PostgreSQL 16 version flexible server from Azure(Cloud) and while generating schema using schemaspy jarfile getting below error:-
#12 13.39 WARN  - Connection Failure
#12 13.39 org.schemaspy.input.dbms.exceptions.ConnectionFailure: Failed to connect to database URL [jdbc:postgresql://****:5432/****] The connection attempt failed.
#12 13.39 	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:110)
#12 13.39 	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:84)
#12 13.39 	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:64)
#12 13.39 	at org.schemaspy.input.dbms.service.SqlService.connect(SqlService.java:69)
#12 13.39 	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:243)
#12 13.39 	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:134)
#12 13.39 	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
#12 13.39 	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
#12 13.39 	at org.schemaspy.Main.main(Main.java:55)
#12 13.39 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#12 13.39 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#12 13.39 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#12 13.39 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#12 13.39 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
#12 13.39 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
#12 13.39 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
#12 13.39 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
#12 13.39 Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
#12 13.39 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:364)
#12 13.39 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
#12 13.39 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
#12 13.39 	at org.postgresql.Driver.makeConnection(Driver.java:446)
#12 13.39 	at org.postgresql.Driver.connect(Driver.java:298)
#12 13.39 	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:103)
#12 13.39 	... 16 common frames omitted
#12 13.39 Caused by: java.net.SocketTimeoutException: connect timed out
#12 13.39 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
#12 13.39 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
#12 13.39 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
#12 13.39 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
#12 13.39 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
#12 13.39 	at java.base/java.net.Socket.connect(Socket.java:609)
#12 13.39 	at org.postgresql.core.PGStream.createSocket(PGStream.java:260)
#12 13.39 	at org.postgresql.core.PGStream.<init>(PGStream.java:121)
#12 13.39 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:140)
#12 13.39 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:268)

* Full command including arguments how you run SchemaSpy:
* java -jar "schemaspy-6.2.0.jar" -dp "postgresql-42.7.4.jar" -t pgsql11 -db "DB_NAME" -host "DB_HOST" -port 5432 -u "DB_USER" -p "DB_PASSWORD" -o "path_to_output_folder" -vizjs -degree 1

**Comment by npetzall** [comment]
When connecting to Azure Postgresql, you'll need to enable SQL mode

`?sslmode=require`, but you'll also need to make sure that you have correct firewall rules in Azure and depending on the stup this could involve private endpoint/links and DNS records.

So you'll at least need to add `-connpros sslmode\\=require` ord `-connprops sslmode\=require` depending on which terminal/shell you're using.

Reading https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/connect-java?tabs=password

It also mentions that you might need to set `serverTimezone=UTC`.

In that case it would be `-connprops sslmode\\=require;serverTimezone\\=UTC` or `-connprops sslmode\=require;serverTimezone\=UTC`

https://schemaspy.readthedocs.io/en/latest/configuration/commandline.html#connecting

The escaping `=` is a bit of problem but it's either `\\=` or `\=`

**Comment by ohanubhavkumar** [comment]
Hi @npetzall ,
Thank you for the response. Tried both the -connprops command but didn't worked getting below error:-

#12 1.383 INFO  - Starting Main v6.1.0 on buildkitsandbox with PID 7 (/build/schemaspy-6.1.0.jar started by root in /build)
#12 1.384 INFO  - The following profiles are active: default
#12 2.169 INFO  - Started Main in 1.317 seconds (JVM running for 1.78)
#12 2.195 DEBUG - Debug enabled
#12 2.197 INFO  - Starting schema analysis
#12 2.232 DEBUG - Resolving dbType: pgsql11 ->
#12 2.232 	pgsql11.properties ->
#12 2.232 	schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/pgsql.properties
#12 2.246 DEBUG - DbSpecificOption name: 'hostOptionalPort' value: '****:5432' description: 'null'
#12 2.248 DEBUG - DbSpecificOption name: 'db' value: **** description: 'database name'
#12 12.31 WARN  - Connection Failure
#12 12.31 org.schemaspy.input.dbms.exceptions.ConnectionFailure: Failed to connect to database URL [jdbc:postgresql://****:5432/****] The connection attempt failed.
#12 12.31 	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:101)
#12 12.31 	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:75)
#12 12.31 	at org.schemaspy.input.dbms.service.SqlService.connect(SqlService.java:70)
#12 12.31 	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:220)
#12 12.31 	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
#12 12.31 	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
#12 12.31 	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
#12 12.31 	at org.schemaspy.Main.main(Main.java:55)
#12 12.31 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#12 12.31 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#12 12.31 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#12 12.31 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#12 12.31 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
#12 12.31 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
#12 12.31 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
#12 12.31 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
#12 12.31 Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
#12 12.31 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331)
#12 12.31 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
#12 12.31 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
#12 12.31 	at org.postgresql.Driver.makeConnection(Driver.java:402)
#12 12.31 	at org.postgresql.Driver.connect(Driver.java:261)
#12 12.31 	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:94)
#12 12.31 	... 15 common frames omitted
#12 12.31 Caused by: java.net.SocketTimeoutException: connect timed out
#12 12.31 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
#12 12.31 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
#12 12.31 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
#12 12.31 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
#12 12.31 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
#12 12.31 	at java.base/java.net.Socket.connect(Socket.java:609)
#12 12.31 	at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
#12 12.31 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
#12 12.31 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
#12 12.31 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
#12 12.31 	... 20 common frames omitted
#12 ERROR: process "/bin/sh -c java -jar "schemaspy-6.2.0.jar" -dp "postgresql-42.7.4.jar" -t pgsql11 -db "DB_NAME" -host "DB_HOST" -port 5432 -u "DB_USER" -p "DB_PASSWORD" -o "path_to_output_folder" -vizjs -degree 1 -connpros sslmode\\=require -debug" did not complete successfully: exit code: 3

**Comment by npetzall** [comment]
I'm so sorry, I had a typo and you copied it.

The argument is `-connprops` and __not__ `-connpros`

**Comment by ohanubhavkumar** [comment]
Hi @npetzall ,
Tried both argument still same issue:--connprops sslmode\\=require ord -connprops sslmode\=require

#12 1.363 INFO  - Starting Main v6.1.0 on buildkitsandbox with PID 7 (/build/schemaspy-6.1.0.jar started by root in /build)
#12 1.363 INFO  - The following profiles are active: default
#12 2.169 INFO  - Started Main in 1.31 seconds (JVM running for 1.781)
#12 2.195 DEBUG - Debug enabled
#12 2.196 INFO  - Starting schema analysis
#12 2.232 DEBUG - Resolving dbType: pgsql11 ->
#12 2.232 	pgsql11.properties ->
#12 2.232 	schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/pgsql.properties
#12 2.243 DEBUG - DbSpecificOption name: 'hostOptionalPort' value: '****:5432' description: 'null'
#12 2.245 DEBUG - DbSpecificOption name: 'db' value: **** description: 'database name'
#12 12.29 WARN  - Connection Failure
#12 12.29 org.schemaspy.input.dbms.exceptions.ConnectionFailure: Failed to connect to database URL [jdbc:postgresql://****:5432/****] The connection attempt failed.
#12 12.29 	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:101)
#12 12.29 	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:75)
#12 12.29 	at org.schemaspy.input.dbms.service.SqlService.connect(SqlService.java:70)
#12 12.29 	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:220)
#12 12.29 	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
#12 12.29 	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
#12 12.29 	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
#12 12.29 	at org.schemaspy.Main.main(Main.java:55)
#12 12.29 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#12 12.29 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#12 12.29 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#12 12.29 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#12 12.29 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
#12 12.29 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
#12 12.29 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
#12 12.29 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
#12 12.29 Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
#12 12.29 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331)
#12 12.29 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
#12 12.29 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
#12 12.29 	at org.postgresql.Driver.makeConnection(Driver.java:402)
#12 12.29 	at org.postgresql.Driver.connect(Driver.java:261)
#12 12.29 	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:94)
#12 12.29 	... 15 common frames omitted
#12 12.29 Caused by: java.net.SocketTimeoutException: connect timed out
#12 12.29 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
#12 12.29 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
#12 12.29 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
#12 12.29 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
#12 12.29 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
#12 12.29 	at java.base/java.net.Socket.connect(Socket.java:609)
#12 12.29 	at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
#12 12.29 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
#12 12.29 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
#12 12.29 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
#12 12.29 	... 20 common frames omitted
#12 ERROR: process "/bin/sh -c java -jar "schemaspy-6.1.0.jar" -dp "postgresql-42.3.5.jar" -t pgsql11 -db "DB_NAME" -host "DB_HOST" -port 5432 -u "DB_USER" -p "DB_PASSWORD" -o "path_to_output_folder" -vizjs -degree 1 -connprops sslmode\\\\=require -debug" did not complete successfully: exit code: 3
Got this error.
