### ISSUE TITLE
Oracle DB Error - Catalog name can't be null

### ISSUE THREAD

**Issue by rpwestcott** [schemaspy/schemaspy#160]
Using  6.0.0-rc2 with same command used for years. (custom orathin.properties only for the slash/colon difference with Oracle 12c

java -jar /apps/schemaspy/schemaspy-6.0.0-rc2.jar -noads -nologo -maxdet 100000 -t orathin -host HOSTNAME -port 1521 -db SERVICENAME -s DBSCHEMA -u DBUSER -p DBPASS -o /apps/www/schemaspy/OUTPUTDIR  -dp /apps/schemaspy/ojdbc7.jar

INFO  - Connected to Oracle - Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Real Application Clusters, Automatic Storage Management, OLAP,
Advanced Analytics and Real Application Testing options
ERROR - Catalog name can't be null
java.lang.IllegalArgumentException: Catalog name can't be null
        at org.schemaspy.model.Catalog.<init>(Catalog.java:33)
        at org.schemaspy.model.Database.<init>(Database.java:77)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:207)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:88)
        at org.schemaspy.Main.runAnalyzer(Main.java:79)
        at org.schemaspy.Main.run(Main.java:72)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
INFO  - Started Main in 6.128 seconds (JVM running for 7.896)

**Comment by npetzall** [comment]
@rpwestcott when you say for years I assume you referring to 5.0 or older version of schemaspy?

**Comment by npetzall** [comment]
slash/colon difference is it like [orathin-service](https://github.com/schemaspy/schemaspy/blob/master/src/main/resources/org/schemaspy/types/orathin-service.properties)

**Comment by mapausch** [comment]
@rpwestcott try to use command line parameter "-cat catalog" or as npetzall suggested "-cat %".
"-cat catalog" works for me, "-cat %" I didn't try.

**Comment by npetzall** [comment]
Might be related in a way with #117 as 2a2cb79a0bf78c30d490e2c1dd22a829c6b282f4 changed what default schema and catalog was set to, if they fail and are null, you'll get the error. Before that commit, you just got two field in the database class that were null.

**Comment by almightynassar** [comment]
Had an extremely old hsqldb database to deal with. Couldn't make headway until I used -cat %. The cat option should be better documented.

My properties file:

```
# type of database. Run with -dbhelp for details
schemaspy.t=hsqldb
# optional path to alternative jdbc drivers.
schemaspy.dp=~/lib/hsqldb.jar
# database properties: host, port number, name user, password
schemaspy.host=localhost
schemaspy.db=database
schemaspy.cat=%
schemaspy.u=SA
schemaspy.p=
# output dir to save generated files
schemaspy.o=~/output
schemaspy.all
```

**Comment by npetzall** [comment]
@almightynassar I guess you solved it by reading the FAQ? If not which places did you go to try to find the information so that we can improve it?

I'm all for a better error message, would that be enough? I really need help with this, since I know the code and have to much knowledge sadly I see everything as obvious.

**Comment by npetzall** [comment]
In reality I want to remove it, but for know I think we could create a better error message. I could add so that it prints the catch all (%) and that I can list the available catalogs, this could be done for schema as well.

**Comment by almightynassar** [comment]
Also just checked out your FAQ and it was quite clearly there. As I mentioned, it was an **extremely** quick troubleshooting exercise. From my end there isn't much more you can do except make the error message a little bit clearer!

Cheers for the excellent piece of software... the results are excellent!

**Comment by npetzall** [comment]
For catalog with #368 it would be 
`Catalog (-cat) was not provided and unable to deduce catalog, wildcard catalog can be used -cat %`

In reality both Catalog and Schema can be null, but our model doesn't support it yet.
