### ISSUE TITLE
 Use long for row count in meta data

### ISSUE THREAD

**Issue by rafalkasa** [schemaspy/schemaspy#23]
https://sourceforge.net/p/schemaspy/bugs/191/

Yes, it is still a problem in the new beta.

Using database properties:
[schemaspy-6.0.0-beta.1.jar]/org/schemaspy/types/mysql.properties
Gathering schema details...java.lang.NumberFormatException: For input string: "2827140533"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:583)
at java.lang.Integer.parseInt(Integer.java:615)
at org.schemaspy.service.DatabaseService.getBasicTableMeta(DatabaseService.java:381)
at org.schemaspy.service.DatabaseService.initTables(DatabaseService.java:81)
at org.schemaspy.service.DatabaseService.gatheringSchemaDetails(DatabaseService.java:48)
at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:175)
at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:83)
at org.schemaspy.Main.main(Main.java:52)

**Comment by rafalkasa** [comment]
Hi pothoven
Thank you very much for your time and verification version schemaspy-6.0.0-beta.1
I confirm this bug, and it will be fixed in next version planed on 23 Dec 2016.

**Comment by rafalkasa** [comment]
It also according to https://sourceforge.net/p/schemaspy/bugs/171/

**Comment by pothoven** [comment]
I can confirm that the fix works now.
