### ISSUE TITLE
How to ignore or select a subset of the tables to include in the diagram

### ISSUE THREAD

**Issue by davidonlaptop** [schemaspy/schemaspy#253]
Trying to map a legacy database where 2 sets of tables should be in separate diagrams. For example, I'd like to only include tables that have the "sec" prefix.

## Expected Behavior
It seems the previous version of schemaspy had this feature using the "-i" command line parameter: https://sourceforge.net/p/schemaspy/feature-requests/41/

## Current Behavior
```
docker run -v "$PWD/doc:/output" -v "$PWD/config:/config" schemaspy/schemaspy:snapshot -t mysql -u root -p mysqlpassword -db CME -schemas "PORTAL" -host 172.17.0.2 -meta /config -i "(.*sec.*)"
Running Main-Class org.springframework.boot.loader.JarLauncher
With drivers:jtds-1.3.1.jar, mariadb-java-client-1.1.10.jar
mysql-connector-java-6.0.6.jar, postgresql-42.1.1.jre7.jar
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0-rc2

SchemaSpy generates an HTML representation of a database schema's relationships.

INFO  - Starting Main v6.0.0-rc2 on 31aee9eca52e with PID 1 (/schemaspy-6.0.0-rc2.jar started by java in /)
INFO  - No active profile set, falling back to default profiles: default
INFO  - Configuration file not found
INFO  - Resolving dbType: mysql ->
	/schemaspy-6.0.0-rc2.jar!/BOOT-INF/classes!/org/schemaspy/types/mysql.properties
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
Analyzing schemas: [PORTAL]
Analyzing PORTAL
INFO  - Starting schema analysis
INFO  - Parsing /config/PORTAL.meta.xml
INFO  - Connected to MySQL - 5.6.38
INFO  - Using additional metadata from /config/PORTAL.meta.xml
INFO  - Gathering schema details
Gathering schema details....................(0sec)
Connecting relationships....................WARN  - Undefined column 'monitorExpectationTemplate.id' referenced by 'monitorEmail.templateId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorEvents.taskId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorExpectationTemplate.taskId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorExpectations.taskId' in XML metadata
WARN  - Undefined column 'monitorExpectationTemplate.id' referenced by 'monitorExpectations.templateId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorJobParams.taskId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorProcessorState.taskId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorTaskDependency.dependingTaskId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorTaskDependency.taskId' in XML metadata
WARN  - Assuming secUserExt.externalApiId is a primary key due to being referenced by secGroup.member
(1sec)
Writing/graphing summary.INFO  - Gathered schema details in 1 seconds
INFO  - Writing/graphing summary
............(3sec)
Writing/diagramming detailsINFO  - Completed summary in 3 seconds
INFO  - Writing/diagramming details
.Table -> secGroupHist
.Table -> secFunc
.Table -> productGeneric
ERROR - null
java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:360)
	at org.schemaspy.view.MustacheWriter.write(MustacheWriter.java:74)
	at org.schemaspy.view.HtmlTablePage.writeMainTable(HtmlTablePage.java:101)
	at org.schemaspy.view.HtmlTablePage.write(HtmlTablePage.java:58)
	at org.schemaspy.SchemaAnalyzer.generateTables(SchemaAnalyzer.java:436)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:392)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:219)
	at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:151)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:96)
	at org.schemaspy.Main.runAnalyzer(Main.java:80)
	at org.schemaspy.Main.run(Main.java:73)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at org.schemaspy.Main.main(Main.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
INFO  - Started Main in 11.133 seconds (JVM running for 11.946)
```

## Possible Solution
Provide a command line parameter to subselect as 

## Steps to Reproduce (for bugs)
See above

## Context
Ask precision if not clear

## Your Environment
OSX (High Sierra) + Docker

**Comment by npetzall** [comment]
The nullpointer your getting is probably due to the Metadata creating a table.

Could you add `-debug` to the command.

**Comment by davidonlaptop** [comment]
Removing the -meta works!

Keeping the -meta flags gives this:
```
docker run -v "$PWD/doc:/output" -v "$PWD/config:/config" schemaspy/schemaspy:snapshot -t mysql -u root -p mysql -db CME -schemas "PORTAL" -host 172.17.0.2 -meta /config -debug -i "(.*sec.*)"
Running Main-Class org.springframework.boot.loader.JarLauncher
With drivers:jtds-1.3.1.jar, mariadb-java-client-1.1.10.jar
mysql-connector-java-6.0.6.jar, postgresql-42.1.1.jre7.jar
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0-rc2

SchemaSpy generates an HTML representation of a database schema's relationships.

INFO  - Starting Main v6.0.0-rc2 on 3d3b5186aa9d with PID 1 (/schemaspy-6.0.0-rc2.jar started by java in /)
INFO  - No active profile set, falling back to default profiles: default
INFO  - Configuration file not found
INFO  - Resolving dbType: mysql ->
	/schemaspy-6.0.0-rc2.jar!/BOOT-INF/classes!/org/schemaspy/types/mysql.properties
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
Analyzing schemas: [PORTAL]
Analyzing PORTAL
INFO  - Starting schema analysis
INFO  - Parsing /config/PORTAL.meta.xml
INFO  - Connected to MySQL - 5.6.38
INFO  - Using additional metadata from /config/PORTAL.meta.xml
INFO  - Gathering schema details
Gathering schema details....................(1sec)
Connecting relationships....................WARN  - Undefined column 'monitorExpectationTemplate.id' referenced by 'monitorEmail.templateId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorEvents.taskId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorExpectationTemplate.taskId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorExpectations.taskId' in XML metadata
WARN  - Undefined column 'monitorExpectationTemplate.id' referenced by 'monitorExpectations.templateId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorJobParams.taskId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorProcessorState.taskId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorTaskDependency.dependingTaskId' in XML metadata
WARN  - Undefined column 'monitorCustomJobs.taskId' referenced by 'monitorTaskDependency.taskId' in XML metadata
WARN  - Assuming secUserExt.externalApiId is a primary key due to being referenced by secGroup.member
(1sec)
Writing/graphing summary.INFO  - Gathered schema details in 1 seconds
INFO  - Writing/graphing summary
............(3sec)
Writing/diagramming detailsINFO  - Completed summary in 3 seconds
INFO  - Writing/diagramming details
.Table -> secGroupHist
.Table -> secFunc
.Table -> productGeneric
ERROR - null
java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:360)
	at org.schemaspy.view.MustacheWriter.write(MustacheWriter.java:74)
	at org.schemaspy.view.HtmlTablePage.writeMainTable(HtmlTablePage.java:101)
	at org.schemaspy.view.HtmlTablePage.write(HtmlTablePage.java:58)
	at org.schemaspy.SchemaAnalyzer.generateTables(SchemaAnalyzer.java:436)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:392)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:219)
	at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:151)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:96)
	at org.schemaspy.Main.runAnalyzer(Main.java:80)
	at org.schemaspy.Main.run(Main.java:73)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at org.schemaspy.Main.main(Main.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
INFO  - Started Main in 12.509 seconds (JVM running for 13.351)
```

**Comment by davidonlaptop** [comment]
OK, I've split my meta in a separate xml for each subset, and still getting a NPE:

```
docker run -v "$PWD/doc:/output" -v "$PWD/config:/config" schemaspy/schemaspy:snapshot -t mysql -u root -p mysql -db CME -schemas "PORTAL" -host 172.17.0.2 -meta /config/PORTAL-ACC.meta.xml -debug -i "(.*sec.*)"
Running Main-Class org.springframework.boot.loader.JarLauncher
With drivers:jtds-1.3.1.jar, mariadb-java-client-1.1.10.jar
mysql-connector-java-6.0.6.jar, postgresql-42.1.1.jre7.jar
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0-rc2

SchemaSpy generates an HTML representation of a database schema's relationships.

INFO  - Starting Main v6.0.0-rc2 on 734aada507df with PID 1 (/schemaspy-6.0.0-rc2.jar started by java in /)
INFO  - No active profile set, falling back to default profiles: default
INFO  - Configuration file not found
INFO  - Resolving dbType: mysql ->
	/schemaspy-6.0.0-rc2.jar!/BOOT-INF/classes!/org/schemaspy/types/mysql.properties
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
Analyzing schemas: [PORTAL]
Analyzing PORTAL
INFO  - Starting schema analysis
INFO  - Parsing /config/PORTAL-ACC.meta.xml
INFO  - Connected to MySQL - 5.6.38
INFO  - Using additional metadata from /config/PORTAL-ACC.meta.xml
INFO  - Gathering schema details
Gathering schema details....................(1sec)
Connecting relationships....................WARN  - Assuming secUserExt.externalApiId is a primary key due to being referenced by secGroup.member
(1sec)
Writing/graphing summary.INFO  - Gathered schema details in 1 seconds
INFO  - Writing/graphing summary
............(2sec)
Writing/diagramming detailsINFO  - Completed summary in 2 seconds
INFO  - Writing/diagramming details
.Table -> secGroupHist
.Table -> secFunc
.Table -> attrSet
ERROR - null
java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:360)
	at org.schemaspy.view.MustacheWriter.write(MustacheWriter.java:74)
	at org.schemaspy.view.HtmlTablePage.writeMainTable(HtmlTablePage.java:101)
	at org.schemaspy.view.HtmlTablePage.write(HtmlTablePage.java:58)
	at org.schemaspy.SchemaAnalyzer.generateTables(SchemaAnalyzer.java:436)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:392)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:219)
	at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:151)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:96)
	at org.schemaspy.Main.runAnalyzer(Main.java:80)
	at org.schemaspy.Main.run(Main.java:73)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at org.schemaspy.Main.main(Main.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
INFO  - Started Main in 9.99 seconds (JVM running for 10.714)
```

**Comment by davidonlaptop** [comment]
ah you were right, there was still 1 table being referenced from the meta that was not included in the regex parameter

Thanks :-)

**Comment by npetzall** [comment]
I've been procrastinating the nullpointer bug. But I'll add an issue for that in a cpl of hrs. You still hit a bug. Either it should work or be ignored, nullpointer is not an option.

**Comment by davidonlaptop** [comment]
Thanks for your dedication @npetzall !
