### ISSUE TITLE
Failing whilst gathering Schema

### ISSUE THREAD

**Issue by alanef** [schemaspy/schemaspy#326]
## Expected Behavior
Gather schema

## Current Behavior
`Fails with ERROR
ERROR - For input string: "YES"
java.lang.NumberFormatException: For input string: "YES"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDouble(MysqlTextValueDecoder.java:228)
        at com.mysql.cj.result.StringConverter.createFromBytes(StringConverter.java:110)
        at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeByteArray(MysqlTextValueDecoder.java:238)
        at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:129)
        at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:233)
        at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:128)
        at com.mysql.cj.jdbc.result.ResultSetImpl.getNonStringValueFromRow(ResultSetImpl.java:628)
        at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:719)
        at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:723)
        at org.schemaspy.service.DatabaseService.initRoutines(DatabaseService.java:816)
        at org.schemaspy.service.DatabaseService.gatheringSchemaDetails(DatabaseService.java:76)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:208)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:88)
        at org.schemaspy.Main.runAnalyzer(Main.java:79)
        at org.schemaspy.Main.run(Main.java:72)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)`

## Steps to Reproduce (for bugs)

docker-compose up -d --build

docker exec -i the-residents-8002_php_1 java -jar schemaspy-6.0.0-rc2.jar -t mysql -o docs -host db:3306 -s residentscivicrm -norows  -db residentscivicrm -u root -p mypass -dp /var/www/html/mysql-connector-java-8.0.11.jar

## Context
Consistently fails

* Database type (e.g. MySQL):  image: mariadb:latest
* Database driver version (is you use a special one): mysql-connector-java-8.0.11.jar
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:
java -jar schemaspy-6.0.0-rc2.jar -t mysql -o docs -host db:3306 -s residentscivicrm -norows  -db residentscivicrm -u root -p mypass -dp /var/www/html/mysql-connector-java-8.0.11.jar

## Your Environment

docker-compose.yml
----------------------------

`version:` '3.3'

services:
   db:
     image: mariadb:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD:  mypass
       MYSQL_DATABASE: wp
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   php:
       depends_on:
         - db
       build: ../../images/for-residents/
       #image: php:7.0-apache
       volumes:
        - ./:/var/www/html
       ports:
         - "8002:80"
       restart: always
       environment:
          XDEBUG_CONFIG: remote_host=172.17.0.1
          
   phpmyadmin:
      depends_on:
         - db
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_ARBITRARY=1
      restart: always
      ports:
       - "9002:80"
      
       
volumes:
       db_data:`

Dockerfile (for-residents)
-------------

`FROM` php:7.0-apache

RUN a2enmod rewrite
RUN   apt-get update

RUN apt-get install -y software-properties-common
RUN add-apt-repository "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main"
RUN echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
RUN echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

RUN   apt-get update \
    && apt-get install -y oracle-java8-installer \
    && apt-get install -y graphviz \
    && apt-get install -y zlib1g-dev \
    && apt-get install -y mysql-client \
    && apt-get install -y wget \
    && apt-get install -y xvfb \
    && apt-get install -y libfontconfig1 libxrender1 \
    && apt-get install -y libxml2-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install zip mysqli simplexml

RUN pecl install xdebug-2.6.0 && docker-php-ext-enable xdebug
RUN echo 'zend_extension="/usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so"' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_port=9000' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_enable=1' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_connect_back=1' >> /usr/local/etc/php/php.ini
RUN echo 'upload_max_filesize=10M' >> /usr/local/etc/php/php.ini
RUN echo 'log_errors = On' >> /usr/local/etc/php/php.ini
RUN echo 'error_log = /dev/stderr' >> /usr/local/etc/php/php.ini
RUN usermod -u 1000 www-data

RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
RUN tar vxf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
RUN cp wkhtmltox/bin/wk* /usr/local/bin/

RUN javac -version`

**Comment by npetzall** [comment]
Hi, could you supply the hash for the mariadb image as shown by the docker instance you received the error. Since latest might not be latest unless you always pull before running the image.

Things I know is that 6.0 mysql driver doesn't support mysql 8.0. Also there is a mariadb databasetype but it expects mariadb driver and not mysql driver. 

I'll be able to test this in a cpl of hrs. We've had issues with booleans in mysql earlier.

Don't think we have tested anything with 8.x yet.

**Comment by npetzall** [comment]
@alanef unfortunately we have same name on latest release and latest build. Is it latest build or release you're using latest build contains fix #244

**Comment by alanef** [comment]
I think I have worked that one out  I was using mysql-connect and I think I have to use mariadb-connect 

But I took a different approach I built the image based on https://hub.docker.com/r/schemaspy/schemaspy/     

And then used docker network to connect to my mariadb container

`docker` run -v "$PWD:/output" --network=mynetwork schemaspy:latest -t mariadb  -host db:3306 -s residentscivicrm -db residentscivicrm -u root -p mypass`

Now this got a LOT further and created lots of js files   

but bailed here 

`Writing/graphing summary.INFO  - Gathered schema details in 80 seconds
INFO  - Writing/graphing summary
.ERROR - null
java.lang.NullPointerException: null
        at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
        at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
        at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
        at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
        at sun.font.SunFontManager$2.run(SunFontManager.java:431)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.SunFontManager.<init>(SunFontManager.java:376)
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at java.awt.Font.getFont2D(Font.java:491)
        at java.awt.Font.access$000(Font.java:224)
        at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)
        at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)
        at sun.font.StandardGlyphVector.initFontData(StandardGlyphVector.java:1126)
        at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1115)
        at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:172)
        at java.awt.Font.getStringBounds(Font.java:2421)
        at java.awt.Font.getStringBounds(Font.java:2331)
        at org.schemaspy.view.DotNode.getTextWidth(DotNode.java:229)
        at org.schemaspy.view.DotNode.getColumnMaxWidth(DotNode.java:214)
        at org.schemaspy.view.DotNode.toString(DotNode.java:126)
        at org.schemaspy.view.DotFormatter.writeRelationships(DotFormatter.java:316)
        at org.schemaspy.view.DotFormatter.writeRealRelationships(DotFormatter.java:264)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:353)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:241)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:88)
        at org.schemaspy.Main.runAnalyzer(Main.java:79)
        at org.schemaspy.Main.run(Main.java:72)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
INFO  - Started Main in 92.028 seconds (JVM running for 93.657)`

**Comment by alanef** [comment]
6.0.0-rc2.jar to answer your earlier question

**Comment by npetzall** [comment]
Since they are named the same. The name doesn't say anything.

What changes did you do to the image?

**Comment by npetzall** [comment]
Also docker image snapshot uses latest, there is a link to latest in the overview.
From what I've heard mariadb should be a drop in replacement. It should be possible to use mysql driver. 
But then again this was said back in 5.x before 8.0 existed.

**Comment by npetzall** [comment]
Add `-debug` and post the stacktrace.

**Comment by npetzall** [comment]
And you used our dockerfile without any changes we'll except jdbc drivers?

**Comment by npetzall** [comment]
Docker pull command is `docker pull schemaspy/schemaspy:snapshot`

Since we haven't done a release since we added docker. 

I'll need to check the queries between Mariadb and mysql. 
I need to test our image also, we had an issue a while back that font in Java changed after Java8 update 111.

**Comment by npetzall** [comment]
Latest build should work I hope else we got a problem. Since you changed the databaseType it's probably a custom query for mariadb that fixed it.

**Comment by alanef** [comment]
Ahha snapshot no latest?
Anyway  schemaspy/schemaspy:snapshot works
`docker run -v "$PWD:/output" --network=mynetwork schemaspy/schemaspy:snapshot -t mariadb  -host db:3306 -s residentscivicrm -db residentscivicrm -u root -p mypass `

Once agin, thanks, will actually do some database work now :)

**Comment by npetzall** [comment]
Root issue was #244 
Had latest build been used from the beginning it should have worked with -t mysql and the mysql-connector-j 8.0.11
The switch to other driver mariadb driver and databaseType solved it in both latest RC and snapshot.
