### ISSUE TITLE
MySQL 5.6: "Schema name can't be null" error

### ISSUE THREAD

**Issue by sampablokuper** [schemaspy/schemaspy#329]
## Expected Behavior

```
$ ssh -f -o ExitOnForwardFailure=yes -L 10000:localhost:3306 \
        -i ~/.ssh/id_rsa_passwordless@192.168.122.68 sleep 10 ; \
    java -jar schemaspy-6.0.0-rc2.jar -t mysql \
        -db my_mysql_db -u my_mysql_user -p my_mysql_pwd \
        -host 127.0.0.01 -port 10000 -o output \
        -dp drivers/mysql-connector-java-8.0.11.jar
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0-rc2

SchemaSpy generates an HTML representation of a database schema's relationships.

INFO  - Starting Main v6.0.0-rc2 on my_pc with PID 27186 (/home/sampablokuper/schemaspy/schemaspy-6.0.0-rc2.jar started by sampablokuper in /home/sampablokuper/schemaspy)
INFO  - No active profile set, falling back to default profiles: default
INFO  - Configuration file not found
INFO  - Starting schema analysis
INFO  - Using database properties:
INFO  -   [schemaspy-6.0.0-rc2.jar]/org/schemaspy/types/mysql.properties
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
INFO  - Connected to MySQL - 5.6.40
```
&hellip; and from there, SchemaSpy should successfully generate output for the `my_mysql_db` database.

## Current Behavior
```
$ ssh -f -o ExitOnForwardFailure=yes -L 10000:localhost:3306 \
        -i ~/.ssh/id_rsa_passwordless@192.168.122.68 sleep 10 ; \
    java -jar schemaspy-6.0.0-rc2.jar -t mysql \
        -db my_mysql_db -u my_mysql_user -p my_mysql_pwd \
        -host 127.0.0.01 -port 10000 -o output \
        -dp drivers/mysql-connector-java-8.0.11.jar
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0-rc2

SchemaSpy generates an HTML representation of a database schema's relationships.

INFO  - Starting Main v6.0.0-rc2 on my_pc with PID 27186 (/home/sampablokuper/schemaspy/schemaspy-6.0.0-rc2.jar started by sampablokuper in /home/sampablokuper/schemaspy)
INFO  - No active profile set, falling back to default profiles: default
INFO  - Configuration file not found
INFO  - Starting schema analysis
INFO  - Using database properties:
INFO  -   [schemaspy-6.0.0-rc2.jar]/org/schemaspy/types/mysql.properties
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
INFO  - Connected to MySQL - 5.6.40
ERROR - Schema name can't be null
java.lang.IllegalArgumentException: Schema name can't be null
	at org.schemaspy.model.Schema.<init>(Schema.java:36)
	at org.schemaspy.model.Database.<init>(Database.java:78)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:207)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:88)
	at org.schemaspy.Main.runAnalyzer(Main.java:79)
	at org.schemaspy.Main.run(Main.java:72)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at org.schemaspy.Main.main(Main.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
INFO  - Started Main in 2.254 seconds (JVM running for 2.889)
```

Same thing happens if I add  `-noschema` to the command.

An arguably separate bug that is nevertheless probably so closely related to the above that it seems best to mention it here first rather than prematurely opening another bug report, is that if I add `-schema foobarbaz` to the command (where `foobarbaz` is just a made-up string that needn't appear in the database or in the database's configuration), then the command succeeds in generating output for the `my_mysql_db` database.

## Steps to Reproduce (for bugs)
See above, for the closest thing to reproduction steps that I can currently offer.

## Context

* Database type (e.g. MySQL): Oracle MySQL Community Edition 5.6
* Database driver version (if you use a special one): mysql-connector-java-8.0.11.jar
* Your DDL (sample how to reproduce the issue): unsure what is being asked for here.
* Full command including arguments how you run SchemaSpy: see above.

## Your Environment

* Version used: v6.0.0-rc2
* Environment name and version (e.g. Chrome 39): Debian 9 "Stretch"
* Operating System and version (e.g. Windows 10): Debian 9 "Stretch"
* Java version: OpenJDK 1.8.0_171 (see details below).

```
$ java -showversion
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**Comment by npetzall** [comment]
This is a problem since multischema analysis was refactored. To get around the issue on mysql  add `-s [same value as -db]

But either it should be changed to not require -s or -s needs to be added as a required input.

**Comment by npetzall** [comment]
The foobarbaz is probably related to #222.
Doesn't find anything for foobarbaz and adds another schema instead due to mysql jdbc driver actually ignoring schema and expects catalog instead.

**Comment by sampablokuper** [comment]
@npetzall wrote:
> The foobarbaz is probably related to #222.
> Doesn't find anything for foobarbaz and adds another schema instead due to mysql jdbc driver actually ignoring schema and expects catalog instead.

Is it worth filing a separate bug report for this?

Thanks :-)

**Comment by npetzall** [comment]
Do you have more database in the mysql instance or is there just one. I'll check later tonight if I can say for sure if it's similar or duplicate of #222.

If there's just one database in the instance I'm pretty sure it's duplicate.

**Comment by sampablokuper** [comment]
That particular MySQL user only has access to that particular database. However, the MySQL instance does contain other databases (that are accessible to the MySQL `root` user, for instance).

**Comment by npetzall** [comment]
If remember my mysql correctly user needs to have access to the table for the information about the table to show in information_schema.

But that's great information to test how it actually works. If it has access to multiple databases what gets populated might be random. But in this case where user only has access to one database it wouldn't be a gigant leap of faith for it to create a database output for foobarbaz and it would contain my_mysql_db instead. You could check the output if foobarbaz is present in text.

**Comment by sampablokuper** [comment]
Thanks :-)

To avoid cluttering _this_ issue report with additional potentially-unrelated comments, I created #330 to handle the `foobarbaz` stuff mentioned above.

**Comment by npetzall** [comment]
Related to #117

**Comment by npetzall** [comment]
I wrote this in the other issue, but it's more relevant here:

I want -cat, -schema to be used as narrowing/filtering. So that they aren't required unless you want to extract a single catalog or a single schema. So in most cases they won't be used. This would eliminate the -all option that exists. Default is all.
So you're use-case and probably lot's of peoples use-cases are that they want everything. If they want less they can filter by using -cat or -schema these would then be pattern or list of patterns.

Due to the current order of things in schemaspy. I tries to create the schema in object form before it's even talked to the dbms. Which I think is backwards. It should talk to dbms and then create/filter etc with the result and after that create the necessary objects. #204

**Comment by sampablokuper** [comment]
Thanks for this. I agree that the current order sounds backwards, and that narrowing/filtering is probably the right use-case for those options, ultimately. Wishing you good luck and much progress. Thanks again for your work to maintain and improve SchemaSpy :+1:
