### ISSUE TITLE
postgres auth fails

### ISSUE THREAD

**Issue by MstWntd** [schemaspy/schemaspy#34]
Firstly a big thank you for picking up this tool, its easily one of the most useful and underrated open source tools.

Now for my issue, I have a ssh tunnel going from the database to my laptop, this works great and connections are established client side using tools such as heidiSQL. So I am very confused when SchemaSpy gives me an auth error when trying to connect using the same credentials which I know are working in heidiSQL. 

```
{ schemaspy }  » java -jar "C:\tools\schemaspy\schemaspy-6.0.0-beta.3.jar" -dp "C:\tools\schemaspy\drivers\postgres\postgresql-9.2-1004.jdbc41.jar" -t pgsql -db mydb -host 127.0.0.1 -port 1111 -u user -o "C:\tools\schemaspy\output" -p password
Feb 20, 2017 9:19:30 AM org.springframework.context.annotation.AnnotationConfigApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@30dae81: startup date [Mon Feb 20 09:19:30 GMT 2017]; root of context hierarchy
Using database properties:
  [C:\tools\schemaspy\schemaspy-6.0.0-beta.3.jar]/org/schemaspy/types/pgsql.properties

Failed to connect to database URL [jdbc:postgresql://127.0.0.1/crm]

org.postgresql.util.PSQLException: FATAL: password authentication failed for user "crm_user"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:398)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:173)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
        at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
        at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
        at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
        at org.postgresql.Driver.makeConnection(Driver.java:397)
        at org.postgresql.Driver.connect(Driver.java:267)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:66)
        at org.schemaspy.service.SqlService.connect(SqlService.java:65)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:194)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
        at org.schemaspy.Main.main(Main.java:52)
```

Any help is greatly appreciated, I'm on postgres v9.2.20

**Comment by rafalkasa** [comment]
@MstWntd thank you for using new version of SchemaSpy. I suppose that problem can be with -port option instead -host 127.0.0.1 -port 1111 try to use -host 127.0.0.1:1111. Maybe this will help you, anyway I have to see what is wrong with the -port parameter.

**Comment by MstWntd** [comment]
Awesome that worked, however I had one further issue, it took the username as the schema, this was circumvented by supplying the schema name using -s.

The output is really well put together, you have no idea how happy I am!
