### ISSUE TITLE
Timezone errors

### ISSUE THREAD

**Issue by pgorod** [schemaspy/schemaspy#362]
## Current Behavior
This is my initial set up. I installed java and graphviz on my Ubuntu Server 16.04.

I'm sorry this is probably a stupid mistake from me, but I have spent the past 30m Googling for solutions but I am at that point where I am too ignorant (about Java) to Google wisely :-)

I created a `schemaspy.properties` file with these contents:
```
# type of database. Run with -dbhelp for details
schemaspy.t=mysql
# optional path to alternative jdbc drivers.
schemaspy.dp= ./mysql-connector-java-8.0.11.jar
# database properties: host, port number, name user, password
schemaspy.host=localhost
schemaspy.port=3306
schemaspy.db=forums
schemaspy.u=root
schemaspy.p=******
# output dir to save generated files
schemaspy.o=.
# db scheme for which generate diagrams
schemaspy.s=dbo
```

I try running schemaspy for the first time and I get these errors:

```
root@SuiteCRM ~/SchemaSpy $ java -jar schemaspy-6.0.0-rc2.jar
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0-rc2

SchemaSpy generates an HTML representation of a database schema's relationships.

INFO  - Starting Main v6.0.0-rc2 on SuiteCRM with PID 11942 (/root/SchemaSpy/schemaspy-6.0.0-rc2.jar started by root in /root/SchemaSpy)
INFO  - No active profile set, falling back to default profiles: default
INFO  - Found configuration file: schemaspy.properties
INFO  - Starting schema analysis
INFO  - Using database properties:
INFO  -   [schemaspy-6.0.0-rc2.jar]/org/schemaspy/types/mysql.properties
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
Mon Jun 18 12:15:45 WEST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

Failed to connect to database URL [jdbc:mysql://localhost:3306/forums]

java.sql.SQLException: The server time zone value 'WEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:87)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:61)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:71)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:69)
        at org.schemaspy.service.SqlService.connect(SqlService.java:65)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:181)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:88)
        at org.schemaspy.Main.runAnalyzer(Main.java:79)
        at org.schemaspy.Main.run(Main.java:72)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'WEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:59)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:83)
        at com.mysql.cj.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:128)
        at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2201)
        at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2225)
        at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1391)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:993)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:852)
        ... 24 more
WARN  - Connection Failure
org.schemaspy.model.ConnectionFailure: java.sql.SQLException: The server time zone value 'WEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:95)
        at org.schemaspy.service.SqlService.connect(SqlService.java:65)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:181)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:88)
        at org.schemaspy.Main.runAnalyzer(Main.java:79)
        at org.schemaspy.Main.run(Main.java:72)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.sql.SQLException: The server time zone value 'WEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:87)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:61)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:71)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:69)
        ... 20 common frames omitted
Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'WEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:59)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:83)
        at com.mysql.cj.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:128)
        at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2201)
        at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2225)
        at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1391)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:993)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:852)
        ... 24 common frames omitted
INFO  - Started Main in 3.472 seconds (JVM running for 4.407)

```

## Your Environment
* Version used: 6.0.0. RC2
* Operating System and version: Ubuntu Server 16.04 64-bit
* Java version: openjdk version "1.8.0_171"

So, how can I set the timezone for SchemaSpy? Thanks in advance!

**Comment by npetzall** [comment]
I'm not sure if this is a schemaspy issue.

What version of mysql are you connecting to?
And just for fun have you tried with 6.x version of the jdbc driver for mysql.

**Comment by npetzall** [comment]
Unsure of which timezone to set but add `-connprops serverTimezone\\=UTC`

This will add serverTimezone to connection

**Comment by pgorod** [comment]
Cool, that worked!

Well, it worked with UTC. To get it to use `Europe/Lisbon` which is my correct timezone, I had to add another escape slash... but only one, not two like for the `=` sign...

So this worked: `-connprops serverTimezone\\=Europe\/Lisbon`

Thanks for your help. I'm off to contemplate my beautiful database Schema. :-)

**Comment by npetzall** [comment]
@pgorod I just want to know if you had a look at the documentation hosted at read the docs.
I'm afraid that the layout makes it hard to find useful information.

**Comment by pgorod** [comment]
Yes I read the Documentation. I had seen the `connprops` option but I wasn't sure it was what I needed, or how to use it. I guess having more examples would be helpful.

Maybe my error message and my solution can be added to the docs? Do you think other people will run into this problem?

**Comment by npetzall** [comment]
Great feedback, there is a what I now consider a really hidden example

http://schemaspy.readthedocs.io/en/latest/started.html#supply-connection-properties

**Comment by pgorod** [comment]
In case anyone lands on this page when Googling for how to set timezone for SchemaSpy, I have a small tip to add to what is written above. 

If you want to use the `schemaspy.properties` file instead of command line arguments, then you need a line like this:

`schemaspy.connprops="serverTimezone\=Europe/Lisbon"`

Compare with the command-line option version:

`-connprops serverTimezone\\=Europe\/Lisbon`

I find the escaping a bit confusing, since it's weird on the command-line, and is (understandably) different inside the file.

I don't know if this is worth putting into the documentation as an example, maybe it is too specific...

**Comment by npetzall** [comment]
Just to make things really confusing there is a third option. Which is a file that I think is without escaping.

**Comment by npetzall** [comment]
Third way should be something in the lines of

new file `connectionProps.properties` with content
```
serverTimezone=Europe/Lisbon
```
And then either `-connprops connectionProps.properties` or in `schemaspy.properties`
```
schemaspy.connprops=connectionProps.properties
```
