### ISSUE TITLE
Large database causes stackoverflow when usig viz.js

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#462]
## Expected Behavior

No failure 

## Current Behavior

A stackoverflow exception is thrown during one of the generation of realtionship/summary
## Steps to Reproduce (for bugs)

1.large db 800+ tables, 6500+ columns
2.usung viz.js
3.
4.

## Context

* Database type (e.g. MySQL):mssql08
* Database driver version (is you use a special one):6.x
* Your DDL (sample how to reproduce the issue):arts odm
* Full command including arguments how you run SchemaSpy:-vizjs

## Your Environment

* Version used:6.1.0-SNAPSHOT
* Environment name and version (e.g. Chrome 39): FIREFOX
* Operating System and version (e.g. Windows 10): Ubuntu 16.04
* Java version:8u60

**Comment by sgramsch** [comment]
Ran into this issue (6.1.0-SNAPSHOT). Tried to run with more memory (-Xmx12G), but no luck.

```
Gathering schema details..........................................................................................................................................................................(14sec)
Connecting relationships..........................................................................................................................................................................(14sec)
Writing/graphing summary.........(70sec)
Writing/diagramming details[WARNING] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[...]
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate Table diagram
    at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram (DiagramFactory.java:71)
    at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram (MustacheDiagramFactory.java:44)
    at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams (MustacheTableDiagramFactory.java:74)
    at org.schemaspy.SchemaAnalyzer.generateHtmlDoc (SchemaAnalyzer.java:426)
    at org.schemaspy.SchemaAnalyzer.analyze (SchemaAnalyzer.java:260)
    at org.schemaspy.SchemaAnalyzer.analyze (SchemaAnalyzer.java:123)
    at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer (SchemaSpyRunner.java:98)
    at org.schemaspy.cli.SchemaSpyRunner.run (SchemaSpyRunner.java:87)
    at org.schemaspy.Main.main (Main.java:55)
[...]
Caused by: org.schemaspy.output.diagram.DiagramException: javax.script.ScriptException: java.lang.StackOverflowError in <eval> at line number 27 at column number 596797
    at org.schemaspy.output.diagram.vizjs.VizJSDot.generateDiagram (VizJSDot.java:72)
    at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram (DiagramFactory.java:68)
    at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram (MustacheDiagramFactory.java:44)
    at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams (MustacheTableDiagramFactory.java:74)
    at org.schemaspy.SchemaAnalyzer.generateHtmlDoc (SchemaAnalyzer.java:426)
    at org.schemaspy.SchemaAnalyzer.analyze (SchemaAnalyzer.java:260)
    at org.schemaspy.SchemaAnalyzer.analyze (SchemaAnalyzer.java:123)
    at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer (SchemaSpyRunner.java:98)
    at org.schemaspy.cli.SchemaSpyRunner.run (SchemaSpyRunner.java:87)
    at org.schemaspy.Main.main (Main.java:55)
```
Any idea how to workaround this at least?

**Comment by npetzall** [comment]
@sgramsch you need to increase stacksize something I didn't try but it's the option ` -Xss[size]` like `-Xss4096k`

**Comment by sgramsch** [comment]
Thanks, this worked (here with -Xss1536k). Took me a while to get it running, because SchemaSpy is executed via Maven. 
Explicitely using `exec-maven-plugin:exec`, because `exec-maven-plugin:java` kills the Maven process, since SchemaSpy fires a `System.exit()` after it finishes.
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <executions>
        <execution>
            <goals>
                <goal>properties</goal>
            </goals>
        </execution>
    </executions>
</plugin>
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>schemaspy</id>
            <phase>compile</phase>
            <goals>
                <goal>exec</goal>
            </goals>
            <configuration>
                <!-- fix for bug https://github.com/mojohaus/exec-maven-plugin/issues/75 -->
                <longModulepath>false</longModulepath>
                <executable>java</executable>
                <arguments>
                    <argument>-Xss1536k</argument>
                    <argument>-jar</argument>
                    <argument>${org.schemaspy:schemaspy:jar}</argument>
                    <argument>-dp</argument>
                    <argument>${com.oracle.jdbc:ojdbc6:jar}</argument>
                    <argument>-vizjs</argument>
                    <argument>-noads</argument>
                    <argument>-nologo</argument>
                    <argument>-maxdet</argument>
                    <argument>100000</argument>
                    <argument>-t</argument>
                    <argument>orathin</argument>
                    <argument>-host</argument>
                    <argument>${db.host}</argument>
                    <argument>-port</argument>
                    <argument>${db.port}</argument>
                    <argument>-db</argument>
                    <argument>${db.sid}</argument>
                    <argument>-u</argument>
                    <argument>${db.user.name}</argument>
                    <argument>-p</argument>
                    <argument>${db.user.password}</argument>
                    <argument>-s</argument>
                    <argument>${db.user.name}</argument>
                    <argument>-o</argument>
                    <argument>${project.build.directory}/schemadoc</argument>
                    <argument>-cat</argument>
                    <argument>${db.user.name}</argument>
                </arguments>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by stefanthurnherr** [comment]
For the reference, we ran into the same problem, see stacktrace below.

@npetzall Maybe worth adding this to the command-line reference for the ``-vizjs`` argument [here](https://schemaspy.readthedocs.io/en/latest/configuration/commandline.html)?

```java
16:36:14  ..ERROR - RelationShipDiagramError
16:36:14  org.schemaspy.output.OutputException: Failed to produce diagram for: OUTPUTFOLDER/SCHEMANAME/diagrams/summary/relationships.real.compact.dot
16:36:14  	at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateSummaryDiagrams(MustacheSummaryDiagramFactory.java:91)
16:36:14  	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:351)
16:36:14  	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
16:36:14  	at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:176)
16:36:14  	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:118)
16:36:14  	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
16:36:14  	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
16:36:14  	at org.schemaspy.Main.main(Main.java:55)
16:36:14  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:36:14  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:36:14  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:36:14  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
16:36:14  	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
16:36:14  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
16:36:14  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
16:36:14  	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
16:36:14  Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate summary diagram
16:36:14  	at org.schemaspy.output.diagram.DiagramFactory.generateSummaryDiagram(DiagramFactory.java:81)
16:36:14  	at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateSummaryDiagram(MustacheDiagramFactory.java:49)
16:36:14  	at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateSummaryDiagrams(MustacheSummaryDiagramFactory.java:87)
16:36:14  	... 15 common frames omitted
16:36:14  Caused by: org.schemaspy.output.diagram.DiagramException: javax.script.ScriptException: java.lang.StackOverflowError in <eval> at line number 27 at column number 596797
16:36:14  	at org.schemaspy.output.diagram.vizjs.VizJSDot.generateDiagram(VizJSDot.java:72)
16:36:14  	at org.schemaspy.output.diagram.DiagramFactory.generateSummaryDiagram(DiagramFactory.java:78)
16:36:14  	... 17 common frames omitted
16:36:14  ......(1110sec)
```

**Comment by npetzall** [comment]
@stefanthurnherr that there is a problem or the thing about the stacksize?

**Comment by npetzall** [comment]
It was a good reminder, should probably add this as a option for the docker container.

**Comment by stefanthurnherr** [comment]
@npetzall I meant the to add to the -vizjs documentation the thing about setting/increasing the stacksize, especially since it is already mentioned something about default memory settings and possible errors:
> Memory is set to 64 MB, if you receive ther error “Cannot enlarge memory arrays” please report this to us.

**Comment by npetzall** [comment]
This should be re-verified after 6.2.0 since, the script engine has been replaced.
