### ISSUE TITLE
Routines documentation for Postgres 11.1

### ISSUE THREAD

**Issue by chsanch** [schemaspy/schemaspy#470]
## Expected Behavior
To have the output of the functions/procedures in the `Routines` section 

## Current Behavior
Using `schemaspy-6.1.0-SNAPSHOT.jar` the documentation is generated but there is an error when obtaining the functions from the schema:
```
INFO  - Gathering schema details
Gathering schema details........WARN  - Failed to retrieve stored procedure/function details using sql 
'select r.routine_name, case when p.proisagg then 'AGGREGATE' else 'FUNCTION' end as 
routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-
DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as 
routine_body, r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description 
as routine_comment from information_schema.routines r left join pg_namespace ns on 
r.routine_schema = ns.nspname left join pg_proc p on ns.oid = p.pronamespace and r.routine_name 
= p.proname left join pg_description d on d.objoid = p.oid where r.routine_schema = :schema'
```

## Context
* Database type (e.g. MySQL): PostgreSQL - 11.1 (Debian 11.1-1.pgdg90+1) _(Docker Image)_
* Database driver version (is you use a special one): postgresql-42.2.5.jar 
* Full command including arguments how you run SchemaSpy: `java -jar schemaspy-6.1.0-SNAPSHOT.jar -t pgsql -dp postgresql-42.2.5.jar -db postgres -host localhost -port 32770  -s $SCHEMA  -u $USER -p $PASSWORD -renderer :cairo -hq -o db_docs`

## Your Environment
* Version used: 6.1.0-SNAPSHOT
* Operating System and version (e.g. Windows 10): MacOS Mojave 10.14.1
* Java version:
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

**Comment by npetzall** [comment]
@chsanch could you run it again with added cmd arg `-debug` this should print stacktrace that might contain details about the error.

**Comment by chsanch** [comment]
This is the output with the details of the error:

```
DEBUG - select r.routine_name, case when p.proisagg then 'AGGREGATE' else 'FUNCTION' end as routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body, r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on ns.oid = p.pronamespace and r.routine_name = p.proname left join pg_description d on d.objoid = p.oid where r.routine_schema = ? [api]
WARN  - Failed to retrieve stored procedure/function details using sql 'select r.routine_name, case when p.proisagg then 'AGGREGATE' else 'FUNCTION' end as routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body, r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on ns.oid = p.pronamespace and r.routine_name = p.proname left join pg_description d on d.objoid = p.oid where r.routine_schema = :schema'
org.postgresql.util.PSQLException: ERROR: column p.proisagg does not exist
  Hint: Perhaps you meant to reference the column "p.prolang".
  Position: 34
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at org.schemaspy.service.DatabaseService.initRoutines(DatabaseService.java:738)
	at org.schemaspy.service.DatabaseService.gatheringSchemaDetails(DatabaseService.java:100)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:242)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:119)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
	at org.schemaspy.Main.main(Main.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```
It seems a problem with a wrong column name, maybe something change in this version of Postgres?

**Comment by npetzall** [comment]
It was for 9.4, in 11 the column has been removed. But there is a prokind that can be used with a case statement.

> f for a normal function, p for a procedure, a for an aggregate function, or w for a window function

**Comment by npetzall** [comment]
Create a new file in same dir as schemaspy.jar call it `pgsql11.properties`

Add following content
```
extends=pgsql
selectRoutinesSql=select r.routine_name, case p.prokind when 'f' then 'FUNCTION' when 'p' then 'PROCEDURE' when 'a' then 'AGGREGATE' when 'w' then 'WINDOW' else 'UNKNOWN' end as routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body, r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on ns.oid = p.pronamespace and r.routine_name = p.proname left join pg_description d on d.objoid = p.oid where r.routine_schema = :schema
selectRoutineParametersSql=select r.routine_name as specific_name, coalesce(p.parameter_name, '$' || p.ordinal_position) as parameter_name, p.data_type as dtd_identifier, p.parameter_mode from information_schema.parameters p left join information_schema.routines r on r.specific_name = p.specific_name where p.specific_schema = :schema order by p.specific_name, p.ordinal_position
```

Now start schemaspy with `-t pgsql11`instead of `-t pgsql``

I'll continue to update this comment since I don't have access to my normal computer yet. So I've only fixed the first `p.proisagg` since I don't have any possbility to test at the moment.

You can find expected returned columns https://schemaspy.readthedocs.io/en/latest/configuration/databaseType.html#other-properties
```
selectRoutinesSql=
routine_name, routine_type, dtd_identifier, routine_body, routine_definition,sql_data_access, security_type, is_deterministic, routine_comment
selectRoutineParametersSql=
specific_name, parameter_name, dtd_identifier, parameter_mode
```

**Comment by npetzall** [comment]
If you verify that the SQL is working and getting the correct results or if you modify it to get it working please let me know and I can include it or you can make a PR to include it.

**Comment by chsanch** [comment]
Hi, it works perfect. 
Please include it for the next release. 

Thanks!
