### ISSUE TITLE
something wrong with SSO here

### ISSUE THREAD

**Issue by sunilsql** [schemaspy/schemaspy#501]
E:\>java -Djava.library.path="E:\jtds-1.2-dist\SSO\ntlmauth.dll" -jar schemaspy-6.0.0.jar -sso -t mssql08-jtds -host DESKTOP-SM37531 -port 1433 -db AdventureWorks2016CTP3 -all -o E:\all -gv "C:\Program Files (x86)\Graphviz2.38" -debug
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on DESKTOP-SM37531 with PID 15724 (E:\schemaspy-6.0.0.jar started by sunil in E:\)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.566 seconds (JVM running for 2.105)
DEBUG - Debug enabled
INFO  - Configuration file not found
DEBUG - Resolving dbType: mssql08-jtds ->
        /E:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql08-jtds.properties ->
        /E:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql05-jtds.properties ->
        /E:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql-jtds.properties ->
        /E:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'DESKTOP-SM37531:1433' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'AdventureWorks2016CTP3' description: 'database name  '
WARN  - Connection Failure
org.schemaspy.model.ConnectionFailure: Failed to connect to database URL [jdbc:jtds:sqlserver://DESKTOP-SM37531:1433/AdventureWorks2016CTP3] I/O Error: SSO Failed: Native SSPI library not loaded. Check the java.library.path system property.
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:101)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:75)
        at org.schemaspy.SchemaAnalyzer.getConnection(SchemaAnalyzer.java:421)
        at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:121)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:102)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
        at org.schemaspy.Main.main(Main.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.sql.SQLException: I/O Error: SSO Failed: Native SSPI library not loaded. Check the java.library.path system property.
        at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.java:611)
        at net.sourceforge.jtds.jdbc.ConnectionJDBC2.<init>(ConnectionJDBC2.java:331)
        at net.sourceforge.jtds.jdbc.ConnectionJDBC3.<init>(ConnectionJDBC3.java:50)
        at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:178)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:94)
        ... 15 common frames omitted
Caused by: java.io.IOException: SSO Failed: Native SSPI library not loaded. Check the java.library.path system property.
        at net.sourceforge.jtds.jdbc.TdsCore.sendMSLoginPkt(TdsCore.java:1894)
        at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.java:584)
        ... 19 common frames omitted

**Comment by npetzall** [comment]
Could you try `java -Djava.library.path="E:\jtds-1.2-dist\SSO" -jar schemaspy-6.0.0.jar -sso -t mssql08-jtds -host DESKTOP-SM37531 -port 1433 -db AdventureWorks2016CTP3 -all -o E:\all -gv "C:\Program Files (x86)\Graphviz2.38" -debug`

Might be totally off but I have a faint recollection from working with javaPOS that it wants a folder and not the file. If this works I'm gonna update the docs.

If possible try with a trailing `\` in the java.library.path

**Comment by sunilsql** [comment]
Nothing has been changed, still looking same

**Comment by npetzall** [comment]
To bad because the problem is with jvm, jtds and possibly windows.

I'm gonna have Google on library path and windows.

**Comment by npetzall** [comment]
Googling just says path to folder/dir containing the library in your case the dll.

**Comment by npetzall** [comment]
I'm setting up a windows box to test this. So we can get proper documentation.
