### ISSUE TITLE
Trying to use on Linux

### ISSUE THREAD

**Issue by travis5491811** [schemaspy/schemaspy#503]
Trying to use this on Ubuntu 18 machine to connect to SQL Server 2005 DB on another machine on the network. I already have other tools (nodejs apps, MySQL Workbench, DBBeaver, etc) connecting to that same database. I can't figure out how to use schemaspy to connect.

Looking through the docs for `.dp` and did not find any documentation about where to get drivers. `-dbhelp` provided a hint about `.t` so i tried `mssql05` but suspect anything could be wrong because the output is just `Connection Failure`.

I'm using a schemaspy.properties file and running with `java -jar schemaspy-6.0.0.jar`. Here is my output

```
$ java -jar schemaspy-6.0.0.jar
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on jtlgz with PID 15781 (/home/travis/Downloads/SchemaSpy/schemaspy-6.0.0.jar started by travis in /home/travis/Downloads/SchemaSpy)
INFO  - The following profiles are active: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/home/travis/Downloads/SchemaSpy/schemaspy-6.0.0.jar!/BOOT-INF/lib/spring-core-4.3.13.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  - Found configuration file: schemaspy.properties
INFO  - Started Main in 0.932 seconds (JVM running for 1.332)
INFO  - Starting schema analysis
WARN  - Connection Failure
```

Config file
```
# type of database. Run with -dbhelp for details
schemaspy.t=mssql05
# optional path to alternative jdbc drivers.
#schemaspy.dp=path/to/drivers
# database properties: host, port number, name user, password
schemaspy.host=ip
schemaspy.port=1433
schemaspy.db=databasename
#instance for sql server 2005
schemaspy.instance=INSTANCENAME
schemaspy.u=sa
schemaspy.p=passwowrd
# output dir to save generated files
schemaspy.o=/the/output/dir
# db scheme for which generate diagrams
schemaspy.s=dbo
```

More local machine info
```
$ java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
```

## Expected Behavior

I expect it to run so that i can experiment to see how helpful this will be with documenting databases.

## Current Behavior

Error posted above.

## Possible Solution

None.

## Steps to Reproduce (for bugs)

1. Download latest schemaspy on Linux machine
2. Try to use.

## Context

* Database type (e.g. MySQL): SQL Server 2005
* Database driver version (is you use a special one): Not sure how to identify or define.
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy: `java -jar schemaspy-6.0.0.jar`

Config file
```
# type of database. Run with -dbhelp for details
schemaspy.t=mssql05
# optional path to alternative jdbc drivers.
#schemaspy.dp=path/to/drivers
# database properties: host, port number, name user, password
schemaspy.host=ip
schemaspy.port=1433
schemaspy.db=databasename
#instance for sql server 2005
schemaspy.instance=INSTANCENAME
schemaspy.u=sa
schemaspy.p=passwowrd
# output dir to save generated files
schemaspy.o=/the/output/dir
# db scheme for which generate diagrams
schemaspy.s=dbo
```

## Your Environment

* Version used: 6.0.0
* Environment name and version (e.g. Chrome 39): Didn't make it to the browser yet.
* Operating System and version (e.g. Windows 10): Mint 19 with Ubuntu 18.04 LTS
* Java version: 10.0.2

**Comment by npetzall** [comment]
Hi

You can add `-debug` to get debug output. PrintStack trace and it will probably help me pinpoint the problem.

I would advice you to use schemaspy-6.1.0-SNAPSHOT since we have done fixes since 6.0.0 was released. https://github.com/schemaspy/schemaspy#latest-build

You'll need to provide the jdbc-driver using `-dp` argument, no drivers are included due to licensing.

Also there are a cpl of different database configuration for SQL Server:
Since you are using 2005.
There are `mssql05`, `mssql05-jtds`, `mssql05-jtds-instance` where both with jtds requires the jtds driver found on sourceforge.

I'll admit that I'm not sure on how to specify instance for the microsoft driver, but I'm gonna assume it's a connection property which can be added like -> https://schemaspy.readthedocs.io/en/latest/advanced_usage.html#supply-connection-properties

**Comment by travis5491811** [comment]
@npetzall Thanks for the info. I'm troubleshooting the following on one of the drivers (4.1) now. Going to try other drivers from the list.

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:2758)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:2244)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:43)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:2230)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1717)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1328)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:993)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:829)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1012)
	at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:94)
	at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:75)
	at org.schemaspy.service.SqlService.connect(SqlService.java:68)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:186)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:107)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
	at org.schemaspy.Main.main(Main.java:48)
	... 8 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 26 more
```

**Comment by travis5491811** [comment]
Thank you @npetzall 
I downloaded driver from the MS website you posted. Driver 7.0 worked, no errors.

Updated config file
```
# type of database. Run with -dbhelp for details
schemaspy.t=mssql05
# optional path to alternative jdbc drivers.
schemaspy.dp=/home/testuser/Downloads/SchemaSpy/Drivers/7.0/sqljdbc_7.0/enu/
# database properties: host, port number, name user, password
schemaspy.host=ip
schemaspy.port=1433
schemaspy.db=databasename
#instance for sql server 2005
schemaspy.instance=INSTANCENAME
schemaspy.u=sa
schemaspy.p=passwowrd
# output dir to save generated files
schemaspy.o=/the/output/dir
# db scheme for which generate diagrams
schemaspy.s=dbo
```
