### ISSUE TITLE
ERROR - Column information from DatabaseMetaData differs from ResultSetMetaData

### ISSUE THREAD

**Issue by loeiten** [schemaspy/schemaspy#516]
I'm working on a database which I have only read access to, and I'm wondering if there is any way to get around the encountered error:

```
ERROR - Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: Meta_StartTime
```

Any help is appreciated :)

## Expected Behavior

I guess the error is expected as the database is setup as it is, however, I look for a solution in order for the output to be something like

```
...
INFO  - Writing/diagramming details
....................(0sec)
Wrote relationship details of x tables/views to directory 'C:\***\output' in 20 seconds.
View the results by opening C:\***\output\index.html
INFO  - Wrote table details in 0 seconds
INFO  - Wrote relationship details of 20 tables/views to directory 'C:\***\output' in 20 seconds.
INFO  - View the results by opening C:\***\output\index.html
```

## Current Behavior

```
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on CPX-RFKMIAQVS50 with PID 17832 (C:\***\schemaspy.jar started by *** in C:\***\schemaspy)
INFO  - The following profiles are active: default
INFO  - Started Main in 2.528 seconds (JVM running for 3.44)
DEBUG - Debug enabled
INFO  - Configuration file not found
INFO  - Starting schema analysis
DEBUG - Resolving dbType: mssql08 ->
        /C:/***/schemaspy.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql08.properties ->
        /C:/***/schemaspy.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql05.properties ->
        /C:/***/schemaspy.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: '***' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'THE_DATABASE' description: 'database name'
DEBUG - supportsSchemasInTableDefinitions: true
DEBUG - supportsCatalogsInTableDefinitions: true
DEBUG - Catalog not provided, queried jdbc driver and got 'THE_DATABASE'
INFO  - Connected to Microsoft SQL Server - 11.00.7001
INFO  - Gathering schema details
Gathering schema details...DEBUG - Including table A_TABLE: matches inclusion pattern '.*'
DEBUG - Creating Table THE_DATABASE.dbo.A_TABLE
ERROR - Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: Meta_StartTime
org.schemaspy.service.InconsistencyException: Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: Meta_Sta
rtTime
        at org.schemaspy.service.TableService.initColumnAutoUpdate(TableService.java:120)
        at org.schemaspy.service.TableService.initColumns(TableService.java:87)
        at org.schemaspy.service.TableService.gatheringTableDetails(TableService.java:65)
        at org.schemaspy.service.DatabaseService$TableCreator.createImpl(DatabaseService.java:311)
        at org.schemaspy.service.DatabaseService$TableCreator.create(DatabaseService.java:306)
        at org.schemaspy.service.DatabaseService.initTables(DatabaseService.java:172)
        at org.schemaspy.service.DatabaseService.gatheringSchemaDetails(DatabaseService.java:75)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:212)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:107)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
        at org.schemaspy.Main.main(Main.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

## Possible Solution

I have no suggestions

## Steps to Reproduce (for bugs)

I'm a bit unsure how to reproduce this bug as my experience with databases is limited, however, it looks like one of the java objects from the columns [is null](https://github.com/schemaspy/schemaspy/blob/35aba283d20ba3d4c0c435152cc85431f982ea18/src/main/java/org/schemaspy/service/TableService.java#L120). It could be that it is somehow related to [this PR](https://github.com/schemaspy/schemaspy/pull/174#issuecomment-352146783)

## Context

* Database type (e.g. MySQL):
Microsoft SQL Server - 11.00.7001
* Database driver version (is you use a special one):
`mssql-jdbc-7.2.1.jre8.jar`
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

```
java -jar schemaspy.jar -t mssql08 -dp C:/path/to/mssql-jdbc-7.2.1.jre8.jar -db THE_DB -host THE_IP -port 1433 -s THE_SCHEMA -u THE_USERNAME -p THE_PASSWORD -o C:/path/to/output -gv C:/path/to/graphviz/ -debug
```

## Your Environment

* Version used:
6.0.0
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10):
Windows 10
* Java version: 
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
```

**Comment by npetzall** [comment]
Would it be possible to provide additional information about the table and the column so that I can try to recreate the issue.

I wonder if I added the exception we could make it so that it's a warning and notify that a column has been excluded. But need to figure out why.

**Comment by loeiten** [comment]
Thank you for the fast reply :).

Sure, what kind of information about the table and column would be of interest?

The `INFORMATION_SCHEMA.TABLES` returns 

```
| TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME |
|---------------|:------------:|-----------:|
| THE_DATABASE  |      dbo     |    A_TABLE |
````

whereas `INFORMATION_SCHEMA.COLUMNS` returns

```
| TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME | COLUMN_NAME    | ORDINAL_POSITION | COLUMN_DEFAULT | IS_NULLABLE | DATA_TYPE | CHARACTER_MAXIMUM_LENGTH | CHARACTER_OCTET_LENGTH | NUMERIC_PRECISION | NUMERIC_PRECISION_RADIX | NUMERIC_SCALE | DATETIME_PRECISION | CHARACTER_SET_CATALOG | CHARACTER_SET_SCHEMA | CHARACTER_SET_NAME | COLLATION_CATALOG | COLLATION_SCHEMA | COLLATION_NAME | DOMAIN_CATALOG | DOMAIN_SCHEMA | DOMAIN_NAME |
|---------------|--------------|------------|----------------|------------------|----------------|-------------|-----------|--------------------------|------------------------|-------------------|-------------------------|---------------|--------------------|-----------------------|----------------------|--------------------|-------------------|------------------|----------------|----------------|---------------|-------------|
| THE_DATABASE  | dbo          | A_TABLE    | Meta_StartTime | 6                | NULL           | YES         | datetime  | NULL                     | NULL                   | NULL              | NULL                    | NULL          | 3                  | NULL                  | NULL                 | NULL               | NULL              | NULL             | NULL           | THE_DATABASE   | NULL          | NULL        |
```

The first row in this table has a `NULL` value in the `Meta_StartTime` column. Could that be the problem?

**Comment by npetzall** [comment]
The value of the column in a single row doesnt cause this issue.

The problem is that we query the JDBC driver for all columns in a table.
So we add them to a map.
Later we try to figure out if any of the columns are auto_incrementing.
So we do a query `select * from [TABLE] where 0=1` this is to get a ResultSet which we can query metadata from.

So when asking for columns in table we don't seem to get Meta_StartTime as a column.
When we ask metadata about the result of select * we receive the Meta_StartTime as a column.

So we have an inconsistency in the number and names of columns between DatabaseMetaData and ResultSetMetaData, where ResultSetMetaData seems to include an additional column.

I'm gonna do a quick test to see if it has anything to do with the name or if it has anything to do with the jdbc driver version.

**Comment by npetzall** [comment]
I'm on linux so can only test with 2017 or version 14 of SQLServer.

I've checked with the name it's working both in 6.0.0 and 6.1.0-SNAPSHOT. I'm guessing you're obfuscating some of the information or are you able to recreate the issue with Database called THE_DATABASE, table called A_TABLE and in the dbo schema?

I'm suspecting this since the information and the commandline won't work in combination.

As for the referenced PR the changes have been changed again more or less reverting the PR.

You could test the SNAPSHOT version https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.1.0-SNAPSHOT.jar

If that still fails. I can add some additional debug logging and I'll let you know when you can download a new version.

**Comment by loeiten** [comment]
Thank you for your kind help :).

I see that there are other tables in the same database with `Meta_StartTime` where SchemaSpy is able to process through without any trouble. Also there are columns in other tables within the same database where SchemaSpy get the same hickup for different columns (for example one named `PK_FACT_something`). This hints that the name is not the problem, but maybe something else_

**Comment by loeiten** [comment]
So, I ran the same command with the snapshot of 6.1:

```
java -jar schemaspy61.jar -t mssql08 -dp C:/***/mssql-jdbc-7.2.1.jre8.jar -db THE_DATABASE -host THE_IP -port 1433 -s dbo -u user -p password -o C:/***/dbo -gv C:/***/graphviz/ -debug
```

And got the result

```
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.1.0-SNAPSHOT

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0-SNAPSHOT on CPX-RFKMIAQVS50 with PID 14860 (C:\***\schemaspy61\schemaspy61.jar started by SOMEONE in C:\***\schemaspy61)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.515 seconds (JVM running for 2.245)
DEBUG - Debug enabled
INFO  - Configuration file not found
INFO  - Starting schema analysis
DEBUG - Resolving dbType: mssql08 ->
        /C:/***/schemaspy61/schemaspy61.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql08.properties ->
        /C:/***/schemaspy61/schemaspy61.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql05.properties ->
        /C:/***/schemaspy61/schemaspy61.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'THE_IP:1433' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'THE_DATABASE' description: 'database name'
DEBUG - supportsSchemasInTableDefinitions: true
DEBUG - supportsCatalogsInTableDefinitions: true
DEBUG - Catalog not provided, queried jdbc driver and got 'THE_DATABASE'
INFO  - Connected to Microsoft SQL Server - 11.00.7001
INFO  - Gathering schema details
Gathering schema details...DEBUG - Including table A_TABLE: matches inclusion pattern '.*'
DEBUG - Creating Table THE_DATABASE.dbo.A_TABLE
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.service.InconsistencyException: Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: Meta_StartTime
        at org.schemaspy.service.TableService.initColumnAutoUpdate(TableService.java:120)
        at org.schemaspy.service.TableService.initColumns(TableService.java:87)
        at org.schemaspy.service.TableService.gatheringTableDetails(TableService.java:65)
        at org.schemaspy.service.DatabaseService$TableCreator.createImpl(DatabaseService.java:342)
        at org.schemaspy.service.DatabaseService$TableCreator.create(DatabaseService.java:337)
        at org.schemaspy.service.DatabaseService.initTables(DatabaseService.java:183)
        at org.schemaspy.service.DatabaseService.gatheringSchemaDetails(DatabaseService.java:85)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:242)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:119)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
```

i.e. the error persists.

If you add some additional debug flags, I'll gladly run the command again.
Also, please let me know if there are any queries you'd like me to run to help you track down the bug :).

**Comment by npetzall** [comment]
Sorry for the delay, family stuff. I've updated the snapshot so download it again.

The should now be something like:
"Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named 'Meta_StartTime' in ['.,.,.,.']"
Where the dots should be a list of tables that have been returned by DatabaseMetaData. 

I'll look over the ms jdbc to see how it does the look up and I might provide a query for you to run.

**Comment by loeiten** [comment]
Hi again.
No worries, have been busy myself.
I ran the new command with the result

```
Caused by: org.schemaspy.service.InconsistencyException: Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: 'Meta_StartTime' in ['']
```

Not sure if that is helpful (as it shows an empty list).
The full trace:

```
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.1.0-SNAPSHOT

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0-SNAPSHOT on CPX-RFKMIAQVS50 with PID 10124 (C:\***\schemaspy61\schemaspy-6.1.0-SNAPSHOT.jar started by THE_USER in C:\***\schemaspy61)
INFO  - The following profiles are active: default
INFO  - Started Main in 2.45 seconds (JVM running for 3.468)
DEBUG - Debug enabled
INFO  - Configuration file not found
INFO  - Starting schema analysis
DEBUG - Resolving dbType: mssql08 ->
        /C:/***/schemaspy61/schemaspy-6.1.0-SNAPSHOT.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql08.properties ->
        /C:/***/schemaspy61/schemaspy-6.1.0-SNAPSHOT.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql05.properties ->
        /C:/***/schemaspy61/schemaspy-6.1.0-SNAPSHOT.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'THE_IP:1433' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'THE_DATABASE' description: 'database name'
DEBUG - supportsSchemasInTableDefinitions: true
DEBUG - supportsCatalogsInTableDefinitions: true
DEBUG - Catalog not provided, queried jdbc driver and got 'THE_DATABASE'
INFO  - Connected to Microsoft SQL Server - 11.00.7001
INFO  - Gathering schema details
Gathering schema details...DEBUG - Including table THE_TABLE: matches inclusion pattern '.*'
DEBUG - Creating Table THE_DATABASE.dbo.THE_TABLE
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.service.InconsistencyException: Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: 'Meta_StartTime' in ['']
        at org.schemaspy.service.TableService.initColumnAutoUpdate(TableService.java:121)
        at org.schemaspy.service.TableService.initColumns(TableService.java:88)
        at org.schemaspy.service.TableService.gatheringTableDetails(TableService.java:66)
        at org.schemaspy.service.DatabaseService$TableCreator.createImpl(DatabaseService.java:342)
        at org.schemaspy.service.DatabaseService$TableCreator.create(DatabaseService.java:337)
        at org.schemaspy.service.DatabaseService.initTables(DatabaseService.java:183)
        at org.schemaspy.service.DatabaseService.gatheringSchemaDetails(DatabaseService.java:85)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:242)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:119)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
```

**Comment by npetzall** [comment]
I'm gonna dubble check my logging, just to verify that it's working.

If it's working there seems to be an issue with
```
try (ResultSet rs = sqlService.getDatabaseMetaData().getColumns(table.getCatalog(), table.getSchema(), table.getName(), "%")) {
```

I checked the driver code earlier and it executes a stored procedure called sp_columns.
Google returned https://stackoverflow.com/questions/14966329/why-does-sp-columns-return-no-results

But i feel that if sp_columns should return nothing if not connected to the correct that database/catalog. sp_tables shouldnt work either.

But according to source code:
`sp_tables [ [ @table_name = ] 'name' ] [ , [ @table_owner = ] 'owner' ] [ , [ @table_qualifier = ]'qualifier' ] [ , [ @table_type = ] "type" ]`
`sp_columns [ @table_name = ] object [ , [ @table_owner = ] owner ] [ , [ @table_qualifier = ] qualifier ][ , [ @column_name = ] column ] [ , [ @ODBCVer = ] ODBCVer ]`

I'll update more when kid isn't wrestling me for the laptop

**Comment by loeiten** [comment]
Hi again

So, not sure I understood your message, but

```
sp_tables @table_name='%', @table_owner='dbo'
```

successfully returned all the tables, and

```
sp_columns @table_name='A_TABLE', @table_owner='dbo', @column_name='%'
```

successfully returned all the columns in `A_TABLE`.
However

```
sp_columns @table_name='[A_TABLE]', @table_owner='dbo', @column_name='%'
```

returned an empty table. Could that be the problem?

**Comment by npetzall** [comment]
Seem that `[ ] \ % _` are escaped by the driver. I double checked and the logging is working.
So it seems that the sp_columns failes.

Are there any characters except a-zA-Z in the table name?

**Comment by loeiten** [comment]
Hmm...strange.

So the table name contains a couple of underscore (`_`) characters, apart from that just `[a-zA-Z]`. The column names in the table contains `[a-zA-Z]` and `_` as well.

However, non-ASCII characters exists in column names in other tables.

**Comment by npetzall** [comment]
Sorry that this has become old. I think I have some spare time now. So if possible could you provide the tablename with [a-zA-Z] replaced with just `a`s so that I can get the pattern for the none [a-zA-Z] characters and which they are.

I'm setting up a SQL Server 2012 Express hoping that it will reproduce the issue.

**Comment by s-nt-s** [comment]
I am having the same problem with a sqlite database with [generated columns](https://www.sqlite.org/gencol.html)

**Comment by patschwork** [comment]
Are there any news regarding this? 

I'm on MSSQL and also face this problem. 

I already tried to "overrule" this, with the custom SQL (selectTablesSql). But I can't find to overrule Columns... The metadata from the SQL Server is alright


----- 

Maybe helpful:
```
Using drivers:mssql-jdbc-12.8.1.jre8.jar
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              7.0.2
```
...with Docker
