### ISSUE TITLE
SQLite connection failure (worked fine in SchemaSpy5.0.0)

### ISSUE THREAD

**Issue by asarmy** [schemaspy/schemaspy#524]
I was able to connect to my database and run SchemaSpy fine in the 5.0.0 version. Now I am getting `WARN  - Connection Failure` in 6.0.0.

**This is the `sqlite.properties` file content:**
```
description=SQLite
connectionSpec=jdbc:sqlite:<db>
db=students.db
driver=org.sqlite.JDBC
driverPath=sqlite-jdbc-3.23.1.jar
selectTablesSql=.tables
```

**This is the entry in command prompt:**
`java -jar schemaspy-6.0.0.jar -t sqlite -db students.db -sso -dp C:\Users\name\Desktop\schemaspy3\schemaspy-6.0.0.jar -o C:\Users\name\Desktop\schemaspy3`

**This is the output:**
```
INFO  - Starting Main v6.0.0 on DESKTOP-E0JS54C with PID 21508 (C:\Users\name\Desktop\schemaspy3\schemaspy-6.0.0.jar started by name in C:\Users\name\Desktop\schemaspy3)
INFO  - The following profiles are active: default
INFO  - Started Main in 3.0 seconds (JVM running for 3.942)
INFO  - Configuration file not found
INFO  - Starting schema analysis
WARN  - Connection Failure
```

Both `schemaspy-6.0.0.jar` and `sqlite-jdbc-3.23.1.jar` are in the same folder (`C:\Users\name\Desktop\schemaspy3`)

**Comment by npetzall** [comment]
The output for failures has been improved a bit in 6.1.0-SNAPSHOT.

Could you rum again adding argument `-debug` to commandline?

**Comment by asarmy** [comment]
**Input:**
`java -jar schemaspy-6.0.0.jar -t sqlite -db students.db -sso -dp C:\Users\name\Desktop\schemaspy3\schemaspy-6.0.0.jar -o C:\Users\name\Desktop\schemaspy3 -debug`

**Output:**
```
INFO  - Starting Main v6.0.0 on DESKTOP-E0JS54C with PID 23756 (C:\Users\name\Desktop\schemaspy3\schemaspy-6.0.0.jar started by name in C:\Users\name\Desktop\schemaspy3)
INFO  - The following profiles are active: default
INFO  - Started Main in 3.483 seconds (JVM running for 4.435)
DEBUG - Debug enabled
INFO  - Configuration file not found
INFO  - Starting schema analysis
DEBUG - Resolving dbType: sqlite ->
        /C:/Users/name/Desktop/schemaspy3/sqlite.properties
DEBUG - DbSpecificOption name: 'db' value: 'students.db' description: 'students.db'
DEBUG - Unable to find driverClass 'org.sqlite.JDBC'
WARN  - Connection Failure
org.schemaspy.model.ConnectionFailure: Failed to connect to database URL [jdbc:sqlite:students.db] Failed to create any of 'org.sqlite.JDBC' driver from driverPath 'C:\Users\name\Desktop\schemaspy3\schemaspy-6.0.0.jar' with sibling jars no.
Resulting in classpath:
        file:/C:/Users/name/Desktop/schemaspy3/schemaspy-6.0.0.jar

        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:101)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:75)
        at org.schemaspy.service.SqlService.connect(SqlService.java:68)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:186)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:107)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
        at org.schemaspy.Main.main(Main.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.model.ConnectionFailure: Failed to create any of 'org.sqlite.JDBC' driver from driverPath 'C:\Users\name\Desktop\schemaspy3\schemaspy-6.0.0.jar' with sibling jars no.
Resulting in classpath:
        file:/C:/Users/name/Desktop/schemaspy3/schemaspy-6.0.0.jar

        at org.schemaspy.DbDriverLoader.getDriver(DbDriverLoader.java:147)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:93)
        ... 15 common frames omitted
```

**Comment by npetzall** [comment]
`java -jar schemaspy-6.0.0.jar -t sqlite -db students.db -sso -dp C:\Users\name\Desktop\schemaspy3\ -o C:\Users\name\Desktop\schemaspy3`

Should work unless you need to escape paths due to Windows.

**Comment by asarmy** [comment]
Using the above input (added `-debug`) yields:
```
INFO  - Starting Main v6.0.0 on DESKTOP-E0JS54C with PID 15804 (C:\Users\name\Desktop\schemaspy3\schemaspy-6.0.0.jar started by name in C:\Users\name\Desktop\schemaspy3)
INFO  - The following profiles are active: default
INFO  - Started Main in 2.897 seconds (JVM running for 3.852)
DEBUG - Debug enabled
INFO  - Configuration file not found
INFO  - Starting schema analysis
DEBUG - Resolving dbType: sqlite ->
        /C:/Users/name/Desktop/schemaspy3/sqlite.properties
DEBUG - DbSpecificOption name: 'db' value: 'students.db' description: 'students.db'
DEBUG - supportsSchemasInTableDefinitions: false
DEBUG - supportsCatalogsInTableDefinitions: false
DEBUG - Catalog not provided, queried jdbc driver and got 'null'
DEBUG - Command line parameters: [-t, sqlite, -db, students.db, -sso, -dp, C:\Users\name\Desktop\schemaspy3\, -o, C:\Users\name\Desktop\schemaspy3, -debug]
ERROR - Bad config: Catalog (-cat) was not provided and unable to deduce catalog, wildcard catalog can be used -cat %
org.schemaspy.model.InvalidConfigurationException: Catalog (-cat) was not provided and unable to deduce catalog, wildcard catalog can be used -cat %
        at org.schemaspy.db.CatalogResolver.resolveCatalog(CatalogResolver.java:51)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:193)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:107)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
        at org.schemaspy.Main.main(Main.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by npetzall** [comment]
@asarmy There was a change way back. That modified how the multi schema function worked. Which introduced a catalog and schema in a weird way. I've ranted about this earlier.

I did a quick check and it seems sqlite doesn't have the concept of catalog and schema. I might be wrong. But might work with `-cat students -s students`

**Comment by asarmy** [comment]
Tried `-cat students -s students`, same errors. I had no issues running this same SQLite database through SchemaSpy 5.0.0.

I only get the `cat` error when this is my input:
`java -jar schemaspy-6.0.0.jar -t sqlite -db students.db -sso -dp C:\Users\name\Desktop\schemaspy3\ -o C:\Users\name\Desktop\schemaspy3`

And I get a `WARN  - Connection Failure` error with this as input:
`java -jar schemaspy-6.0.0.jar -t sqlite -db students.db -sso -dp C:\Users\name\Desktop\schemaspy3\schemaspy-6.0.0.jar -o C:\Users\name\Desktop\schemaspy3`

Also tried with `schemaspy-6.1.0-SNAPSHOT.jar`; no difference

**Comment by npetzall** [comment]
@asarmy 
`WARN  - Connection Failure ` is due to malformed `-dp` argument, your adding schemaspy as a driver but it should be sqlit driver. `-dp` will however add all jars found in a folder/dir so just removing `schemaspy-6.0.0.jar` from `-dp` solves that issue.

Then you get a new error (so two separate issues). First fix must still be applied.
`ERROR - Bad config: Catalog (-cat) was not provided` due to early changes in schemaspy and how it does multi-schema analysis it made catalog and schema required parameters. But since sqlite doesn't seem to have these concepts it might be possible to use `-cat students -s students`

So the complete command-line with all  possible fixes.
`java -jar schemaspy-6.0.0.jar -t sqlite -db students.db -sso -dp C:\Users\name\Desktop\schemaspy3\ -o C:\Users\name\Desktop\schemaspy3 -cat students -s students`

**Comment by asarmy** [comment]
Still not working, but thank you for your help. Last question is, why did it work fine in SchemaSpy 5.0.0? I thought the multischema changes were back in version 4? Thanks again for your help

**Comment by npetzall** [comment]
What error do you get now?

Im gonna setup a test with sqlite to see if I can't get it working.

Well there is the one that your refering to which is way way back. There are changes done in early in the life of 6.0.0 also.

**Comment by asarmy** [comment]
**Input:**
`java -jar schemaspy-6.0.0.jar -t sqlite -db students.db -sso -dp C:\Users\name\Desktop\schemaspy3\ -o C:\Users\name\Desktop\schemaspy3 -cat students -s students -debug`
**Output:**
```
INFO  - Starting Main v6.0.0 on DESKTOP-E0JS54C with PID 24568 (C:\Users\name\Desktop\schemaspy3\schemaspy-6.0.0.jar started by name in C:\Users\name\Desktop\schemaspy3)
INFO  - The following profiles are active: default
INFO  - Started Main in 2.945 seconds (JVM running for 4.127)
DEBUG - Debug enabled
INFO  - Configuration file not found
INFO  - Starting schema analysis
DEBUG - Resolving dbType: sqlite ->
        /C:/Users/name/Desktop/schemaspy3/sqlite.properties
DEBUG - DbSpecificOption name: 'db' value: 'students.db' description: 'students.db'
DEBUG - supportsSchemasInTableDefinitions: false
DEBUG - supportsCatalogsInTableDefinitions: false
INFO  - Connected to SQLite - 3.23.1
INFO  - Gathering schema details
Gathering schema details...DEBUG - .tables []
WARN  - Failed to retrieve 'table' names with custom SQL '.tables
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near ".": syntax error)
        at org.sqlite.core.DB.newSQLException(DB.java:909)
        at org.sqlite.core.DB.newSQLException(DB.java:921)
        at org.sqlite.core.DB.throwex(DB.java:886)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
        at org.sqlite.core.DB.prepare(DB.java:227)
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:235)
        at org.schemaspy.service.SqlService.prepareStatement(SqlService.java:132)
        at org.schemaspy.service.DatabaseService.getBasicTableMetaFromSql(DatabaseService.java:432)
        at org.schemaspy.service.DatabaseService.getBasicTableMeta(DatabaseService.java:420)
        at org.schemaspy.service.DatabaseService.initTables(DatabaseService.java:145)
        at org.schemaspy.service.DatabaseService.gatheringSchemaDetails(DatabaseService.java:75)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:212)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:107)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
        at org.schemaspy.Main.main(Main.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
(0sec)
Connecting relationships...(0sec)
Writing/graphing summary.WARN  - No tables or views were found in schema 'students'.
ERROR - The schema 'students' could not be read/found, schema is specified using the -s option.Make sure user 'null' has the correct privileges to read the schema.Also not that schema names are usually case sensitive.
INFO  - Available schemas(Some of these may be user or system schemas):

ERROR - Unable to determine if any of the schemas contain tables/views
WARN  - Empty schema
org.schemaspy.model.EmptySchemaException: null
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:222)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:107)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
        at org.schemaspy.Main.main(Main.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by asarmy** [comment]
@npetzall  I just tried it with another database, and it worked! (The 'students.db' worked in SchemaSpy5, so not sure what's going... so will troubleshoot that on my end.) Glad I can use version 6 now, the layout is really slick. Thanks!

Separate issue: I think related to SQLite oddities, that I did notice in SchemaSpy5 and is happening here in version 6: relationship diagrams look great (FK mapping, etc.) but SchemaSpy is not recognizing PK for some tables (I posted about it [here](https://stackoverflow.com/questions/55053736/sqlite-is-not-assigning-primary-keys/55058999#55058999))

**Comment by npetzall** [comment]
Interesting, I'll have a look after the kids have fallen asleep.

**Comment by npetzall** [comment]
@asarmy the students db is it available online or is it a "private" database?

I've tested with chinook.db available from http://www.sqlitetutorial.net/sqlite-sample-database/

It works, but primaryKeys failes I saw the problem and I created a new issue #527

**Comment by asarmy** [comment]
the students.db is not online unfortunately. Thanks for looking into the PK fails and creating a new issue--I'll be sure to follow it. Thanks for your help, SchemaSpy is such a great tool. Cheers

**Comment by npetzall** [comment]
@asarmy for studens.db could you test 6.1.0-SNAPSHOT and use `-t sqlite-xerial` since I'm not sure you need the `selectTablesSql=.tables` that you have in your sqlite.properties file. The above fails due to `selectTablesSql=.tables`

**Comment by flurin-conradin** [comment]
I seem to have the same issue. Haven't tried with test 6.1.0-SNAPSHOT though. Where do I get that? Does not seem to be a release, right?

**Comment by npetzall** [comment]
@flurin-conradin you can find link under https://github.com/schemaspy/schemaspy#latest-build

Should download sqlite jdbc driver from xerial and use `-t sqlite-xerial`

If you still get errors add `-debug` and post the stacktrace, make sure to remove any sensitive data.

**Comment by flurin-conradin** [comment]
Thanks, it worked. In hindsight, it might have worked before already. I just failed at specifying command line options correctly, in particular -cat, which I specified as -cat SYS.

**Comment by jrsrjrsr** [comment]
I was having a similar problems and found this Issue.  Using the information in this thread, I got SchemaSpy 6.0.0 to work with sqlite using:

`java -jar schemaspy-6.0.0.jar`

with an `sqlite.properties` file containing:

`description=SQLite`
`connectionSpec=jdbc:sqlite:<db>`
`driver=org.sqlite.JDBC`
`driverPath=sqlite-jdbc-3.27.2.1.jar`

an an `schemaspy.properties` file containing:

`schemaspy.t=sqlite`
`schemaspy.db=../my_db_name.sqlite3`
`schemaspy.sso=true`
`schemaspy.o=./output`
`schemaspy.cat=my_db_name`
`schemaspy.s=my_db_name`

**Comment by naushad-madakiya** [comment]
> Following is the configuration I am using (same as @jrsrjrsr  provided above)

![Screenshot 2019-09-11 at 12 29 35 PM](https://user-images.githubusercontent.com/8583183/64675118-fe196600-d48f-11e9-80b1-dc4dcefd2d3e.png)
![Screenshot 2019-09-11 at 12 29 57 PM](https://user-images.githubusercontent.com/8583183/64675120-fe196600-d48f-11e9-9717-04e084d704db.png)

I am getting a similar error as @asarmy 
> java -jar schemaspy-6.1.0.jar -debug
```
SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0-SNAPSHOT on Naushads-MacBook-Air.local with PID 40461 (/Users/naushad/Desktop/schemaspy/schemaspy-6.1.0.jar started by naushad in /Users/naushad/Desktop/schemaspy)
INFO  - The following profiles are active: default
INFO  - Found configuration file: schemaspy.properties
INFO  - Started Main in 1.9 seconds (JVM running for 2.596)
DEBUG - Debug enabled
INFO  - Loaded configuration from schemaspy.properties
INFO  - Starting schema analysis
DEBUG - Resolving dbType: sqlite ->
	sqlite.properties
DEBUG - DbSpecificOption name: 'db' value: '../rblogbook.sqlite' description: 'null'
DEBUG - supportsSchemasInTableDefinitions: false
DEBUG - supportsCatalogsInTableDefinitions: false
INFO  - Connected to SQLite - 3.27.2
INFO  - Gathering schema details
Gathering schema details...(0sec)
Connecting relationships...WARN  - No tables or views were found in schema 'rblogbook'.
ERROR - The schema 'rblogbook' could not be read/found, schema is specified using the -s option.Make sure user 'null' has the correct privileges to read the schema.Also not that schema names are usually case sensitive.
INFO  - Available schemas(Some of these may be user or system schemas):

ERROR - Unable to determine if any of the schemas contain tables/views
WARN  - Empty schema
org.schemaspy.model.EmptySchemaException: null
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:255)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by npetzall** [comment]
Path to database seems incorrect.

Schemaspy jar and database are in same folder so the `../` would mean that it's located in the parent folder.

**Comment by npetzall** [comment]
You might have created a new empty db in the parent folder.

**Comment by ckhung** [comment]
Hi, please allow me to ask a few simple questions before presenting my main question.
Many thanks to  @jrsrjrsr 's very helpful comment which get me off square 0.
From my reading and quite a few futile experiments, my understanding is that:
1. Schemaspy reads the schemaspy.properties config file if there is one.
2. Schemaspy further reads the sqlite.properties config file if there is schemaspy.t=sqlite in the above file.
3. Command line options overwrite the options specified in the above two files.
4. the driver= option in the sqlite.properties config file has no command line counterpart.

@npetzall can you please confirm or correct each of the above?
It would help a lot if these are prominently written in the document and/or help and/or debugging messages.

So I downloaded [sqlite-jdbc-3.32.3.2.jar](https://github.com/xerial/sqlite-jdbc/releases/download/3.32.3.2/sqlite-jdbc-3.32.3.2.jar) and [chinook](https://www.sqlitetutorial.net/sqlite-sample-database/) and removed the experimental schemaspy.properties file and have this sqlite.properties file:
```
description=SQLite
connectionSpec=jdbc:sqlite:<db>
driver=org.sqlite.JDBC
driverPath=sqlite-jdbc-3.32.3.2.jar
```
Then I give this command: ```java -jar schemaspy-6.1.0.jar -debug -t sqlite -o /tmp -sso -cat chinook -s chinook -db chinook.db ``` then the relevant part of the error message is:
```
Connecting relationships...WARN  - No tables or views were found in schema 'chinook'.
ERROR - The schema 'chinook' could not be read/found, schema is specified using the -s option.Make sure user 'null' has the correct privileges to read the schema.Also not that schema names are usually case sensitive.
INFO  - Available schemas(Some of these may be user or system schemas):

ERROR - Unable to determine if any of the schemas contain tables/views
WARN  - Empty schema
org.schemaspy.model.EmptySchemaException: null

```
Did I miss something? It would be really nice if there is a working example of schemaspy connecting to sqlite using the publicly available chinook sample database. Many thanks in advance!

**Comment by ckhung** [comment]
My apology. The above setup and command actually works! I had been using a modified version of chinook.db and therefore got the mysterious error message. After replacing it with the freshly downloaded chinook.db , it works!

**Comment by rafalkasa** [comment]
This look like that issue was resolved. I close the issue if you have any other question please reopen this issue or create another.
