### ISSUE TITLE
Case (in)sensitive table names lead to error 'Column information from DatabaseMetaData differs from ResultSetMetaData'

### ISSUE THREAD

**Issue by ktetzlaff** [schemaspy/schemaspy#539]
I have inherited a PostgreSQL data base (PostgreSQL 9.6.9, running on Debian Linux, using java 11.0.2 with JDBC driver postgreql-42.2.5.jar). When running SchemaSpy (tried with an older 6.0.0-rc2 version and 6.1.0-SNAPSHOT as of 20190326),  on that db, I get the following exception (from a run with the SNAPSHOT version):

```
Exception in thread "Thread-2" org.schemaspy.input.dbms.service.InconsistencyException: Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: 'userid' in ['testsession','description','ts_id']
	at org.schemaspy.input.dbms.service.ColumnService.initColumnAutoUpdate(ColumnService.java:149)
	at org.schemaspy.input.dbms.service.ColumnService.gatherColumns(ColumnService.java:46)
	at org.schemaspy.input.dbms.service.TableService.gatheringTableDetails(TableService.java:76)
	at org.schemaspy.input.dbms.service.DatabaseService$TableCreator.createImpl(DatabaseService.java:334)
	at org.schemaspy.input.dbms.service.DatabaseService$ThreadedTableCreator$1.run(DatabaseService.java:379)
```

While trying to find out what may cause this issue, I found that the db contains two tables with names that differ only in case: 'testsession' and 'TestSession'. They are defined as shown below:

```
                             Table "public.testsession"
   Column    |  Type   |                          Modifiers
-------------+---------+-------------------------------------------------------------
 ts_id       | integer | not null default nextval('testsession_ts_id_seq'::regclass)
 testsession | text    | default ''::character varying
 description | text    |
 tstype      | integer | default 1
 completed   | integer | default 0
 userid      | integer | default 0
```
```
                                    Table "public.TestSession"
   Column    |         Type          |                          Modifiers
-------------+-----------------------+-------------------------------------------------------------
 testsession | character varying(7)  |
 description | character varying(64) |
 ts_id       | integer               | not null default nextval('testsession_ts_id_seq'::regclass)
```

Is it possible that SchemaSpy gets confused by the 'duplicate' tables?

The generated output is missing the columns overview (i.e. has an empty 'Columns' page). Probably as a result of the earlier exception.

I've tried to reproduce the problem with a stripped down db (commands from a psql session):

```
create database schemaspy_test;
\connect schemaspy_test
CREATE TABLE public.testsession (ts_id integer, testsession text, description text, userid integer);
CREATE TABLE public."TestSession" (testsession character varying(7), description character varying(64), ts_id integer);
```

Running schemaspy on schemaspy_test results in the same (or a very similar) error:

```
Gathering schema details...Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.input.dbms.service.InconsistencyException: Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: 'userid' in ['testsession','description','ts_id']
	at org.schemaspy.input.dbms.service.ColumnService.initColumnAutoUpdate(ColumnService.java:149)
	at org.schemaspy.input.dbms.service.ColumnService.gatherColumns(ColumnService.java:46)
	at org.schemaspy.input.dbms.service.TableService.gatheringTableDetails(TableService.java:76)
	at org.schemaspy.input.dbms.service.DatabaseService$TableCreator.createImpl(DatabaseService.java:334)
	at org.schemaspy.input.dbms.service.DatabaseService$TableCreator.create(DatabaseService.java:329)
	at org.schemaspy.input.dbms.service.DatabaseService.initTables(DatabaseService.java:174)
	at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(DatabaseService.java:88)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:244)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:121)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	... 8 more
```

**Comment by npetzall** [comment]
Yeah, case is ignored in SchemaSpy, this is from 5.0. We haven't changed it, since we actually don't know how much problems we would get it we removed it.

**Comment by npetzall** [comment]
What we could do is to introduce a -casesensitive option, that way we might find specific cases where we need to do case-in-senstive lookups.

**Comment by mkurz** [comment]
Wow, schemaspy ignoring case is a real problem for us. We have a Postgres 13 db with single letter columns like `t` and `T` (and many more, like `P`, `p`, ...) and schemaspy just swallows one half of the columns.
Even worse, it shows that `T` has an unique index, but that is wrong, `t` has the unique index (but `t` does not even get shown).

**Comment by annjulyleon** [comment]
I've encountered the same problem with two tables with same names. Schemaspy collect only one table and ignores the other. Is there any workaround to force schemaspy to collect both tables?

**Comment by ktetzlaff** [comment]
@annjulyleon: I did not find a workaround which includes both tables in the output. However, you can use the `-I` option to exclude some table(s):
```
[-I excludeTableRegex]

    Exclude table(s) from analysis, defaults to exclude tables containing $, can be overridden with -I ""
```
If I remember correctly, the `excludeTableRegex` is actually case sensitive. So I ended up using `-I 'TestSession'` to exclude one of my two conflicting tables. That made the result more predictable (and got rid of the Exception).

In my case, the ignored table wasn't really important to the project. But you could also run SchemaSpy multiple times with different excludes to get a representation of all tables - just not in the same output.
