### ISSUE TITLE
MSSQL08 sso connection with windows authentication is failing to connect to the database

### ISSUE THREAD

**Issue by user0624** [schemaspy/schemaspy#566]
I logged into windows box with my windows authentication credentials and I am trying the execute the schemaspy command with sso option. I have followed schemaspy sso documentation and added the required parameters to the schemaspy command but connection is failing with blank user.

## Expected Behavior

When I execute the schemaspy command locally on the windows box where my credentionals are authenticated during the login. I expect schemaspy to utilize the windows authentication and connect to the desired MSSQL database as per the connection details provided in the command.

## Current Behavior

Currently command is failing with below connection error.

WARN  - Connection Failure
Failed to connect to database URL [jdbc:sqlserver://xyz.com:1433;databaseName=DB1] Login failed for user ''. ClientConnectionId:276d63af-8912-4ac5-b365-6e53fb04e35f
INFO  - StackTraces have been omitted, use `-debug` when executing SchemaSpy to see them

## Steps to Reproduce (for bugs)

D:\>java -jar -Djava.library.path=D:\Software\sqljdbc_7.2\enu\auth\x64  D:\schemaspy\schemaspy-6.1.0-SNAPSHOT.jar -sso -connprops integratedSecurity\\=true -t mssql08 -dp D:\schemaspy\mssql-jdbc-7.2.2.jre8.jar -host xyz.com -port 1433 -db DB1 -o D:\schemaspy\output -all -cat catalog -vizjs -r enderer :cairo -debug
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.1.0-SNAPSHOT

SchemaSpy generates an HTML representation of a database schema's relationships.

SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0-SNAPSHOT on xyz with PID 2292 (D:\schemaspy\schemaspy-6.1.0-SNAPSHOT.jar started by xyz100 in D:\)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.963 seconds (JVM running for 2.847)
DEBUG - Debug enabled
INFO  - Configuration file not found
DEBUG - Resolving dbType: mssql08 ->
        /D:/schemaspy/schemaspy-6.1.0-SNAPSHOT.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql08.properties ->
        /D:/schemaspy/schemaspy-6.1.0-SNAPSHOT.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql05.properties ->
        /D:/schemaspy/schemaspy-6.1.0-SNAPSHOT.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: ‘xyz.com:1433' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'DB1’ description: 'database name'
WARN  - Connection Failure
org.schemaspy.model.ConnectionFailure: Failed to connect to database URL [jdbc:sqlserver://xyz.com:1433;databaseName=DB1] Login failed for user ''. ClientConnectionId:2ea7a067-01c4-435e-9c80-65690c4b7624
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:101)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:75)
        at org.schemaspy.SchemaAnalyzer.getConnection(SchemaAnalyzer.java:460)
        at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:133)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:114)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user ''. ClientConnectionId:2ea7a067-01c4-435e-9c80-65690c4b7624
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
        at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:258)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:104)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5036)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3668)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:94)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3627)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2935)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2456)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2103)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1950)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1162)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:735)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:94)
        ... 15 common frames omitted

D:\>

## Context

* Database type (e.g. MySQL): MSSQL 2008R2
* Database driver version (is you use a special one): mssql-jdbc-7.2.2.jre8.jar
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:
java -jar -Djava.library.path=D:\Software\sqljdbc_7.2\enu\auth\x64  D:\schemaspy\schemaspy-6.1.0-SNAPSHOT.jar -sso -connprops integratedSecurity\\=true -t mssql08 -dp D:\schemaspy\mssql-jdbc-7.2.2.jre8.jar -host xyz.com -port 1433 -db DB1 -o D:\schemaspy\output -all -cat catalog -vizjs -r enderer :cairo -debug

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10):
* Java version:

**Comment by npetzall** [comment]
Could you add `-debug` to commandline and post the stacktrace.

**Comment by npetzall** [comment]
Have you read this
 https://schemaspy.readthedocs.io/en/v6.0.0/sso.html

**Comment by user0624** [comment]
Yes. I have referred that document and added all the required parameters in the schemaspy command but connection is still failing.

Login failed for user '' <- User is showing as blank here. Its not taking any user.

**Comment by npetzall** [comment]
I'm suspecting that it doesn't pick up `-connprops integratedSecurity\\=true`.

A quick way of checking that is to run `java -jar D:\schemaspy\schemaspy-6.1.0-SNAPSHOT.jar -sso -connprops integratedSecurity\\=true -t mssql08 -dp D:\schemaspy\mssql-jdbc-7.2.2.jre8.jar -host xyz.com -port 1433 -db DB1 -o D:\schemaspy\output -all -cat catalog -vizjs -debug`  and see if you get the following error `Failed to load the sqljdbc_auth.dll`

**Comment by user0624** [comment]
Getting the same error even if the parameter is removed.

D:\>java -jar D:\schemaspy\schemaspy-6.1.0-SNAPSHOT.jar -sso -connprops integratedSecurity\\=true -t mssql08 -dp D:\schemaspy\mssql-jdbc-7.2.2.jre8.jar -host xyz.com -port 1433 -db DB1 -o D:\schemaspy\output -all -cat catalog -vizjs -renderer :cairo
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.1.0-SNAPSHOT

SchemaSpy generates an HTML representation of a database schema's relationships.

SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL
 version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0-SNAPSHOT on xyz with PID 15384 (D:\schemaspy\schemaspy-6.1.0-SNAPSHOT.jar started by xyz100 in D:\)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.797 seconds (JVM running for 2.543)
INFO  - Configuration file not found
WARN  - Connection Failure
Failed to connect to database URL [jdbc:sqlserver://xyz.com:1433;databaseName=DB1] Login failed for user ''. ClientConnectionId:666ff
4f9-245e-4ab4-9fb3-e5e6661310a4
INFO  - StackTraces have been omitted, use `-debug` when executing SchemaSpy to
see them

D:\>

**Comment by npetzall** [comment]
Sorry for getting back so late. I've had trouble finding time.

But I finally figured out what the problem is and it's a really painful one.

`-connprops` and the number of `\` before the `=` differ depending on the terminal/shell used.
I'm gonna update the documentation.

Linux or Windows using any type och bash terminal you need `\\=` for Git bash which I mainly use needs two.
Windows and cmd only requires 1.

So to get it working in cmd:
`java -Djava.library.path=D:\Software\sqljdbc_7.2\enu\auth\x64 -jar D:\schemaspy\schemaspy-6.1.0-SNAPSHOT.jar -sso -connprops integratedSecurity\=true -t mssql08 -dp D:\schemaspy\mssql-jdbc-7.2.2.jre8.jar -host xyz.com -port 1433 -db DB1 -o D:\schemaspy\output -all -vizjs`
and in git bash or similar:
`java -Djava.library.path=D:\Software\sqljdbc_7.2\enu\auth\x64 -jar D:\schemaspy\schemaspy-6.1.0-SNAPSHOT.jar -sso -connprops integratedSecurity\\=true -t mssql08 -dp D:\schemaspy\mssql-jdbc-7.2.2.jre8.jar -host xyz.com -port 1433 -db DB1 -o D:\schemaspy\output -all -vizjs`

**Comment by fuixx217** [comment]
Thanks npetzall for documenting that -- was just trying to do this as well, and this thread popped up and you were really helpful here.

**Comment by user0624** [comment]
Thanks npetzall. Just to confirm that this worked pretty well !!!

**Comment by npetzall** [comment]
Documentation should be update shortly.
