### ISSUE TITLE
Postgres 10.7 - cannot generate docs

### ISSUE THREAD

**Issue by vladt89** [schemaspy/schemaspy#597]
## Expected Behavior
I would like to get the documentation:)

## Current Behavior
Documentation is not generated, well, I can see the list of tables, but if I click to any of the Table name, it does not open separate page.

## Context
* Database type (e.g. MySQL): Postgres 10.7
* Database driver version (is you use a special one): postgresql-42.2.8.jar
* Full command including arguments how you run SchemaSpy: 
java -jar schemaspy-6.1.0.jar -dp postgresql-42.2.8.jar -t pgsql -db postgres -s <schema> -host localhost:<port> -u <user> -p <password> -o c2-db-doc

I try to run this command, but first I get the following warning:

```
INFO  - The following profiles are active: default
INFO  - Started Main in 0.945 seconds (JVM running for 1.296)
INFO  - Starting schema analysis
INFO  - Connected to PostgreSQL - 11.4 (Debian 11.4-1.pgdg90+1)
INFO  - Gathering schema details
Gathering schema details.............................................WARN  - Failed to retrieve stored procedure/function details using sql 'select r.routine_name, case when p.proisagg then 'AGGREGATE' else 'FUNCTION' end as routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body, r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on ns.oid = p.pronamespace and r.routine_name = p.proname left join pg_description d on d.objoid = p.oid where r.routine_schema = :schema'
ERROR: column p.proisagg does not exist
  Hint: Perhaps you meant to reference the column "p.prolang".
  Position: 34
(0sec)
Connecting relationships.............................................(0sec)
```

Here as well I noticed that it says that I am connected to 11.4, however, I have 10.7 database. 

Moreover, the tables are also not generated, this is one of them:

```
.......ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: *** First throw call stack:
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: (
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	0   CoreFoundation                      0x00007fff4dfbb2fd __exceptionPreprocess + 256
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	1   libobjc.A.dylib                     0x00007fff7868ba17 objc_exception_throw + 48
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	2   CoreFoundation                      0x00007fff4e035056 __CFExceptionProem + 0
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	3   CoreFoundation                      0x00007fff4df5d18f ___forwarding___ + 1485
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	4   CoreFoundation                      0x00007fff4df5cb38 _CF_forwarding_prep_0 + 120
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	5   CoreFoundation                      0x00007fff4deef67c CFStringCompareWithOptionsAndLocale + 68
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	6   ImageIO                             0x00007fff50924c85 _ZN17IIO_ReaderHandler15readerForUTTypeEPK10__CFString + 51
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	7   ImageIO                             0x00007fff508fd0a6 _ZN14IIOImageSource14extractOptionsEP13IIODictionary + 182
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	8   ImageIO                             0x00007fff50929b86 _ZN14IIOImageSourceC2EP14CGDataProviderP13IIODictionary + 72
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	9   ImageIO                             0x00007fff50929a59 CGImageSourceCreateWithDataProvider + 172
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	10  libgvplugin_quartz.6.dylib          0x000000010db67c5c quartz_loadimage_quartz + 224
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	11  libgvc.6.dylib                      0x000000010da8b9bd gvloadimage + 269
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	12  libgvc.6.dylib                      0x000000010da8aa21 gvrender_usershape + 956
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	13  libgvc.6.dylib                      0x000000010daa17bb emit_html_tbl + 1329
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	14  libgvc.6.dylib                      0x000000010daa1732 emit_html_tbl + 1192
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	15  libgvc.6.dylib                      0x000000010daa11d7 emit_html_label + 439
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	16  libgvc.6.dylib                      0x000000010daaead5 emit_label + 56
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	17  libgvc.6.dylib                      0x000000010dab86df poly_gencode + 2205
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	18  libgvc.6.dylib                      0x000000010dac4b41 emit_node + 1025
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	19  libgvc.6.dylib                      0x000000010dac38d0 emit_graph + 5048
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	20  libgvc.6.dylib                      0x000000010dac8e4c gvRenderJobs + 4936
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	21  dot                                 0x000000010da81d62 main + 697
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: 	22  libdyld.dylib                       0x00007fff79e593d5 start + 1
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: )
ERROR - dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx: libc++abi.dylib: terminating with uncaught exception of type NSException
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate Table diagram
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:71)
	at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram(MustacheDiagramFactory.java:44)
	at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams(MustacheTableDiagramFactory.java:80)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:426)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	... 8 more
Caused by: org.schemaspy.output.diagram.DiagramException: 'dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx' failed with exception org.schemaspy.output.diagram.DiagramException: 'dot -Tpng ContactContent.ChatMessage.1degree.dot -oContactContent.ChatMessage.1degree.png -Tcmapx' failed with return code 134
	at org.schemaspy.output.diagram.graphviz.GraphvizDot.generateDiagram(GraphvizDot.java:237)
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:68)
	... 16 more
```

## Your Environment
* Version used: schemaspy 6.1.0
* Postgres 10.7
* Operating System and version (e.g. Windows 10): MacOS Mojave 10.14.6
* Java version: java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

_**Any hints how to resolve this?**_

**Comment by npetzall** [comment]
There are probably two issue.

1, is that graphviz is really troublesome on OSX. You could try `-vizjs` to use the Javascript version of graphviz.
2, The version is as reported by jdbc and the type of error you get is when using `-t pgsql` with 11.2 or newer #537 so you might be connecting to 11.7 and as such you should use `-t pgsql11`

**Comment by vladt89** [comment]
1. Will try.
2. Yes, that helped. Now I can see the amount of routines/functions one the html page. Do you know if I should be able to see the signatures of those functions?
