### ISSUE TITLE
Schemaspy in docker fails to generate a schema - java.lang.NullPointerException

### ISSUE THREAD

**Issue by petarGitNik** [schemaspy/schemaspy#610]
## Expected Behavior

Upon executing schemaspy schema (html with accompanying) should be generated within a docker container.

## Current Behavior

Schema fails to generate.

```
INFO  - Starting Main v6.1.0 on sirius-HP-250-G6-Notebook-PC with PID 106 (/opt/schemaspy started by root in /root)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.522 seconds (JVM running for 2.105)
DEBUG - Debug enabled
INFO  - Starting schema analysis
DEBUG - Resolving dbType: pgsql11 ->
	/opt/schemaspy!/BOOT-INF/classes!/org/schemaspy/types/pgsql11.properties ->
	/opt/schemaspy!/BOOT-INF/classes!/org/schemaspy/types/pgsql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'localhost' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'userdb' description: 'database name'
DEBUG - supportsSchemasInTableDefinitions: true
DEBUG - supportsCatalogsInTableDefinitions: false
DEBUG - Catalog not provided, queried jdbc driver and got 'userdb'
DEBUG - Schema not provided, queried jdbc driver and got 'public'
INFO  - Connected to PostgreSQL - 12.0
INFO  - Gathering schema details
Gathering schema details...DEBUG - Including table role: matches inclusion pattern '.*'
DEBUG - Creating Table public.role
DEBUG - Querying primary keys for public.role
.DEBUG - Retrieved details of public.role
DEBUG - SELECT datname AS catalog_name, pg_catalog.obj_description(datlastsysoid, 'pg_database') AS catalog_comment FROM pg_catalog.pg_database WHERE datname = ? ; [userdb]
DEBUG - SELECT nspname AS schema_name, pg_catalog.obj_description(oid, 'pg_namespace') AS schema_comment FROM pg_catalog.pg_namespace where nspname = ? [public]
DEBUG - select tc.table_name, tc.constraint_name, cc.check_clause as text from information_schema.check_constraints cc left join information_schema.table_constraints tc on tc.constraint_catalog = cc.constraint_catalog and tc.constraint_schema = cc.constraint_schema and tc.constraint_name = cc.constraint_name where cc.constraint_name not like '%not_null' and tc.constraint_schema = ? [public]
DEBUG - select r.routine_name, case p.prokind when 'f' then 'FUNCTION' when 'p' then 'PROCEDURE' when 'a' then 'AGGREGATE' when 'w' then 'WINDOW' else 'UNKNOWN' end as routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body, r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on ns.oid = p.pronamespace and r.routine_name = p.proname left join pg_description d on d.objoid = p.oid where r.routine_schema = ? [public]
DEBUG - select r.routine_name as specific_name, coalesce(p.parameter_name, '$' || p.ordinal_position) as parameter_name, p.data_type as dtd_identifier, p.parameter_mode from information_schema.parameters p left join information_schema.routines r on r.specific_name = p.specific_name where p.specific_schema = ? order by p.specific_name, p.ordinal_position [public]
DEBUG - SELECT seqs.sequence_name, seqs.start_value, seqs.increment FROM information_schema.sequences seqs WHERE seqs.sequence_schema = ? [public]
(0sec)
Connecting relationships....(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
...Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NullPointerException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
	at sun.font.SunFontManager$2.run(SunFontManager.java:431)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Font.getFont2D(Font.java:491)
	at java.awt.Font.access$000(Font.java:224)
	at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)
	at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)
	at sun.font.StandardGlyphVector.initFontData(StandardGlyphVector.java:1126)
	at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1115)
	at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:172)
	at java.awt.Font.getStringBounds(Font.java:2421)
	at java.awt.Font.getStringBounds(Font.java:2331)
	at org.schemaspy.output.dot.schemaspy.DotNode.getTextWidth(DotNode.java:185)
	at org.schemaspy.output.dot.schemaspy.DotNode.getColumnMaxWidth(DotNode.java:170)
	at org.schemaspy.output.dot.schemaspy.DotNode.columnsToString(DotNode.java:144)
	at org.schemaspy.output.dot.schemaspy.DotNode.toString(DotNode.java:122)
	at org.schemaspy.output.dot.schemaspy.DotFormatter.writeOrphan(DotFormatter.java:330)
	at org.schemaspy.output.html.mustache.diagrams.MustacheOrphanDiagramFactory.generateOrphanDiagrams(MustacheOrphanDiagramFactory.java:79)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:366)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	... 8 more
```

## Possible Solution

No suggestions.

## Steps to Reproduce (for bugs)

1. Build docker image from following docker file using this command: `docker build -t schemaspy:test .`

```
FROM alpine:3.9.4

ARG SCHEMASPY_VERSION=6.1.0
ARG PGSQL_VERSION=42.2.8

WORKDIR /root

RUN apk add --update --no-cache openjdk8-jre=8.222.10-r0 \
  && wget "https://github.com/schemaspy/schemaspy/releases/download/v${SCHEMASPY_VERSION}/schemaspy-${SCHEMASPY_VERSION}.jar" -O schemaspy \
  && wget "https://jdbc.postgresql.org/download/postgresql-${PGSQL_VERSION}.jar" -O pgsql-driver \
  && mv /root/schemaspy /opt \
  && mkdir -p /opt/drivers \
  && mv /root/pgsql-driver /opt/drivers \
  && echo '#!/bin/sh' >> /usr/local/bin/schemaspy \
  && echo 'java -jar /opt/schemaspy -dp /opt/drivers/pgsql-driver -vizjs $@' >> /usr/local/bin/schemaspy \
  && chmod +x /usr/local/bin/schemaspy

CMD ["/bin/sh"]
```

2. Run postgres container

```
docker run -d --network host --name db -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=userdb postgres:12.0-alpine
```

3. Create test table in the database:

```
docker exec -it db psql -U user userdb -c 'CREATE TABLE role(role_id serial PRIMARY KEY, role_name VARCHAR (255) UNIQUE NOT NULL);'
```

4. Enter into shell of the schemaspy container:

```
docker run -it --network host --name schemaspy schemaspy:test sh
```

5. Execute schemaspy within the container:

```
schemaspy -u "user" -p "password" -host localhost -p 5432 -db "userdb" -t pgsql11 -hq -o output/ -debug
```

## Context

I'm trying to create schema within a docker container.

* Database type (e.g. MySQL): PostgreSQL
* Database driver version (is you use a special one): postgresql-42.2.8.jar

## Your Environment

* Version used: schemaspy 6.1.0
* Environment name and version (e.g. Chrome 39): Alpine 9 (Docker)
* Operating System and version (e.g. Windows 10): Ubuntu 16.04 on host
* Java version: openjdk8-jre v8.222.10-r0

**Comment by npetzall** [comment]
We already have an image for that which uses alpine. You can have a look at that, we have had three issues with alpine. 1, contains no fonts. 2, alpine contains no font configuration. 3, we hade an issue with a specific Java 8 update.

**Comment by petarGitNik** [comment]
@npetzall I cannot use your docker image in CI/CD because it requires DIND, which is not possible because of my CI/CD configuration. But with the addition of fonts, it seems that my image is working now. Thank you!

**Comment by npetzall** [comment]
Don't understand how the DIND would be required.

If the CI/CD is running in docker, it would just need the docker socket to be able to start a sibling container.

To retrieve the content/output it would be possible to use volumes-from and we could change the output folder (think there's a PR for using env)

**Comment by jflambert** [comment]
Hi @petarnikolovski and @npetzall 

> But with the addition of fonts

I'm using Alpine 3.17 and have the same error as you. Which fonts package am I suppose to install to fix this error?
