### ISSUE TITLE
he driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption

### ISSUE THREAD

**Issue by grwhite1** [schemaspy/schemaspy#633]
I have installed Schemaspy and I'm trying to connect to an MS SQL 2008 Database from a Windows 10 Client
I'm using Java 8 update 231

I do not have a great knowledge of Java but is there a setting I need to change in order to connect to the database?

Many thanks in advance.

Gary

######this is my cmd line 
 java -jar "C:\Program Files (x86)\schemaSpyGUI20090302\schemaSpy_5.0.0.jar" -dp "C:\Program Files (x86)\schemaSpyGUI20090302\Microsoft JDBC Driver 6.2 for SQL Server\sqljdbc_6.2\enu\mssql-jdbc-6.2.2.jre7.jar" -t mssql05 -db DACS_MSCRM -host DACSCRMDB -port 1433 -u xxxxxx -p xxxxxx -o "C:\Users\gary\Downloads\library" -ahic  -hq -gv "C:\Program Files (x86)\Graphviz2.38"

#####the output I'm getting is 
Using database properties:
  [C:\Program Files (x86)\schemaSpyGUI20090302\schemaSpy_5.0.0.jar]/net/sourceforge/schemaspy/dbTypes/mssql05.properties

Failed to connect to database URL [jdbc:sqlserver://DACSCRMDB:1433;databaseName=DACS_MSCRM]

com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "SQL Server did not return a response. The connection has been closed. ClientConnectionId:77bf39ad-f65f-4193-b804-881a548deb1c".
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2435)
        at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1816)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2022)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1687)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1528)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:866)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:569)
        at net.sourceforge.schemaspy.SchemaAnalyzer.getConnection(SchemaAnalyzer.java:582)
        at net.sourceforge.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:157)
        at net.sourceforge.schemaspy.Main.main(Main.java:42)
Caused by: java.io.IOException: SQL Server did not return a response. The connection has been closed. ClientConnectionId:77bf39ad-f65f-4193-b804-881a548deb1c
        at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.ensureSSLPayload(IOBuffer.java:774)
        at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.readInternal(IOBuffer.java:830)
        at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.read(IOBuffer.java:821)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1003)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:991)
        at sun.security.ssl.InputRecord.readFully(Unknown Source)
        at sun.security.ssl.InputRecord.read(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1753)
        ... 8 more

**Comment by npetzall** [comment]
That is the old schemaspy. Which I don't know too much about. Things have changed since back then.

As for your error. Seems like the database server isn't responding to the connection request. 

I would check that sqlcmd or sql server studio can connect from the same client.

Since this can be a firewall issue or that the sql server doesn't listen to tcp connections.

**Comment by grwhite1** [comment]
Okay thank you.

I just followed a link via the internet when I was having issues with database diagrams in SQL Studio. Is there a link to the new version then?

Kind regards,

Gary White
IT Manager
gary.white@dacs.org.uk<mailto:gary.white@dacs.org.uk>
D/L: +44 (0) 20 7553 9060

[DACS-logo-grey-for-email]<http://www.dacs.org.uk/>

DACS, 33 Old Bethnal Green Road, London, E2 6AA
T: +44 (0) 20 7336 8811
F: +44 (0) 20 7336 8822
dacs.org.uk<http://www.dacs.org.uk/?utm_source=email&utm_medium=email&utm_campaign=employee-signature&utm_content=textlink>

Follow us: Twitter<https://twitter.com/DACSforArtists> | Facebook<https://www.facebook.com/DACSforArtists/> | Instagram<https://www.instagram.com/dacsforartists/> | YouTube<https://www.youtube.com/user/DACSartists> | Subscribe to our e-news<http://eepurl.com/8mtZ9> | Download Art360’s archiving app<https://www.art360foundation.org.uk/art360-app/>

[cid:image004.png@01D52C01.798FE300]<http://fairshareforartists.org/>

Paying artists fairly keeps them making art. Protect artists’ rights.

Join our campaign at fairshareforartists.org<http://fairshareforartists.org/>


This message and any attachments are confidential. It may also be privileged or otherwise protected by work product immunity or other legal rules. If you have received it by mistake, please let us know by reply and then delete it from your system. You should not copy the message or disclose its contents to anyone. For more information on how DACS uses your personal data, see our Privacy Policy<https://www.dacs.org.uk/about-us/privacy-policy>.

The Design and Artists Copyright Society is a Company Limited by Guarantee.Reg office as above. Reg England No. 1780482

**Comment by npetzall** [comment]
New version of schemaspy can be found here https://github.com/schemaspy/schemaspy/releases/download/v6.1.0/schemaspy-6.1.0.jar

However your problem isn't with schemaspy it's with establishing a connection to the database.

**Comment by npetzall** [comment]
@grwhite1 any updates?

**Comment by phillipjohnson** [comment]
I am seeing this issue with SchemaSpy 6.1.0 and MSSQL Driver 10.2.0 on Windows 2012. Falling back to MSSQL Driver 9.2.0 fixed the problem. I have a feeling it has something to do with the allow cipher suites, but I have not investigate in detail.

**Comment by npetzall** [comment]
@phillipjohnson which version of sql server are you connecting to?

**Comment by mprins** [comment]
New jdbc driver version (10.2.x) has TLS enabled  by default. Check the MS release notes and driver documentation, you can turn it off using a connection parameter

**Comment by phillipjohnson** [comment]
> New jdbc driver version (10.2.x) has TLS enabled by default. Check the MS release notes and driver documentation, you can turn it off using a connection parameter

Thank you, that makes sense.
