### ISSUE TITLE
Failed if table names are non-ascii 

### ISSUE THREAD

**Issue by anzai** [schemaspy/schemaspy#635]
Some tables in my database have non-ascii (Japanese) names, and Schemaspy fails with an Exception.
It seems handling "{tablename}.1degree.dot" doesn't work well.

```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: ???????.1degree.dot
```

## Expected Behavior
Succeed even if table names are non-ascii.

## Current Behavior
Exception occurs.

```java
...Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: ???????.1degree.dot
        at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
        at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
        at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
        at org.schemaspy.output.html.mustache.diagrams.MustacheOrphanDiagramFactory.generateOrphanDiagrams(MustacheOrphanDiagramFactory.java:76)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:366)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
```

## Steps to Reproduce (for bugs)

```sh
DBMS=pgsql

docker run --rm \
  -e LANG=ja_JP.UTF-8 \
  -v "${DST_DIR}:/output" \
  --net="host" schemaspy/schemaspy \
  -t ${DBMS} -host ${_HOST}:${_PORT} -db ${_DB} -u ${_DBUSER} -p ${_DBPASSWORD} -s ${_SCHEMA} 
```

## Your Environment

* SchemaSpy in Docker: 6.1.0

**Comment by npetzall** [comment]
This is partially related to #360. The same solution should work. Will do a check on that one, or modify the code to avoid any copyright/license issue.
