### ISSUE TITLE
Materialized views issue

### ISSUE THREAD

**Issue by fernandobrenes** [schemaspy/schemaspy#636]
After introducing Materialized Views in Schemaspy 6.1.0  as part of https://github.com/schemaspy/schemaspy/pull/390 I'm getting the following error:

`
ERROR - select definition as view_definition from pg_views where viewname = :tab
le UNION select definition as view_definition from pg_matviews where matviewname
 = :table
ERROR - SqlException
org.postgresql.util.PSQLException: ERROR: relation "pg_matviews" does not exist
  Position: 120
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryEx
ecutorImpl.java:2505)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutor
Impl.java:2241)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.ja
va:310)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)

        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedSt
atement.java:158)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatem
ent.java:108)
        at org.schemaspy.input.dbms.service.ViewService.gatherViewDefinition(Vie
wService.java:86)
        at org.schemaspy.input.dbms.service.ViewService.gatherViewsDetails(ViewS
ervice.java:68)
        at org.schemaspy.input.dbms.service.DatabaseService.initViews(DatabaseSe
rvice.java:211)
        at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(
DatabaseService.java:92)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:246)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98
)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner
.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
`

## Expected Behavior
Exception to be handled.

## Current Behavior
Since pg_matviews doesn't exist then I can't use SchemaSpy 6.1.0 with Postgres.
SchemaSpy 6.0.0 works fine.

## Steps to Reproduce (for bugs)
1. Run SchemaSpy 6.1.0 against postgres without Materialized views

## Context
* Database type (e.g. MySQL): PostgreSQL - 9.1.9
* Database driver version (is you use a special one): postgresql-42.2.9.jar

Thank you!

**Comment by npetzall** [comment]
Ahh, I need to check pg_matviews, might have been introduced in Postgres 10. If so I need to find a solution for 9 and move the properties files around. I can provide a workaround in cpl of hrs. Putting kids to bed.

**Comment by fernandobrenes** [comment]
Hi @npetzall 

Thank you! :)

**Comment by npetzall** [comment]
Sorry, kid wouldn't fall asleep and then it escaped me.

Create a file in the same dir as schemaspy-jar file. Let's call it `mypgsql.properties`

It should have the following content
```
extends=pgsql
selectViewSql=select definition as view_definition from pg_views where viewname = :table
```

Now run schemaspy with `-t mypgsql` instead of `-t pgsql`

**Comment by fernandobrenes** [comment]
Hi @npetzall,

Thank you for your help :) 

This is my command: 

`C:\Program Files\OmniBack\idb\bin>"C:\Program Files\Omniback\jre\bin\java.exe" -
jar C:\Users\Administrator.DPLAB\Desktop\schemaspy\schemaspy-6.1.0.jar -vizjs -t
 mypgsql -dp C:\Users\Administrator.DPLAB\Desktop\schemaspy\postgresql-42.2.9.ja
r -db hpdpidb -host localhost:7112 -u support -p xxxxxxxxxx -s hpdpidb_app -o C:
\DPIDB -debug`

This is the content of schemaspy folder:

```
PS C:\Users\Administrator.DPLAB\Desktop\schemaspy> dir
    Directory: C:\Users\Administrator.DPLAB\Desktop\schemaspy


`Mode               LastWriteTime         Length Name
----                -------------         ------ ----
-a----         1/2/2020   8:19 AM            103 mypgsql.properties
-a----       12/26/2019  12:12 PM         914037 postgresql-42.2.9.jar
-a----       12/23/2019   8:43 AM       14122568 schemaspy-6.1.0.jar
```

This is the content of mypgsql.properties

```
PS C:\Users\Administrator.DPLAB\Desktop\schemaspy> Get-Content .\mypgsql.properties
extends=pgsql
selectViewSql=select definition as view_definition from pg_views where viewname = :table
```

I'm not sure if I'm missing something as it fails with:

```
INFO  - Starting schema analysis
DEBUG - Command line parameters: [-vizjs, -t, mypgsql, -dp, C:\Users\Administrat
or.DPLAB\Desktop\schemaspy\postgresql-42.2.9.jar, -db, hpdpidb, -host, localhost
:7112, -u, support, -p, xxxxxxxxxxx, -s, hpdpidb_app, -o, C:\DPIDB, -debug]
ERROR - Bad parameter: '-t = mypgsql'
org.schemaspy.model.InvalidConfigurationException: Unable to resolve databaseTyp
e: mypgsql
        at org.schemaspy.input.dbms.config.PropertiesResolver.getDbProperties(Pr
opertiesResolver.java:67)
```

Thank you,
Best regards

**Comment by npetzall** [comment]
Ahh, my bad. Should have been more precise, the `mypgsql.properties` should be in the workdir or I think the full path to the properties-file can be used. So move it to `C:\Program Files\OmniBack\idb\bin` or start schemaspy from `C:\Users\Administrator.DPLAB\Desktop\schemaspy`

We should maybe add a check to see if it's in the same dir as schemaspy-jar file

**Comment by fernandobrenes** [comment]
Hi @npetzall,

Thank you! I really appreciate it. I used the full path to the properties file and now it worked perfectly.
Best Regards
