### ISSUE TITLE
Schema spy connection failure using mysql

### ISSUE THREAD

**Issue by milostrugis** [schemaspy/schemaspy#639]
I am trying to set up schemaspy with mysql, but I repeatedly get the connection failure error.
Based on previous responses I reinstlled connector and modifod the command, I am using, which is:
C:\Users\XXX\Desktop\New folder>java -jar schemaspy-6.1.0.jar -t mysql -dp mysql-connector-java-8.0.19.jar -db pat-name -host localhost -sso -u 127.0.0.1:3306 [-p password] -o outputDir -cat pat-name -s pat-name -debug

Password is my password, the rest is copied from the command.
I work in windows, Java 8, schemaspy  6.1.0

The message I get is:
EBUG - Debug enabled
INFO  - Starting schema analysis
DEBUG - Resolving dbType: mysql ->
        /C:/Users/XXX/Desktop/New%20folder/schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mysql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'localhost' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'pat-name' description: 'database name'
WARN  - Connection Failure
org.schemaspy.input.dbms.exceptions.ConnectionFailure: Failed to connect to database URL [jdbc:mysql://localhost/pat-name] Access denied for user '127.0.0.1:3306'@'localhost' (using password: NO)
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:101)
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:75)
        at org.schemaspy.input.dbms.service.SqlService.connect(SqlService.java:70)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:220)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.sql.SQLException: Access denied for user '127.0.0.1:3306'@'localhost' (using password: NO)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:94)
        ... 15 common frames omitted

thank you very much for help.

**Comment by npetzall** [comment]
Let's start by removing `-sso`. It's the reason it complains about no password.

`-u` should be followed by a username. Like root or other suitable username. 
`-host localhost` can be replaced by `-host 127.0.0.1:3306`

**Comment by milostrugis** [comment]
Thank you,
it has not improved the stiuation,
I have run the command:
\Desktop\New folder>java -jar schemaspy-6.1.0.jar -t mysql -dp mysql-connector-java-8.0.19.jar -db pat-name -host 127.0.0.1:3306 -u root -p XXXXXX -o outputD -cat pat-name -s pat-name -debug
And I got the same message :
DEBUG - Resolving dbType: mysql ->
        /C:/Users/xxxx/Desktop/New%20folder/schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mysql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: '127.0.0.1:3306' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'pat-name' description: 'database name'
WARN  - Connection Failure

**Comment by milostrugis** [comment]
I thouhgt the message a message:
DEBUG - DbSpecificOption name: 'db' value: 'pat-name' description: 'database name'
means there is some problem with data base, but I can see when I run  mysql> show databases;

**Comment by npetzall** [comment]
It's really weird you should get something after the connection failure.

Mysql is a bit strange, `-db`, `-cat` and `-s` should all be the same.

That debug output is only related to parsing of input arguments.

**Comment by milostrugis** [comment]
I did, i ust did not copy the whole one:
command:
java -jar schemaspy-6.1.0.jar -t mysql -dp mysql-connector-java-8.0.19.jar -db pat-name -host 127.0.0.1:3306 -u root -p XXXX -o outputD -cat pat-name -s pat-name -debug

message:
DEBUG - Resolving dbType: mysql ->
        /C:/Users/xxxx/Desktop/New%20folder/schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mysql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: '127.0.0.1:3306' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'pat-name' description: 'database name'
WARN  - Connection Failure
org.schemaspy.input.dbms.exceptions.ConnectionFailure: Failed to connect to database URL [jdbc:mysql://127.0.0.1:3306/pat-name] Unknown database 'pat-name'
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:101)
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:75)
        at org.schemaspy.input.dbms.service.SqlService.connect(SqlService.java:70)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:220)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.sql.SQLSyntaxErrorException: Unknown database 'pat-name'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:94)
        ... 15 common frames omitted

In one of the lines it states unknown database pat-name
This is why I assumend there is some problem with the database

**Comment by npetzall** [comment]
Jdbc drivers can't connect to the database, either the user doesn't have access(but I think that's another error) or the name is incorrect in some way, might be special characters or spaces.

**Comment by milostrugis** [comment]
Thank you, 
I reset the comp and after the changes you advised, the base connected, but it still does not work properly, there is a myriad of bugs now, but there is some output:
DEBUG - Debug enabled
INFO  - Starting schema analysis
DEBUG - Resolving dbType: mysql ->
        /C:/Users/xxxx/Desktop/New%20folder/schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mysql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: '127.0.0.1:3306' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'pat-name' description: 'database name'
DEBUG - supportsSchemasInTableDefinitions: false
DEBUG - supportsCatalogsInTableDefinitions: true
INFO  - Connected to MySQL - 8.0.19
INFO  - Gathering schema details
Gathering schema details...DEBUG - select table_schema as table_catalog, null as table_schema, table_name, table_comment, table_rows from information_schema.tables where table_schema=? and table_type='BASE TABLE' [pat-name]
DEBUG - Including table patient_address: matches inclusion pattern '.*'
DEBUG - Creating Table pat-name.patient_address
DEBUG - Querying primary keys for pat-name.patient_address
DEBUG - select table_rows row_count from information_schema.tables where table_name=? and table_schema=? [patient_address, pat-name]
.DEBUG - Retrieved details of pat-name.patient_address
DEBUG - Including table patient_mid: matches inclusion pattern '.*'
DEBUG - Including table patient_name: matches inclusion pattern '.*'
DEBUG - Including table phone_no: matches inclusion pattern '.*'
DEBUG - Creating Table pat-name.patient_mid
DEBUG - Creating Table pat-name.patient_name
DEBUG - Creating Table pat-name.phone_no
DEBUG - Querying primary keys for pat-name.patient_mid
DEBUG - Querying primary keys for pat-name.phone_no
DEBUG - select table_rows row_count from information_schema.tables where table_name=? and table_schema=? [patient_mid, pat-name]
.DEBUG - select table_rows row_count from information_schema.tables where table_name=? and table_schema=? [phone_no, pat-name]
DEBUG - Retrieved details of pat-name.patient_mid
.DEBUG - Retrieved details of pat-name.phone_no
DEBUG - Querying primary keys for pat-name.patient_name
DEBUG - select table_rows row_count from information_schema.tables where table_name=? and table_schema=? [patient_name, pat-name]
.DEBUG - Retrieved details of pat-name.patient_name
DEBUG - select table_schema as view_catalog, null as view_schema, table_name as view_name, view_definition, null as view_comment from information_schema.views where table_schema=? [pat-name]
DEBUG - select table_name, column_name, replace(column_type,"','","', '") as column_type, left(column_type, locate("(", column_type)-1) as short_column_type from information_schema.columns where table_schema=? and (column_type like 'enum(%' or column_type like 'set(%') [pat-name]
DEBUG - select routine_name, routine_type, dtd_identifier, routine_body, routine_definition, is_deterministic LIKE 'Yes' as is_deterministic, sql_data_access, security_type, sql_mode, routine_comment from information_schema.routines where routine_schema=? [pat-name]
DEBUG - select specific_name, parameter_name, dtd_identifier, parameter_mode from information_schema.parameters where specific_schema=? and ordinal_position != 0 order by ordinal_position [pat-name]
(0sec)
Connecting relationships.....DEBUG - Adding foreign key constraint 'fk_Patient_address_Patient_MID1' to pat-name.patient_address
.DEBUG - Adding foreign key constraint 'fk_Patient_name_Patient_MID1' to pat-name.patient_name
.DEBUG - Adding foreign key constraint 'fk_Phone_no_Patient_MID2' to pat-name.phone_no
(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
WARN  - Failed to query Graphviz version using 'dot -V'
java.io.IOException: Cannot run program "dot": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at org.schemaspy.output.diagram.graphviz.GraphvizDot.initVersion(GraphvizDot.java:75)
        at org.schemaspy.output.diagram.graphviz.GraphvizDot.<init>(GraphvizDot.java:61)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:326)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 19 common frames omitted
INFO  - Graphviz rendered set to ''
..ERROR - RelationShipDiagramError
org.schemaspy.output.OutputException: Failed to produce diagram for: outputD\diagrams\summary\relationships.real.compact.dot
        at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateSummaryDiagrams(MustacheSummaryDiagramFactory.java:91)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:351)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate summary diagram
        at org.schemaspy.output.diagram.DiagramFactory.generateSummaryDiagram(DiagramFactory.java:81)
        at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateSummaryDiagram(MustacheDiagramFactory.java:49)
        at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateSummaryDiagrams(MustacheSummaryDiagramFactory.java:87)
        ... 14 common frames omitted
Caused by: org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version
        at org.schemaspy.output.diagram.graphviz.GraphvizDot.generateDiagram(GraphvizDot.java:193)
        at org.schemaspy.output.diagram.DiagramFactory.generateSummaryDiagram(DiagramFactory.java:78)
        ... 16 common frames omitted
ERROR - RelationShipDiagramError
org.schemaspy.output.OutputException: Failed to produce diagram for: outputD\diagrams\summary\relationships.real.large.dot
        at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateRealLarge(MustacheSummaryDiagramFactory.java:125)
        at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateSummaryDiagrams(MustacheSummaryDiagramFactory.java:94)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:351)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate summary diagram
        at org.schemaspy.output.diagram.DiagramFactory.generateSummaryDiagram(DiagramFactory.java:81)
        at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateSummaryDiagram(MustacheDiagramFactory.java:49)
        at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateRealLarge(MustacheSummaryDiagramFactory.java:120)
        ... 15 common frames omitted
Caused by: org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version
        at org.schemaspy.output.diagram.graphviz.GraphvizDot.generateDiagram(GraphvizDot.java:193)
        at org.schemaspy.output.diagram.DiagramFactory.generateSummaryDiagram(DiagramFactory.java:78)
        ... 17 common frames omitted
......(8sec)
Writing/diagramming detailsINFO  - Completed summary in 8 seconds
INFO  - Writing/diagramming details
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate Table diagram
        at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:71)
        at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram(MustacheDiagramFactory.java:44)
        at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams(MustacheTableDiagramFactory.java:80)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:426)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
Caused by: org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version
        at org.schemaspy.output.diagram.graphviz.GraphvizDot.generateDiagram(GraphvizDot.java:193)
        at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:68)
        ... 16 more

**Comment by npetzall** [comment]
Two options

1, install graphviz and either add bin folder to path or use `-gv` option to specify path to dot.exe

2, add `-vizjs` to commandline to use embedded viz.js to render diagrams.

You could probably remove `-debug` unless you get an error with bad description.

**Comment by milostrugis** [comment]
This is my final command:
C:\Users\xxxx\Desktop\New folder>java -jar schemaspy-6.1.0.jar -t mysql -dp mysql-connector-java-8.0.19.jar -db pat-name -gv C:/prog/bin/gvedit.exe -host 127.0.0.1:3306 -u root -p xxxx -o outputDir1 -cat pat-name -s pat-name -vizjs

and the output has no error messages :)

Great thanky for your super fast help!!!!

**Comment by npetzall** [comment]
I think `-vizjs` supersedes `-gv` so it's not needed.

Glad I could help.
