### ISSUE TITLE
Informix schema unavailable

### ISSUE THREAD

**Issue by michoudu13820** [schemaspy/schemaspy#644]
I am running schemaSpy on an Informix database, and I'm providing all the information but schemaSpy can not find the schema

## Expected Behavior
Running the command : 
`java -jar .\schemaspy-6.1.0.jar -configFile .\SIRHEN_Informix.properties -debug`
and expecting it goes well with the generation

## Current Behavior
When I'm running the command, there is a null pointer (cf log after), and the log says the schema 'agora'  isn't found but 3 lines after the log says that there are 2 schemas available, and one of them is 'agora'

## Possible Solution
I tried to use the command with -noschema but still not working...

## Steps to Reproduce (for bugs)

- Properties file : `

schemaspy.t=informix 
schemaspy.dp=C:\Schema_Spy_6\drivers\ifxjdbc.jar 
schemaspy.host= 
schemaspy.port=2222 
schemaspy.server=ifx_se 
schemaspy.db= 
schemaspy.o=C:\Schema_Spy_6\AnalyseSch\Informix\Agora 
schemaspy.s=agora 
schemaspy.cat=%`

- Launch the command : `java -jar .\schemaspy-6.1.0.jar -configFile .\SIRHEN_Informix.properties -debug'

- ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.1.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0 on LFR037210 with PID 55304 (C:\Schema_Spy_6\schemaspy-6.1.0.jar started by matmiche in C:\Schema_Spy_6)
INFO  - The following profiles are active: default
INFO  - Found configuration file: .\SIRHEN_Informix.properties
INFO  - Started Main in 1.359 seconds (JVM running for 1.754)
DEBUG - Debug enabled
INFO  - Loaded configuration from .\SIRHEN_Informix.properties
INFO  - Starting schema analysis
DEBUG - Resolving dbType: informix ->
        /C:/Schema_Spy_6/schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/informix.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'dbdb2int01.in.ac-aix-marseille.fr:2222' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: '/appli/agora/base/epp' description: 'database name'
DEBUG - DbSpecificOption name: 'server' value: 'ifx_se' description: 'database server'
DEBUG - supportsSchemasInTableDefinitions: true
DEBUG - supportsCatalogsInTableDefinitions: false
INFO  - Connected to INFORMIX-SQL - 7.24.UC5
INFO  - Gathering schema details
Gathering schema details...(2sec)
Connecting relationships...WARN  - No tables or views were found in schema 'agora'.
ERROR - The schema 'agora' could not be read/found, schema is specified using the -s option.Make sure user 'agora' has the correct privileges to read the schema.Also not that schema names are usually case sensitive.
INFO  - Available schemas(Some of these may be user or system schemas):
agora
informix
DEBUG - Including schema agora             : matches + ".*" and contains tables
DEBUG - Including schema informix          : matches + ".*" and contains tables
INFO  - Schemas with tables/views visible to 'agora':
agora
informix
WARN  - Empty schema
org.schemaspy.model.EmptySchemaException: null
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:255)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

## Context

* Database type (e.g. MySQL): Informix 7.24
* Full command including arguments how you run SchemaSpy:

## Your Environment

Can you help me please because I really have no idea.

**Comment by Kamyabnz** [comment]
Hello @michoudu13820 , well have you tried '-all' Argument ? first to see if you get any results ? it should create a multipage output.

schemaspy.t=informix
schemaspy.dp=C:\Schema_Spy_6\drivers\ifxjdbc.jar
schemaspy.host=
schemaspy.port=2222
schemaspy.server=ifx_se
schemaspy.db=
schemaspy.o=C:\Schema_Spy_6\AnalyseSch\Informix\Agora

and your runtime arg: 'java -jar .\schemaspy-6.1.0.jar -configFile .\SIRHEN_Informix.properties -debug -all'

where is your username and password ? 

Note:  Informix servers are a bit tricky, catalog and schema is the way around in Informix DB's

**Comment by michoudu13820** [comment]
Hi @Kamyabnz ,

Thanks for your reply, I deleted the username and password but I have those fields in my properties file.
I tried tu run to command you gave me and logs are much relevant. You might be right and it could be a difference between catalog or schema or some thing like that...  Because it says "ERROR - The schema exists in the database, but the user you specified 'agora'might not have rights to read its contents. ".  It's weird because when it's the credidentials I use to connect to my dB with a database visualizer.

Full log : 
PS C:\Schema_Spy_6> java -jar .\schemaspy-6.1.0.jar -configFile .\SIRHEN_Informix.properties -debug -all
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.1.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0 on LFR037210 with PID 33392 (C:\Schema_Spy_6\schemaspy-6.1.0.jar started by matmiche in C:\Schema_Spy_6)
INFO  - The following profiles are active: default
INFO  - Found configuration file: .\SIRHEN_Informix.properties
INFO  - Started Main in 1.255 seconds (JVM running for 1.753)
DEBUG - Debug enabled
INFO  - Loaded configuration from .\SIRHEN_Informix.properties
DEBUG - Resolving dbType: informix ->
        /C:/Schema_Spy_6/schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/informix.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'xxxxxxxxxxx' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: xxxxxxx' description: 'database name'
DEBUG - DbSpecificOption name: 'server' value: 'ifx_se' description: 'database server'
INFO  - Analyzing schemas that match regular expression '.*'. (use -schemaSpec on command line or in .properties to exclude other schemas)
DEBUG - Including schema agora             : matches + ".*" and contains tables
DEBUG - Including schema informix          : matches + ".*" and contains tables
INFO  - Analyzing schemas:
agora
informix
INFO  - Analyzing agora
INFO  - Starting schema analysis
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'dbdb2int01.in.ac-aix-marseille.fr:2222' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'xxxxxx' description: 'database name'
DEBUG - DbSpecificOption name: 'server' value: 'ifx_se' description: 'database server'
DEBUG - supportsSchemasInTableDefinitions: true
DEBUG - supportsCatalogsInTableDefinitions: false
INFO  - Connected to INFORMIX-SQL - 7.24.UC5
INFO  - Gathering schema details
Gathering schema details...(2sec)
Connecting relationships...WARN  - No tables or views were found in schema 'agora             '.
ERROR - The schema exists in the database, but the user you specified 'agora'might not have rights to read its contents.
ERROR - Another possibility is that the regular expression that you specified for what to include (via -i) didn't match any tables.
(2sec)
Writing/graphing summary.INFO  - Gathered schema details in 2 seconds
INFO  - Writing/graphing summary
INFO  - Graphviz rendered set to ''
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.nio.file.InvalidPathException: Trailing char < > at index 59: C:\Schema_Spy_6\AnalyseSch\Informix\Agora\agora
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:191)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.io.File.toPath(File.java:2234)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:328)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
        at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:176)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:118)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more

**Comment by npetzall** [comment]
Could you check that the value of  `schemaspy.o` in your config doesn't contain any trailing spaces. I've implemented trim at some point but need to check.

**Comment by michoudu13820** [comment]
No, I checked, not only schemaspy.o but all fields  and  I don't have any trailing spaces

**Comment by Kamyabnz** [comment]
How you found any clues ? Has your problem been fixed or are you still stuck ? @michoudu13820

**Comment by michoudu13820** [comment]
Yes I still stuck... I found any clues by checking trailing spaces with Notepad++, do you have a better solution ? 
Thank's 👍

**Comment by npetzall** [comment]
The row that has a problem in SchemaSpy seems to be from the following: `outputDir.toPath()` that's why I asked about the `schemaspy.o` row.  But I realize now that since it's running from `-all` it will contain the schema name, that might be invalid...
I'm gonna see if I can implement the same fix I've done for table names to the schema name it will probably look horrible on the filesystem, but it might work.

**Comment by npetzall** [comment]
So to explain further the schema/table name might not be `agora` but `agora ` where the last character in the name could be something that isn't a visible character.

**Comment by npetzall** [comment]
So try a second attempt at single schema just add `"` around the agora name so you get the trailing space.
```
schemaspy.t=informix
schemaspy.dp=C:\Schema_Spy_6\drivers\ifxjdbc.jar
schemaspy.host=
schemaspy.port=2222
schemaspy.server=ifx_se
schemaspy.db=
schemaspy.o=C:\Schema_Spy_6\AnalyseSch\Informix\Agora
schemaspy.s="agora "
schemaspy.cat=%`
```
Launch the command : `java -jar .\schemaspy-6.1.0.jar -configFile .\SIRHEN_Informix.properties -debug`

**Comment by michoudu13820** [comment]
Thanks for your answers, I've tried what you said. It doesn't work, do I have to dowload the latest version of schemaSpy, or the "correction" with ` "` is allready present in 6.1.0 ?


here is the log : 
`DEBUG - supportsSchemasInTableDefinitions: true
DEBUG - supportsCatalogsInTableDefinitions: false
INFO  - Connected to INFORMIX-SQL - 7.24.UC5
INFO  - Gathering schema details
Gathering schema details...(70sec)
Connecting relationships...WARN  - No tables or views were found in schema 'agora '.
ERROR - The schema 'agora ' could not be read/found, schema is specified using the -s option.Make sure user 'agora' has the correct privileges to read the schema.Also not that schema names are usually case sensitive.
INFO  - Available schemas(Some of these may be user or system schemas):
agora
informix`

**Comment by npetzall** [comment]
I haven't had the time to finish the name handling, it's almost done. I'll try to get some time now over the holiday.

There might be a bug there also regarding the `"` it seems that they are preserved in properties I think they are removed on commandline and thought they had the same handling in properties config. I'll have a look at that also. But I might be wrong in both instances. So I'll add tests for both and correct the behavior.

**Comment by npetzall** [comment]
I've done the filename handling in #668 also added `'` around schema names when listed so any potentially hidden characters are "indicated".

That will only fix the filename issue but not the 
> WARN - No tables or views were found in schema 'agora '.

So if you download a new snapshot the schema name will be surrounded by `'` but now I sort of realize that it's not done for the "available schemas". So that should be added. (will be available in minutes, building right now)

Regarding rights we got some help in #261 

If you have the create statement for the database that would help. But I'm starting to wonder about the versions the database is 7.24 what version is the jdbc driver?

**Comment by michoudu13820** [comment]
Ok thanks for your help.

Unfortunatly I do not have the create statement for the database. It's a very old database (as you would have guessed with Informix), it's around a 20/30 years database... 
I'm using the jdbc driver I'm using to connect to my database via a database editor (DBeaver). Tried to find a web page with jdbc driver to use but haven't figured it out, in order to use the correct jdbc driver and try it out. Do you have a page for that ? 


I've used the latest snapshot and it seems working, and the schema name was 'agora             ' regarding the logs. It reminds me a problem we had during development, in the database they are using char instead of varchar... so all field that aren't used are blank spaces...

`INFO  - Analyzing schemas:
'agora             '
'informix          '
INFO  - Analyzing 'agora             '`

And it seems working but an other exception, but logs are WARN so is it important ? 
`INFO  - Analyzing 'agora             '
INFO  - Starting schema analysis
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'dbdb2int01.in.ac-aix-marseille.fr:2222' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: '/appli/agora/base/epp' description: 'database name'
DEBUG - DbSpecificOption name: 'server' value: 'ifx_se' description: 'database server'
DEBUG - supportsSchemasInTableDefinitions: true
DEBUG - supportsCatalogsInTableDefinitions: false
INFO  - Connected to INFORMIX-SQL - 7.24.UC5
INFO  - Gathering schema details
Gathering schema details...DEBUG - select t.tabname as table_name, c.constrname as constraint_name, k.checktext as text from sysconstraints c,syschecks k,systables t where c.constrid = k.constrid and c.tabid = t.tabid and c.constrtype = 'C' and k.type = 'T' order by k.seqno []
WARN  - Failed to retrieve check constraints using SQL 'select t.tabname as table_name, c.constrname as constraint_name, k.checktext as text from sysconstraints c,syschecks k,systables t where c.constrid = k.constrid and c.tabid = t.tabid and c.constrtype = 'C' and k.type = 'T' order by k.seqno'
java.sql.SQLException: ORDER BY column (seqno) must be in SELECT list.
        at com.informix.jdbc.IfxSqli.a(IfxSqli.java:3204)
        at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3518)
        at com.informix.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2353)
        at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2269)
        at com.informix.jdbc.IfxSqli.executePrepare(IfxSqli.java:1153)
        at com.informix.jdbc.IfxPreparedStatement.e(IfxPreparedStatement.java:318)
        at com.informix.jdbc.IfxPreparedStatement.a(IfxPreparedStatement.java:298)
        at com.informix.jdbc.IfxPreparedStatement.<init>(IfxPreparedStatement.java:168)
        at com.informix.jdbc.IfxSqliConnect.h(IfxSqliConnect.java:5918)
        at com.informix.jdbc.IfxSqliConnect.prepareStatement(IfxSqliConnect.java:1999)
        at org.schemaspy.input.dbms.service.SqlService.prepareStatement(SqlService.java:134)
        at org.schemaspy.input.dbms.service.DatabaseService.initCheckConstraints(DatabaseService.java:524)
        at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(DatabaseService.java:97)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:246)
        at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:176)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:118)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.sql.SQLException: null
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:373)
        at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3523)
        ... 25 common frames omitted
DEBUG - SELECT p.procname || '(' || ifx_param_types(p.procid) || ')' AS routine_name, case p.isproc when "f" then "Function" when "t" then "Procedure" end as routine_type, ifx_ret_types(p.procid) as dtd_identifier, l.langname as routine_body, b.data as routine_definition, b.seqno, 'N/A' as sql_data_access, case LOWER (p.mode) when "d" then "DBA" when "o" then "Owner" when "p" then "Protected" when "r" then "Restricted" when "t" then "trigger" end as security_type, p.variant as is_deterministic, "N/A" as routine_comment from sysprocedures p join sysroutinelangs l on p.langid = l.langid join sysprocbody b on p.procid = b.procid and b.datakey = 'T' order by p.procid, b.seqno []
WARN  - Failed to retrieve stored procedure/function details using sql 'SELECT p.procname || '(' || ifx_param_types(p.procid) || ')' AS routine_name, case p.isproc when "f" then "Function" when "t" then "Procedure" end as routine_type, ifx_ret_types(p.procid) as dtd_identifier, l.langname as routine_body, b.data as routine_definition, b.seqno, 'N/A' as sql_data_access, case LOWER (p.mode) when "d" then "DBA" when "o" then "Owner" when "p" then "Protected" when "r" then "Restricted" when "t" then "trigger" end as security_type, p.variant as is_deterministic, "N/A" as routine_comment from sysprocedures p join sysroutinelangs l on p.langid = l.langid join sysprocbody b on p.procid = b.procid and b.datakey = 'T' order by p.procid, b.seqno'
java.sql.SQLException: A syntax error has occurred.
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:373)
        at com.informix.jdbc.IfxSqli.a(IfxSqli.java:3208)
        at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3518)
        at com.informix.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2353)
        at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2269)
        at com.informix.jdbc.IfxSqli.executePrepare(IfxSqli.java:1153)
        at com.informix.jdbc.IfxPreparedStatement.e(IfxPreparedStatement.java:318)
        at com.informix.jdbc.IfxPreparedStatement.a(IfxPreparedStatement.java:298)
        at com.informix.jdbc.IfxPreparedStatement.<init>(IfxPreparedStatement.java:168)
        at com.informix.jdbc.IfxSqliConnect.h(IfxSqliConnect.java:5918)
        at com.informix.jdbc.IfxSqliConnect.prepareStatement(IfxSqliConnect.java:1999)
        at org.schemaspy.input.dbms.service.SqlService.prepareStatement(SqlService.java:134)
        at org.schemaspy.input.dbms.service.RoutineService.initRoutines(RoutineService.java:72)
        at org.schemaspy.input.dbms.service.RoutineService.gatherRoutines(RoutineService.java:44)
        at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(DatabaseService.java:105)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:246)
        at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:176)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:118)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.sql.SQLException: null
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:373)
        at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3523)
        ... 26 common frames omitted
DEBUG - select p.procname || '(' || ifx_param_types(p.procid) || ')' as specific_name, c.paramname as parameter_name, CASE WHEN MOD(c.paramtype,256)=0 THEN 'CHAR' WHEN MOD(c.paramtype,256)=1 THEN 'SMALLINT' WHEN MOD(c.paramtype,256)=2 THEN 'INTEGER' WHEN MOD(c.paramtype,256)=3 THEN 'FLOAT' WHEN MOD(c.paramtype,256)=4 THEN 'SMALLFLOAT' WHEN MOD(c.paramtype,256)=5 THEN 'DECIMAL' WHEN MOD(c.paramtype,256)=6 THEN 'SERIAL' WHEN MOD(c.paramtype,256)=7 THEN 'DATE' WHEN MOD(c.paramtype,256)=8 THEN 'MONEY' WHEN MOD(c.paramtype,256)=9 THEN 'NULL' WHEN MOD(c.paramtype,256)=10 THEN 'DATETIME' WHEN MOD(c.paramtype,256)=11 THEN 'BYTE' WHEN MOD(c.paramtype,256)=12 THEN 'TEXT' WHEN MOD(c.paramtype,256)=13 THEN 'VARCHAR' WHEN MOD(c.paramtype,256)=14 THEN 'INTERVAL' WHEN MOD(c.paramtype,256)=15 THEN 'NCHAR' WHEN MOD(c.paramtype,256)=16 THEN 'NVARCHAR' WHEN MOD(c.paramtype,256)=17 THEN 'INT8' WHEN MOD(c.paramtype,256)=18 THEN 'SERIAL8' WHEN MOD(c.paramtype,256)=19 THEN 'SET' WHEN MOD(c.paramtype,256)=20 THEN 'MULTISET' WHEN MOD(c.paramtype,256)=21 THEN 'LIST' WHEN MOD(c.paramtype,256)=22 THEN 'ROW (unnamed)' WHEN MOD(c.paramtype,256)=23 THEN 'COLLECTION' WHEN MOD(c.paramtype,256)=40 THEN 'LVARCHAR fixed-length opaque types' WHEN MOD(c.paramtype,256)=41 THEN 'BLOB, BOOLEAN, CLOB variable-length opaque types' WHEN MOD(c.paramtype,256)=43 THEN 'LVARCHAR (client-side only)' WHEN MOD(c.paramtype,256)=45 THEN 'BOOLEAN' WHEN MOD(c.paramtype,256)=52 THEN 'BIGINT' WHEN MOD(c.paramtype,256)=53 THEN 'BIGSERIAL' WHEN MOD(c.paramtype,256)=2061 THEN 'IDSSECURITYLABEL' WHEN MOD(c.paramtype,256)=4118 THEN 'ROW (named)' ELSE TO_CHAR(c.paramtype) END AS dtd_identifier, case c.paramattr when 0 then "Unknown" when 1 then "INPUT" when 2 then "INOUT" when 3 then "Multi Return" when 4 then "OUT" when 5 then "RETURN" end as parameter_mode from sysprocedures p join sysproccolumns c on p.procid = c.procid order by p.procid, c.paramid []
WARN  - Failed to retrieve stored procedure/function details using SQL 'select p.procname || '(' || ifx_param_types(p.procid) || ')' as specific_name, c.paramname as parameter_name, CASE WHEN MOD(c.paramtype,256)=0 THEN 'CHAR' WHEN MOD(c.paramtype,256)=1 THEN 'SMALLINT' WHEN MOD(c.paramtype,256)=2 THEN 'INTEGER' WHEN MOD(c.paramtype,256)=3 THEN 'FLOAT' WHEN MOD(c.paramtype,256)=4 THEN 'SMALLFLOAT' WHEN MOD(c.paramtype,256)=5 THEN 'DECIMAL' WHEN MOD(c.paramtype,256)=6 THEN 'SERIAL' WHEN MOD(c.paramtype,256)=7 THEN 'DATE' WHEN MOD(c.paramtype,256)=8 THEN 'MONEY' WHEN MOD(c.paramtype,256)=9 THEN 'NULL' WHEN MOD(c.paramtype,256)=10 THEN 'DATETIME' WHEN MOD(c.paramtype,256)=11 THEN 'BYTE' WHEN MOD(c.paramtype,256)=12 THEN 'TEXT' WHEN MOD(c.paramtype,256)=13 THEN 'VARCHAR' WHEN MOD(c.paramtype,256)=14 THEN 'INTERVAL' WHEN MOD(c.paramtype,256)=15 THEN 'NCHAR' WHEN MOD(c.paramtype,256)=16 THEN 'NVARCHAR' WHEN MOD(c.paramtype,256)=17 THEN 'INT8' WHEN MOD(c.paramtype,256)=18 THEN 'SERIAL8' WHEN MOD(c.paramtype,256)=19 THEN 'SET' WHEN MOD(c.paramtype,256)=20 THEN 'MULTISET' WHEN MOD(c.paramtype,256)=21 THEN 'LIST' WHEN MOD(c.paramtype,256)=22 THEN 'ROW (unnamed)' WHEN MOD(c.paramtype,256)=23 THEN 'COLLECTION' WHEN MOD(c.paramtype,256)=40 THEN 'LVARCHAR fixed-length opaque types' WHEN MOD(c.paramtype,256)=41 THEN 'BLOB, BOOLEAN, CLOB variable-length opaque types' WHEN MOD(c.paramtype,256)=43 THEN 'LVARCHAR (client-side only)' WHEN MOD(c.paramtype,256)=45 THEN 'BOOLEAN' WHEN MOD(c.paramtype,256)=52 THEN 'BIGINT' WHEN MOD(c.paramtype,256)=53 THEN 'BIGSERIAL' WHEN MOD(c.paramtype,256)=2061 THEN 'IDSSECURITYLABEL' WHEN MOD(c.paramtype,256)=4118 THEN 'ROW (named)' ELSE TO_CHAR(c.paramtype) END AS dtd_identifier, case c.paramattr when 0 then "Unknown" when 1 then "INPUT" when 2 then "INOUT" when 3 then "Multi Return" when 4 then "OUT" when 5 then "RETURN" end as parameter_mode from sysprocedures p join sysproccolumns c on p.procid = c.procid order by p.procid, c.paramid'
java.sql.SQLException: A syntax error has occurred.
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:373)
        at com.informix.jdbc.IfxSqli.a(IfxSqli.java:3208)
        at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3518)
        at com.informix.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2353)
        at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2269)
        at com.informix.jdbc.IfxSqli.executePrepare(IfxSqli.java:1153)
        at com.informix.jdbc.IfxPreparedStatement.e(IfxPreparedStatement.java:318)
        at com.informix.jdbc.IfxPreparedStatement.a(IfxPreparedStatement.java:298)
        at com.informix.jdbc.IfxPreparedStatement.<init>(IfxPreparedStatement.java:168)
        at com.informix.jdbc.IfxSqliConnect.h(IfxSqliConnect.java:5918)
        at com.informix.jdbc.IfxSqliConnect.prepareStatement(IfxSqliConnect.java:1999)
        at org.schemaspy.input.dbms.service.SqlService.prepareStatement(SqlService.java:134)
        at org.schemaspy.input.dbms.service.RoutineService.initRoutineParameters(RoutineService.java:108)
        at org.schemaspy.input.dbms.service.RoutineService.gatherRoutines(RoutineService.java:45)
        at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(DatabaseService.java:105)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:246)
        at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:176)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:118)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.sql.SQLException: null
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:373)
        at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3523)
        ... 26 common frames omitted
(74sec)
Connecting relationships...WARN  - No tables or views were found in schema 'agora             '.
ERROR - The schema exists in the database, but the user you specified 'agora'might not have rights to read its contents.
ERROR - Another possibility is that the regular expression that you specified for what to include (via -i) didn't match any tables.
(69sec)
Writing/graphing summary.INFO  - Gathered schema details in 69 seconds`

**Comment by eeealexxx** [comment]
I hade same issue. 

```
WARN  - Empty schema
org.schemaspy.model.EmptySchemaException: null
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:257)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:124)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```
And all solved when I added it to the bigquery.properties next parameter:

`schemaspy.s=dataset-name`
