### ISSUE TITLE
"-loadjars" not works

### ISSUE THREAD

**Issue by MikePryadko** [schemaspy/schemaspy#672]
```
$ java -jar schemaspy-6.1.0.jar -t pgsql -s public-host {real_IP} -db {real_DB_name} -u {my_real_user} -p {my_real_pass} -o ~/postgres/spy/ -loadjars
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.1.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0 on bobik with PID 31168 (/home/mike/Downloads/apps/schemaspy-6.1.0.jar started by mike in /home/mike/Downloads/apps)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.741 seconds (JVM running for 2.293)
INFO  - Starting schema analysis
ERROR - Bad config
java.lang.IndexOutOfBoundsException: Index 8 out of bounds for length 8
INFO  - StackTraces have been omitted, use `-debug` when executing SchemaSpy to see them
```
then...
```
$ java -jar schemaspy-6.1.0.jar -t pgsql -s public -host {real_IP} -db {real_DB_name} -u {my_real_user} -p {my_real_pass} -o ~/postgres/spy/ -loadjars -debug
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.1.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0 on bobik with PID 31654 (/home/mike/Downloads/apps/schemaspy-6.1.0.jar started by mike in /home/mike/Downloads/apps)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.867 seconds (JVM running for 2.497)
DEBUG - Debug enabled
INFO  - Starting schema analysis
DEBUG - Resolving dbType: pgsql ->
	schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/pgsql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'postgres' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'kmdb' description: 'database name'
DEBUG - Unable to find driverClass 'org.postgresql.Driver'
WARN  - Connection Failure
org.schemaspy.input.dbms.exceptions.ConnectionFailure: Failed to connect to database URL [jdbc:postgresql://postgres/kmdb] Failed to create any of 'org.postgresql.Driver' driver from driverPath '/org/schemaspy/drivers/postgresql-9.4.1208.jre6.jar' with sibling jars no.
Resulting in classpath: empty
There were missing paths in driverPath:
	/org/schemaspy/drivers/postgresql-9.4.1208.jre6.jar
Use commandline option '-dp' to specify driver location.
If you need to load sibling jars used '-loadjars'
	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:101)
	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:75)
	at org.schemaspy.input.dbms.service.SqlService.connect(SqlService.java:70)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:220)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.input.dbms.exceptions.ConnectionFailure: Failed to create any of 'org.postgresql.Driver' driver from driverPath '/org/schemaspy/drivers/postgresql-9.4.1208.jre6.jar' with sibling jars no.
Resulting in classpath: empty
There were missing paths in driverPath:
	/org/schemaspy/drivers/postgresql-9.4.1208.jre6.jar
Use commandline option '-dp' to specify driver location.
If you need to load sibling jars used '-loadjars'
	at org.schemaspy.input.dbms.DbDriverLoader.getDriver(DbDriverLoader.java:147)
	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:93)
	... 15 common frames omitted
```
I write `-loadjars` but application still ask me for that

so.. when I specify external driver all works fine

P.S. My system:
```
$ lsb_release -d
Description:	Ubuntu 18.04.4 LTS
$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
$ uname -r
5.3.0-51-generic
```

**Comment by npetzall** [comment]
Hi, you still need to use `-dp`. -loadjars has become obsololet. If `-dp` is a folder it will add the content of that folder.

-loadjars would load jars that are siblings to the jar specified by `-dp`

So if the jar is located in the same folder as schemaspy-jar. It should work with `-dp [name of the driver jar file]`
