### ISSUE TITLE
documentation (installation or Get Started) - add some information about required drivers

### ISSUE THREAD

**Issue by aisbergde** [schemaspy/schemaspy#674]
## Current Behavior

After installing and creating a schemaspy.properties and executing the program by double click the output folder is empty.

If the command is executed in the command line it gets clear that an jdbc driver is required. 

## Possible Solution

Write a little bit more in the "Get started" or "Installation" section of the documentation. Or add a new section in the documentation with a little bit more information which drivers are recommended to be used. 

## Context

Imagine that the user could be a database professional but not a Java developer. 

For example: I never programmed something in Java and I will never do. I used an JDBC driver only very seldom in some projects. Or even not me, but there have been Java developers and they used the drivers.

* Database type (e.g. MySQL): Microsoft SQL Server
* Database driver version (is you use a special one): I will try "sqljdbc_8.2.2.0_deu" or "sqljdbc_8.2.2.0_enu"

## Your Environment

* Version used: 6.1.0
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10): Windows 10
* Java version: I never cared about :-) 1.8.0_231

**Comment by npetzall** [comment]
Thanks for the feedback. When you develop software you get blind to what is commonly know and what's not. We will try to update it when we get the time.

**Comment by aisbergde** [comment]
I am really not able to connect to SQL Server, I downloaded several drivers and tried several things:

```
schemaspy.dp="C:\Program Files\Microsoft JDBC Driver 8.2 for SQL Server\sqljdbc_8.2\enu"
# schemaspy.dp="C:\Program Files\Microsoft JDBC Driver 7.4 for SQL Server\sqljdbc_7.4\enu"
# schemaspy.dp="C:\Program Files\Microsoft JDBC Driver 7.2 for SQL Server\sqljdbc_7.2\enu"
# schemaspy.dp="C:\Program Files\Microsoft JDBC Driver 7.0 for SQL Server\sqljdbc_7.0\enu"
# schemaspy.dp="C:\Program Files\Microsoft JDBC Driver 6.4 for SQL Server\sqljdbc_6.4\enu"
# schemaspy.dp="C:\Program Files\Microsoft JDBC Driver 6.2 for SQL Server\sqljdbc_6.2\enu"
# schemaspy.dp="C:\Program Files\Microsoft JDBC Driver 6.0 for SQL Server\sqljdbc_6.0\enu"
```

But I only get Connection Failure, or at the beginning I got an error that the driver was compiled with a newer version than supported by JRE

When I use
```
schemaspy.t=mssql
```

and

`schemaspy.dp="C:\Program Files\Microsoft JDBC Driver 8.2 for SQL Server\sqljdbc_8.2\enu"`
or
`schemaspy.dp="C:\Program Files\Microsoft JDBC Driver 7.4 for SQL Server\sqljdbc_7.4\enu"`

I get other errors:

```
INFO  - Starting schema analysis
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.UnsupportedClassVersionError: com/microsoft/sqlserver/jdbc/SQLServerDriver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)

```

This looks better:

`schemaspy.dp="C:\Program Files\Microsoft JDBC Driver 7.2 for SQL Server\sqljdbc_7.2\enu"
`

but still will not connect:

```
WARN  - Connection Failure
Failed to connect to database URL [jdbc:microsoft:sqlserver://localhost;databaseName=PerformanceAnalytics] Cannot connect to 'jdbc:microsoft:sqlserver://localhost;databaseName=PerformanceAnalytics' with driver 'com.microsoft.sqlserver.jdbc.SQLServerDriver,com.microsoft.jdbc.sqlserver.SQLServerDriver'
INFO  - StackTraces have been omitted, use `-debug` when executing SchemaSpy to see them

```

I was looking for small test application to check if it is possible in general to connect to my server, but I can find only find some examples like this one:

https://www.codejava.net/java-se/jdbc/connect-to-microsoft-sql-server-via-jdbc

it is really very hard to start...

**Comment by npetzall** [comment]
Which version of sqlserver are you trying to connect to?

**Comment by npetzall** [comment]
Also are you trying to connect with windows authentication or with sql authentication.

**Comment by aisbergde** [comment]
Microsoft SQL Server 2017 (RTM-CU20) (KB4541283) - 14.0.3294.2 (X64)   Mar 13 2020 14:53:45   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 18363: ) (Hypervisor) 

I used user and password as in the example. I would prefer integrated security, but I did not find an option here how to use:

https://schemaspy.readthedocs.io/en/latest/configuration/commandline.html

There is only this:  
https://schemaspy.readthedocs.io/en/latest/sso.html#singlesignon

But I don't understand this without some investigation. So I tried first to use sql-user and password.

**Comment by npetzall** [comment]
As long as the user/password works with sqlcmd/management studio and sql authentication there shouldn't be an issue.

Since it's a newer sqlserver you can use `-t mssql08` should only effect output and not connection.

In our tests with sqlserver 2017 we use this driver. 

https://github.com/microsoft/mssql-jdbc/releases/download/v6.2.2/mssql-jdbc-6.2.2.jre8.jar

**Comment by aisbergde** [comment]
When I used

`schemaspy.t=mssql08`
I got this error:

```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Fehler beim Herstellen der TCP/IP-Verbindung mit dem Host 'localhost', Port 1433. Fehler: 'Socket operation on nonsocket: configureBlocking. ▄berpr³fen Sie die Verbindungseigenschaften. Stellen Sie sicher, dass eine SQL Server-Instanz auf dem Host ausgef³hrt wird und am Port TCP/IP-Verbindungen akzeptiert. Vergewissern Sie sich, dass am Port keine TCP-Verbindungen durch eine Firewall blockiert werden.'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
        at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:285)
```
That means TCP/IP needs to be enabled!

I enabled TCP/IP and now this combination works:

```
schemaspy.t=mssql08
schemaspy.dp="C:\Program Files\Microsoft JDBC Driver 7.2 for SQL Server\sqljdbc_7.2\enu"
```

but this driver doesn't work with any driver:

`schemaspy.t=mssql`

So we see, it is possible to connect with SSQL, but this is not so easy!

Now I will investigate and explore several options. The demo documenation is promising. Especially the idea of markdown commets. Maybe I will also find how to create all documentation in markdown to add it to some WIKI. 

The first step I did!

**Comment by npetzall** [comment]
Actually mssql does work but you need a really old driver. Microsoft changed the connectionString like 15 years ago. So with mssql 2000 and the driver at the time worked.

From a development point of view you don't want to break things for people that have gotten it to work. So people using mssql shouldn't have to change that's why mssql08 has been added and there's even an newer unreleased mssql19 that's supposed to work with Azure Sql.

There is some planned work to avoid the number in the end by probing which connection string to use and then query the database for version. I personally haven't had the time yet. But the idea is that the would only be `-t mssql` and it would work for most of the versions of mssql.

**Comment by aisbergde** [comment]
Where is the place to ask some question which are not clear in the documentation?

For example:

- is it possible to document relations between objects from different schemas?
- how the "Rails-based naming convention" are implemented, or what exactly is implemented?  
I could adapt my naming conventions to allow automatic detection (normally I have no physical relations but only virtual relations).  
Such automatic could solve my problem how to document relations

**Comment by npetzall** [comment]
Simplest is to create an issue for each question.

And we are open to ideas that are more on the generic side, if something new is required.
