### ISSUE TITLE
Viewing the results

### ISSUE THREAD

**Issue by srulikuk** [schemaspy/schemaspy#688]
This might be a very stupid question but there is nothing about it in readthedocs so please don't hit me ;-)

I successfully created a report using the following command on my ubuntu 18.04 server 
`java -jar schemaspy.jar -t pgsql -host localhost -db dbname -u user -p 'mypass' -dp ./postgresql-42.2.12.jar -vizjs -o my_schema/ -hq`
I scp'd the full dir to my local machine, I cannot find any html files to view the results in my browser.
HOW do I view the results?
(my desktop is ubuntu 18.04)

**Comment by npetzall** [comment]
Well it should be in folder called my_schema next to schemaspy.jar unless you had an error during creation. We have an issue about exit codes. So you might get rerun code 0 but that there were errors.

Schemaspy.jar? Did you rename it or is it old 5.0?

**Comment by srulikuk** [comment]
Using latest version - I renamed it.
This is the output of the command (below is the output of ls -lah)

```
                                              6.1.1-SNAPSHOT

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.1-SNAPSHOT on web with PID 28869 (/root/schemaspy.jar started by root in /root)
INFO  - The following profiles are active: default
INFO  - Started Main in 3.55 seconds (JVM running for 5.17)
INFO  - Starting schema analysis
INFO  - Connected to PostgreSQL - 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)
INFO  - Gathering schema details
Gathering schema details........................................................................................(3sec)
Connecting relationships........................................................................................(3sec)
Writing/graphing summary.INFO  - Gathered schema details in 3 seconds
INFO  - Writing/graphing summary
Warning: Nashorn engine is planned to be removed from a future JDK release
.Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.PropertyHashMap.replaceInList(PropertyHashMap.java:468)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.PropertyHashMap$MapBuilder.replaceProperty(PropertyHashMap.java:805)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.PropertyHashMap.immutableReplace(PropertyHashMap.java:187)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.PropertyMap.replaceProperty(PropertyMap.java:486)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.AccessorProperty.getWiderMap(AccessorProperty.java:562)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.AccessorProperty.getSetter(AccessorProperty.java:618)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.FindProperty.getSetter(FindProperty.java:117)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.SetMethodCreator.createExistingPropertySetter(SetMethodCreator.java:166)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.SetMethodCreator.createSetMethod(SetMethodCreator.java:123)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.SetMethodCreator.createGuardedInvocation(SetMethodCreator.java:84)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptObject.findSetMethod(ScriptObject.java:2238)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1870)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:104)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96)
	at jdk.dynalink/jdk.dynalink.linker.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:161)
	at jdk.dynalink/jdk.dynalink.linker.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:109)
	at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.lambda$getGuardedInvocation$0(LinkerServicesImpl.java:137)
	at jdk.dynalink/jdk.dynalink.LinkerServicesImpl$$Lambda$328/0x000000084037d440.get(Unknown Source)
	at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getWithLookupInternal(LinkerServicesImpl.java:168)
	at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:135)
	at jdk.dynalink/jdk.dynalink.DynamicLinker.relink(DynamicLinker.java:242)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x00000008400aa840.invokeSpecial(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000840361c40.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000840426840.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000840427840.reinvoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000840427c40.guard(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000840426c40.linkToCallSite(LambdaForm$MH)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$147$268435448$\^eval\_.L:22#Module#asm$:split-2(<eval>:34)
	at java.base/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00000008405d2840.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x000000084041bc40.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.Invokers$Holder.linkToCallSite(Invokers$Holder)

```

Output of ls -lah my_schema
```
total 68K
drwxr-xr-x  8 sruli sruli 4.0K May 14 16:03 .
drwxrwxr-x  4 sruli sruli 4.0K May 14 16:44 ..
-rw-r--r--  1 sruli sruli    0 May 14 16:03 anomalies.js
drwxr-xr-x 17 sruli sruli 4.0K May 14 16:03 bower
-rw-r--r--  1 sruli sruli 3.2K May 14 16:03 column.js
-rw-r--r--  1 sruli sruli  380 May 14 16:03 constraint.js
drwxr-xr-x  5 sruli sruli 4.0K May 14 16:03 diagrams
-rw-r--r--  1 sruli sruli 1.4K May 14 16:02 favicon.png
drwxr-xr-x  4 sruli sruli 4.0K May 14 16:03 fonts
drwxr-xr-x  2 sruli sruli 4.0K May 14 16:03 images
-rw-r--r--  1 sruli sruli  229 May 14 16:02 info-html.txt
-rw-r--r--  1 sruli sruli 1.6K May 14 16:03 main.js
-rw-r--r--  1 sruli sruli  410 May 14 16:02 relationships.js
drwxr-xr-x  2 sruli sruli 4.0K May 14 16:03 routines
-rw-r--r--  1 sruli sruli 2.1K May 14 16:03 routines.js
-rw-r--r--  1 sruli sruli 2.5K May 14 16:03 schemaSpy.css
-rw-r--r--  1 sruli sruli 1.6K May 14 16:03 schemaSpy.js
drwxr-xr-x  2 sruli sruli 4.0K May 14 16:03 tables
```

**Comment by npetzall** [comment]
That thing blew up, what version of Java is that? 14? Java 8 should work. Need to look into that, might work with graphviz installed or by using the docker container.

**Comment by srulikuk** [comment]
```
# dpkg -l openjdk*
ii  openjdk-11-jre-headless:amd64                     11.0.7+10-2ubuntu2~18.04      amd64 
```

**Comment by npetzall** [comment]
Some warnings are form Java 11, but the main problem is `java.lang.OutOfMemoryError: Java heap space` which means that the application has run out of memory. Could you try with version 6.1.0. Just had another report about issues with 6.1.1-SNAPHOT. Could be what's causing the out of memory.

**Comment by srulikuk** [comment]
will try and report in ~30 min

**Comment by srulikuk** [comment]
exact same issue with schemaspy-6.1.0.jar, same error and same files in output

**Comment by npetzall** [comment]
Do you have memory restrictions on the host that you run schemaspy?

**Comment by srulikuk** [comment]
its a VM that I am fully in control of the hypervisor (KVM)
```
# free -m
              total        used        free      shared  buff/cache   available
Mem:           1896         343        1373          12         180        1339
Swap:          4095         266        3829

```

**Comment by npetzall** [comment]
You can specify the max heap used by Java. If this is a big database it might be necessary you do this by adding `-Xmx1g` to give it 1 gig of memory.

**Comment by srulikuk** [comment]
Not sure if you are referring to size of structure or records. its 85 tables but in terms of records I hardly started putting in some test data so its very small.

I tried giving it 1GB it ate it all and failed (v6.1.0), I upped the VM to 4GB and gave it 2GB, it took 15 minutes, it ate the full 4GB (double than what i gave it) for half the time and 2gb the other half but SUCCESS!!! (v6.1.1)

Is it normal for it to require that much RAM?

**Comment by npetzall** [comment]
Number of records shouldn't matter. But the -vizjs probably has an impact. I'll do a cpl of test runs to see if and how much of an impact it has.

Vizjs is the nashorn and a Javascript port/compile of graphviz. So jvm probably eats more ram. Probably goes slow due to swap.

**Comment by srulikuk** [comment]
I tried without vizjs and when viewing the results, the "relationships" tab gave an error.
regarding speed, it used the full 4GB of real RAM, I did not check how much SWAP it used.
If you give me a way to send you the result privately you can have a look at the relationships and determine if it's normal for it to use that much resources for that long.

OOOPS just noticed the graph I was looking at is CPU usage, now i dont know the RAM usage

**Comment by srulikuk** [comment]
Too give you an idea of the tables & relationships, I made a screenshot of the relationships.real.compact.svg file https://pasteboard.co/J8n0mzI.png

**Comment by npetzall** [comment]
Yeah, if you run without -vizjs you need to have graphviz installed. Looks pretty komplex. I think I have something similar that I can use to check.
