### ISSUE TITLE
InconsistencyException: Column information from DatabaseMetaData differs from ResultSetMetaData MSSql

### ISSUE THREAD

**Issue by Francoislinkt** [schemaspy/schemaspy#707]
## Expected Behavior
 I would like to run my Mssql db Schema generation

## Current Behavior

` Gathering schema details...Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.input.dbms.service.InconsistencyException: Column information from DatabaseMetaData differs from ResultSetMetaData, expected to find column named: 'Quantite' in ['']
        at org.schemaspy.input.dbms.service.ColumnService.initColumnAutoUpdate(ColumnService.java:149)
        at org.schemaspy.input.dbms.service.ColumnService.gatherColumns(ColumnService.java:46)
        at org.schemaspy.input.dbms.service.TableService.gatheringTableDetails(TableService.java:76)
        at org.schemaspy.input.dbms.service.DatabaseService$TableCreator.createImpl(DatabaseService.java:337)
        at org.schemaspy.input.dbms.service.DatabaseService$TableCreator.create(DatabaseService.java:332)
        at org.schemaspy.input.dbms.service.DatabaseService.initTables(DatabaseService.java:186)
        at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(DatabaseService.java:90)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:246)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more`

## Steps to Reproduce (for bugs)

`java -jar schemaspy-6.1.0.jar -dp sqljdbc4-3.0.jar -t mssql08 -host x.xx.xxx.x -port x -db MyDB -s dbo -u user -p passw -o /home/user/cartographie/Folder`

## Context

* I've tried both jdts and non jdts driver with sqljdbc4-3.0.jar / jtds-1.3.1.jar 
* Full command including arguments how you run SchemaSpy:

## Your Environment
* Version used: schemaSpy v6.1.0
* Operating System and version : centos
* Java version: latest stable

**Comment by Francoislinkt** [comment]
After a deep search. The error was comming from a crappy name in the db. table with [db].[mytable] as name.

**Comment by npetzall** [comment]
@Francoislinkt could you create an example script to create such a table. I would want to handle it better.

**Comment by Francoislinkt** [comment]
Hi 

This kind of table. 


CREATE TABLE "[dbo].[StrangeTableName]" (test int);

Thank's for fast reply ;) And all the work done !

**Comment by npetzall** [comment]
If I understand this right.
It should have been `[dbo].[tableName]` but instead you have something like `[dbo]."[dbo].[tableName]"`

**Comment by Francoislinkt** [comment]
Yes the full table name is "[dbo].[tableName]" And that cause some errors. 

I've deleted the table and everything is back to normal.
