### ISSUE TITLE
Schema spy dies on connecting relationships on MySQL8

### ISSUE THREAD

**Issue by mskempri** [schemaspy/schemaspy#713]
I'm on macOS Catalina, version 10.15.5.

```
java --version
java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
```

schemaspy version 6.1.0
mysql connector version 8.0.20

Trying to create a schema for mysql 8.0.19 on RDS and all efforts die on connecting relationships

`INFO  - Starting Main v6.1.0 on Markellas-MacBook-Pro.local with PID 7517 (/Users/markella.skempri/Downloads/schemaSpyGUI20090302/lib/schemaspy-6.1.0.jar started by markella.skempri in /Users/markella.skempri/Downloads/schemaSpyGUI20090302/lib)
INFO  - The following profiles are active: default
INFO  - Found configuration file: iris_config.cnf
INFO  - Started Main in 2.295 seconds (JVM running for 2.839)
INFO  - Loaded configuration from iris_config.cnf
INFO  - Starting schema analysis
INFO  - Connected to MySQL - 8.0.19
INFO  - Gathering schema details
Gathering schema details................................................................................................................................................................................................(24sec)
Connecting relationships.............Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NullPointerException
	at org.schemaspy.input.dbms.service.TableService.connectForeignKeysRemoteTable(TableService.java:154)
	at org.schemaspy.input.dbms.service.TableService.addRemoteTable(TableService.java:356)
	at org.schemaspy.input.dbms.service.TableService.addRemoteTable(TableService.java:329)
	at org.schemaspy.input.dbms.service.TableService.connectForeignKeys(TableService.java:126)
	at org.schemaspy.input.dbms.service.DatabaseService.connectTables(DatabaseService.java:297)
	at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(DatabaseService.java:110)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:246)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	... 8 more
`
We just upgraded from 5.7 and it worked fine for me - is there any way I can trouble shoot this? I can't see any other issues listed mysql8

**Comment by npetzall** [comment]
I'm a bit out of my depth and I'm also sick at the moment so I have a hard time to keep focus.

But there's a lot going on that I know little to nothing about. RDS, Version 8 and your schema.

So SchemaSpy seems to think that your schema has references to tables in other schemas/catalog, is this true?

I've read in the past that earlier mysql and drivers sort of mixed the schema and catalog and that they might change this. Which I don't have the energy at the moment to look into. But if it has changed it might be causing this issue.

Also implementations might have changed from 6.0.6 driver that relates to DatabaseMetaData, which also could be the cause.
I managed to bump one of our tests from 5.x to 8.0.20 and it worked with an expected error and one unexpected error (however SchamaSpy ran from start to finish, I had to change the testdata which cause it to not match the expected data (expected error), but it failed to read a view definition so something must have changed there(unexpected error))

For some possible good news, there has been a performance issue with Oracle/Oracle driver that made me add a flag to avoid looking for tables that references a tables primary key. Normally this would be found when that table is processed and it's FK are mapped. BUT if you have multiple schemas/catalogs that references each other you need to use `-all` or `-schemas` to find this relationship if you disable the look up which you do by adding `-noexportedkeys`

Hopes this helps for now. I'll take a closer look and try to reproduce on a local mysql 8.0 when I have the time.

**Comment by mskempri** [comment]
Nils, thank you, apologies it took so long to get back to you. I just tried with `-noexportedkeys` and it run to completion. I didn't realise there are other dependencies in that schema, I'll investigate. Let me know if there is anything I can help with this, I'm happy to review logs if they exist.
