### ISSUE TITLE
Abort(1) while generating diagram

### ISSUE THREAD

**Issue by rafaela00castro** [schemaspy/schemaspy#718]
While generating a mysql database using built-in vizjs, the diagram (.svg) of the user table is not generated and an abort(1) error is shown.

## Expected Behavior
Generate `user.1degree.svg` since `user.1degree.dot`is generated.

## Current Behavior
```
DEBUG - Writing table page -> motivo_indeferimento_beneficio
1
1
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate Table diagram
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:71)
	at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram(MustacheDiagramFactory.java:44)
	at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams(MustacheTableDiagramFactory.java:80)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:426)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	... 8 more
Caused by: org.schemaspy.output.diagram.DiagramException: javax.script.ScriptException: abort(1) at Error
	at jsStackTrace (<eval>:27)
	at stackTrace (<eval>:27)
	at abort (<eval>:50)
	at g7 (<eval>:43)
	at wD (<eval>:34)
	at kD (<eval>:34)
	at EE (<eval>:34)
	at gF (<eval>:34)
	at hF (<eval>:34)
	at WB (<eval>:34)
	at Ib (<eval>:33)
	at ccallFunc (<eval>:27)
	at render (<eval>:87)
	at Viz (<eval>:75)
	at <program> (<eval>:1)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information. in <eval> at line number 50 at column number 6466
	at org.schemaspy.output.diagram.vizjs.VizJSDot.generateDiagram(VizJSDot.java:72)
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:68)
	... 16 more
```

## Possible Solution
Instead of aborting the process, schemaspy should skip the generation of the problematic table diagram, proceeding with the generation of other tables

## Steps to Reproduce (for bugs)
1. Execute the command-line presented in context section.

## Context
* Database type: MySQL - 5.7.20
* Database driver version: 6.0.4
* large database: +1000 tables
* user table has 951 children and 10 parents
* Full command including arguments how you run SchemaSpy:
```
java -Xss512M -jar schemaspy-6.1.0.jar - t mysql -dp mysql-connector-java-6.0.4.jar -host host -port port -u myuser -p mypassword -db name_db -s name_db -c catalog -lq -norows -noviews -o ~/output  -noimplied -noexportedkeys -vizjs -debug
```

## Your Environment
* Version used: schemaspy-6.1.0
* Environment name and version: Chrome 84.0.4147.105
* Operating System and version: Linux (Centos 7)
* Java version: 1.8.0_191

**Comment by rafaela00castro** [comment]
I also tried to run the command with suggestion in the stack trace `If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information`, but received `ERROR - The schema 'ASSERTIONS=1' could not be read/found, schema is specified using the -s option.`

**Comment by rafallity** [comment]
Hi, did you manage to find workaround for this issue? I have exact same problem but for mssql, I searched the web for "abort(1) at Error", and this page is the only one I found.

**Comment by npetzall** [comment]
Sorry feel like I've missed this. There two issues. 1, We let an exception bubble way to high it seems and 2, there is an issue either with vizJs or the generated dot-lang file.

If possible this might be too old but there might exist files in ouput/diagrams that ends with `.dot` which I might be able to reproduce the error with.

But when I get the time I'm fix the error handling.

**Comment by rafaela00castro** [comment]
@rafallity meanwhile, I "sacrificed" my problematic table (the one with 900+ children), removing it from the generation process (-I "user"). You can check which table is causing the "abort(1)" error by accessing `YOUR_PROJECT/diagrams/tables`. Find the last generated table (there will be only `.dot` and no `.svg` file for this table.

**Comment by rafallity** [comment]
Thanks @rafaela00castro . I reverted back to old way and generated diagrams with graphviz.
Thanks @npetzall, good luck fixing it.

**Comment by rol1** [comment]
Are there any news here? I'm facing this issue today.

**Comment by npetzall** [comment]
No news, but I've been busy for a long time. Starting to get some time back, so good that you pinged this issue.

I see that it hasn't been clearly stated but. The abort is within vizjs. But might be related to the script engine.

In the latest master build, we have included and specified that nashorn should be used. This means that it should run at least with a newer script engine. But I'll have to see if the vizjs in 6.1 is the latest version, but also see if anyone has continued to work on vizjs since it has been archived.
