### ISSUE TITLE
Issue trying to generate diagram with PostgreSQL

### ISSUE THREAD

**Issue by SergiMP** [schemaspy/schemaspy#719]
Good afternoon,

I am trying to get a database diagram running schemaspy on Windows 10 using  graphviz-2.38-win32

I have run the following command on the terminal:

`java -jar schemaspy-6.1.0.jar -t pgsql -dp C:/Users/smunoz/Downloads postgresql-42.2.14.jar -db investor -host localhost -port 5432 -u postgres -o /c/Users/smunoz -p postgres -s investment_manager -gv C:/Users/smunoz/Downloads/rele
ase/bin/dot.exe`

Which causes the following error:
```
INFO  - Starting Main v6.1.0 on PC-D5060w10e with PID 11768 (C:\Users\smunoz\Downloads\schemaspy-6.1.0.jar started by SMunoz in C:\Users\smunoz\Downloads)
INFO  - The following profiles are active: default
INFO  - Started Main in 0.887 seconds (JVM running for 1.251)
INFO  - Starting schema analysis
INFO  - Connected to PostgreSQL - 12.2
INFO  - Gathering schema details
Gathering schema details...............WARN  - Failed to retrieve stored procedure/function details using sql 'select r.routine_name, case when p.proisagg then 'AGGREGATE' else 'FUNCTION' end as routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body, r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on ns.oid = p.pronamespace and r.routine_name = p.proname left join pg_description d on d.objoid = p.oid where r.routine_schema = :schema'
ERROR: column p.proisagg does not exist
  Hint: Perhaps you meant to reference the column "p.prolang".
  Position: 34
(0sec)
Connecting relationships...............(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
WARN  - Failed to query Graphviz version using 'C:\Users\smunoz\Downloads\release\bin\dot.exe\bin\dot -V'
Cannot run program "C:\Users\smunoz\Downloads\release\bin\dot.exe\bin\dot": CreateProcess error=2, The system cannot find the file specified
INFO  - Graphviz rendered set to ''
..ERROR - RelationShipDiagramError
Failed to produce diagram for: C:\Users\smunoz\diagrams\summary\relationships.real.compact.dot
ERROR - RelationShipDiagramError
Failed to produce diagram for: C:\Users\smunoz\diagrams\summary\relationships.real.large.dot
......(0sec)
Writing/diagramming detailsINFO  - Completed summary in 0 seconds
INFO  - Writing/diagramming details
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate Table diagram
        at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:71)
        at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram(MustacheDiagramFactory.java:44)
        at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams(MustacheTableDiagramFactory.java:80)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:426)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
Caused by: org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version
        at org.schemaspy.output.diagram.graphviz.GraphvizDot.generateDiagram(GraphvizDot.java:193)
        at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:68)
        ... 16 more
```
I initially thought I didn't configured the path properly, but adding the specific path hasn't changed the results. Could somebody give me a hand on this one?

**Comment by npetzall** [comment]
column p.proisagg does not exist see #537 you are probably using a version of pgsql higher or equal to 11. Use `-t pgsql11` instead of `-t pgsql`.

As for graphviz gv should be install dir or home dir for graphviz.

In the output you have `Cannot run program "C:\Users\smunoz\Downloads\release\bin\dot.exe\bin\dot": CreateProcess error=2, The system cannot find the file specified`

So change to `-gv "C:\Users\smunoz\Downloads\release"

Or use the embedded viz.js by adding `-vizjs`

**Comment by SergiMP** [comment]
Thanks a lot!!!

It works now :)

**Comment by NayanKaran** [comment]
JDK version 17 was not working for me.
I had to install JDK 8

**Comment by npetzall** [comment]
@NayanKaran where you using the `-vizjs` Java removed the Javascript engine in Java 15 or 16. So 11 would have worked.
