### ISSUE TITLE
ClassNotFoundException while running schemaspy for Google Big Query

### ISSUE THREAD

**Issue by bhupinder48** [schemaspy/schemaspy#737]
ClassNotFoundException for class **GoogleJsonResponseException** is thrown while running the SchemaSpy for the Google Big Query using Simba JDBC connector for Big Query. Below is the exception log:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoClassDefFoundError: com/google/api/client/googleapis/json/GoogleJsonResponseException
	at com.simba.googlebigquery.googlebigquery.core.BQConnection.connect(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.AbstractDriver.connect(Unknown Source)
```

## Steps to Reproduce (for bugs)
1. Create _bigquery.properties_ file as shown below

```
description=Google Big Query
connectionSpec=jdbc:bigquery://{host}:{port};ProjectId={database};OAuthType=0;OAuthServiceAcctEmail={user};OAuthPvtKeyPath={file_path};
host=https://www.googleapis.com/bigquery/v2
port=443

driver=com.simba.googlebigquery.jdbc42.Driver
driverPath=drivers/GoogleBigQueryJDBC42.jar
```

2. Running the schemaspy command using the [Simba JDBC for Big Query](https://cloud.google.com/bigquery/providers/simba-drivers) jar:
`java  -jar schemaspy-6.1.0.jar -t bigquery -o output -u <Service_Account_User_Id>`

3. Getting the exception even after added the supporting library jars in the classpath

## Context
* Database type: Data Warehouse (Google Big Query)
* Full command including arguments how you run SchemaSpy:
`java  -jar schemaspy-6.1.0.jar -t bigquery -o output -u <Service_Account_User_Id>`

**Comment by npetzall** [comment]
I'm guessing that the driver consist of multiple jars, put driver and supporting jars in a folder.

Add `-dp [path to folder with all the jars]`

**Comment by bhupinder48** [comment]
@npetzall Thanks this worked. I was setting all the jars in the CLASSPATH environment variable.
