### ISSUE TITLE
Failed to connect to database URL [jdbc:mysql://127.0.0.1:6789/xyz] Unknown system variable 'query_cache_size' for MySQL version 8.0.21

### ISSUE THREAD

**Issue by ankit284** [schemaspy/schemaspy#750]
Hi Guys,
I am not able to connect to MySQL 8.0.21 (running on Ubuntu)

Contents of properties file
# type of database. Run with -dbhelp for details
schemaspy.t=mysql
# optional path to alternative jdbc drivers.
schemaspy.dp=E:\\schema-spy\\mysql-connector-java-8.0.23.jar	
# database properties: host, port number, name user, password
schemaspy.host=127.0.0.1
schemaspy.port=6789
schemaspy.db=xyz
schemaspy.u=user
schemaspy.p=user123
# output dir to save generated files
schemaspy.o=E:\\schema-spy\\output_sit
# db scheme for which generate diagrams
schemaspy.s=xyz

I am using below command to generate the documentation. 
java -jar E:\schema-spy\schemaspy-6.1.0.jar -configFile e:\schema-spy\sit_config.properties -dp mysql-connector-java-8.0.23.jar -noexportedkeys -norows -noviews -vizjs 

On the execution of above command, it ends with error of not able to connect to MySQL.

Same configurations & setting works well with MySQL 5.7.33-36-log

**Comment by npetzall** [comment]
Hi, 

Just let me start of by explaining what I've done.
I've launched a mysql 8.0.21 on Windows 10 using Docker(WSL).
`docker run -e "MYSQL_DATABASE=test" -e "MYSQL_PASSWORD=test" -e "MYSQL_USER=test" -e "MYSQL_ROOT_PASSWORD=test" -P --name mysql8 mysql:8.0.21`

I connected using DBBeaver and added some test tables and stuff. More or less what we use when we test schemaspy.

I connected using SchemaSpy-6.1.0.jar using.
`java -jar schemaspy-6.1.0.jar -db test -o mysql8 -u test -p test -t mysql -host localhost -port 49188 -dp ..\.m2\repository\mysql\mysql-connector-java\8.0.23 -s htmlit`

Port is random since I've used `-P` so that must be corrected if you're gonna try it.

I had the driver in my local maven cache so I just pointed towards that.

And it worked so I'm a bit unsure what the problem might be.

I've googled this `Failed to connect to database URL [jdbc:mysql://127.0.0.1:6789/xyz] Unknown system variable 'query_cache_size'` and it's a property that has been removed from MySQL 8. SchemaSpy doesn't supply that configuration. So it might be supplied by the driver or if you're using a custom databasetype, but from your config you shouldn't be unless you have a mysql.properties file in the same directory as the schemaspy-jarfile or user_home.

Just to make sure I've re-downloaded the driver from https://search.maven.org/artifact/mysql/mysql-connector-java/8.0.23/jar maven and tried with that one and it also works.

But it could be some server configuration that isn't present in the docker image supplied by mysql.

With the failure you should have received a hint that information has been omitted could you run with the additional argument `-debug` and supply that after you have masked sensitive information?

**Comment by ankit284** [comment]
Thanks for looking into it. Please see the command and logs printed out in console with debug enabled.

E:\schema-spy>java -jar schemaspy-6.1.0.jar -db schema123 -o mysql8 -u test -p test -t mysql -host localhost -port 6789 -dp E:\schema-spy\mysql-connector-java-8.0.23.jar -debug
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.1.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0 on Notebook683 with PID 18788 (E:\schema-spy\schemaspy-6.1.0.jar started by ankit.singhai in E:\schema-spy)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.241 seconds (JVM running for 1.788)
DEBUG - Debug enabled
INFO  - Starting schema analysis
DEBUG - Resolving dbType: mysql ->
        /E:/schema-spy/schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mysql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'localhost:6789' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'schema123' description: 'database name'
WARN  - Connection Failure
org.schemaspy.input.dbms.exceptions.ConnectionFailure: Failed to connect to database URL [jdbc:mysql://localhost:6789/schema123] Unknown system variable 'query_cache_size'
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:101)
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:75)
        at org.schemaspy.input.dbms.service.SqlService.connect(SqlService.java:70)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:220)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.sql.SQLException: Unknown system variable 'query_cache_size'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:94)
        ... 15 common frames omitted
