### ISSUE TITLE
java.lang.IllegalArgumentException: viz.js

### ISSUE THREAD

**Issue by ugultopu** [schemaspy/schemaspy#753]
- macOS 11.2.3
- openjdk 15.0.2 2021-01-19

In `~/Downloads`:
- `schemaspy-6.1.0.jar`
- `postgresql-42.2.19.jar`
- `schemaspy.properties`

       schemaspy.t=pgsql
       schemaspy.dp=.
       schemaspy.host=localhost
       schemaspy.db=postgres
       schemaspy.u=postgres
       schemaspy.o=schemaspy_out
       schemaspy.vizjs=true
- `schemaspy_out/`

From `~/Downloads`, running `java -jar schemaspy-6.1.0.jar`. Output is:

    $ java -jar schemaspy-6.1.0.jar
    ____       _                          ____
    / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
    \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
    ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
    |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                                |_|    |___/

                                                6.1.0

    SchemaSpy generates an HTML representation of a database schema's relationships.
    SchemaSpy comes with ABSOLUTELY NO WARRANTY.
    SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
    http://www.gnu.org/licenses/

    INFO  - Starting Main v6.1.0 on Mac with PID 76435 (/Users/utku/Downloads/schemaspy-6.1.0.jar started by utku in /Users/utku/Downloads)
    INFO  - The following profiles are active: default
    INFO  - Found configuration file: schemaspy.properties
    INFO  - Started Main in 1.184 seconds (JVM running for 1.635)
    INFO  - Loaded configuration from schemaspy.properties
    INFO  - Starting schema analysis
    INFO  - Connected to PostgreSQL - 13.2
    INFO  - Gathering schema details
    Gathering schema details............................................................WARN  - Failed to retrieve stored procedure/function details using sql 'select r.routine_name, case when p.proisagg then 'AGGREGATE' else 'FUNCTION' end as routine_type, case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, r.external_language as routine_body, r.routine_definition, r.sql_data_access, r.security_type, r.is_deterministic, d.description as routine_comment from information_schema.routines r left join pg_namespace ns on r.routine_schema = ns.nspname left join pg_proc p on ns.oid = p.pronamespace and r.routine_name = p.proname left join pg_description d on d.objoid = p.oid where r.routine_schema = :schema'
    ERROR: column p.proisagg does not exist
    Hint: Perhaps you meant to reference the column "p.prolang".
    Position: 34
    (0sec)
    Connecting relationships............................................................(0sec)
    Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
    INFO  - Writing/graphing summary
    Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
    Caused by: java.lang.IllegalArgumentException: viz.js
        at org.schemaspy.output.diagram.vizjs.VizJSDot.<init>(VizJSDot.java:49)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:324)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
    Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.scriptEngine" is null
        at org.schemaspy.output.diagram.vizjs.VizJSDot.<init>(VizJSDot.java:47)
        ... 14 more
    $

**Comment by npetzall** [comment]
#537

But short answer change

`schemaspy.t=pgsql`

To

`schemaspy.t=pgsql11`

**Comment by mprins** [comment]
> Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.scriptEngine" is null
    at org.schemaspy.output.diagram.vizjs.VizJSDot.<init>(VizJSDot.java:47)

Nashorn (javascript engine) was removed in Java 15, see https://openjdk.java.net/jeps/372

**Comment by npetzall** [comment]
@mprins good catch, bad reading of me.
