### ISSUE TITLE
Help: I can't connect to SQL Server 2019 database (SSL error)

### ISSUE THREAD

**Issue by NilkOne** [schemaspy/schemaspy#828]
Hello,

When I try to connect to SQL Server 2019, I get SSL error.

## Expected Behavior

I would like to use SchemaSpy and success to connect to SQL Server.

## Current Behavior

This is error that I get : 
```
Failed to connect to database URL [jdbc:sqlserver://SRV-DEV-TEST:1433;databaseName=BlazorDB]
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption.
Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target."
ClientConnectionId:98d0b6f4-f3ca-4683-939e-7c0a0fca5931
```

## Steps to Reproduce

1. Run this command line `java -jar .\schemaspy-6.1.0.jar -connprops useSSL\=false`
2. Use this config file schemaspy.properties
```
schemaspy.t=mssql08
schemaspy.dp=mssql-jdbc-10.2.0.jre11.jar
schemaspy.host=SRV-DEV-TEST
schemaspy.port=1433
schemaspy.db=BlazorDB
schemaspy.u=user
schemaspy.p=pwd
schemaspy.o=/doc
```

## My Environment

* Version used: [schemaspy-6.1.0.jar](https://github.com/schemaspy/schemaspy/releases)
* Server version: Microsoft SQL Server 2019 - 15.0.2080.9 (X64)  
* Operating System: Windows 10
* Java version: 11.0.12
* JDBC version : [mssql-jdbc-10.2.0.jre11.jar](https://github.com/microsoft/mssql-jdbc/releases)

## Complete StackTrace

```
INFO  - The following profiles are active: default
INFO  - Found configuration file: schemaspy.properties
INFO  - Started Main in 1.345 seconds (JVM running for 1.871)
DEBUG - Debug enabled
INFO  - Loaded configuration from schemaspy.properties
INFO  - Starting schema analysis
DEBUG - Resolving dbType: mssql08 ->
        /schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql08.properties ->
        /schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql05.properties ->
        /schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'SRV-DEV-TEST:1433' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'BlazorDB' description: 'database name'
WARN  - Connection Failure
org.schemaspy.input.dbms.exceptions.ConnectionFailure: Failed to connect to database URL [jdbc:sqlserver://SRV-DEV-TEST:1433;databaseName=BlazorDB] Le pilote n'a pas pu Útablir de connexion sÚcurisÚe au serveur SQL Server Ó l'aide du chiffrement SSL (Secure Sockets Layer). Erreurá: ½áPKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetá╗. ClientConnectionId:98d0b6f4-f3ca-4683-939e-7c0a0fca5931
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:101)
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:75)
        at org.schemaspy.input.dbms.service.SqlService.connect(SqlService.java:70)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:220)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Le pilote n'a pas pu Útablir de connexion sÚcurisÚe au serveur SQL Server Ó l'aide du chiffrement SSL (Secure Sockets Layer). Erreurá: ½áPKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetá╗. ClientConnectionId:98d0b6f4-f3ca-4683-939e-7c0a0fca5931
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3680)
        at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2113)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3204)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)
        at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:94)
        ... 15 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1426)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1336)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
        at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2021)
        ... 21 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:233)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:110)
        at com.microsoft.sqlserver.jdbc.TDSChannel$HostNameOverrideX509TrustManager.checkServerTrusted(IOBuffer.java:1702)
        at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1510)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        ... 33 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 41 common frames omitted
```

**Comment by npetzall** [comment]
See #633 there is also an option to configure Java to use windows cert store if the sql server is setup with ssl.

**Comment by NilkOne** [comment]
Sorry, I don't know java

this command line get this error : 
```
java -Djavax.net.ssl.trustStoreType=Windows-ROOT -jar .\schemaspy-6.1.0.jar
Erreur : impossible de trouver ou de charger la classe principale .net.ssl.trustStoreType=Windows-ROOT
Causé par : java.lang.ClassNotFoundException: /net/ssl/trustStoreType=Windows-ROOT
```

**Comment by NilkOne** [comment]
Is it possible to not use encrypted connection ? (because the server has no SSL certificates)

**Comment by npetzall** [comment]
See 
https://github.com/schemaspy/schemaspy/issues/633#issuecomment-1039293273
https://github.com/schemaspy/schemaspy/issues/633#issuecomment-1039545210

Downgrading seems to fix the ssl default.

**Comment by npetzall** [comment]
There is a property `encrypt` that is default true since version 10

`-connprops encrypt\=false` for windows cmd
`-connprops encrypt\\=false` Linux or git bash on windows

**Comment by npetzall** [comment]
There are improved queries for SQL Server 17 and newer. So this is the databaseType-file  from master.

Save this content into `my-mssql.properties` place it next to schemaspy-jarfile and use `-t my-mssql` and it will use the `-db` as instanceName instead and it will also disable TLS. So no need for `-connprops`

```
extends=mssql08
connectionSpec=jdbc:sqlserver://<hostOptionalPort>;instanceName=<db>;encrypt=false
selectViewSql=select sm.definition as view_definition from sys.objects so left join sys.sql_modules sm on so.object_id = sm.object_id where so.[type] = 'V' and so.name =:table
selectCheckConstraintsSql=select OBJECT_NAME(parent_object_id) as table_name, name AS constraint_name, definition as text from sys.check_constraints

selectCatalogsSql=SELECT cast(value as nvarchar(max)) as catalog_comment FROM fn_listextendedproperty(N'MS_Description', default, default, default, default, default, default)
selectSchemasSql=SELECT cast(value as nvarchar(max)) as schema_comment FROM fn_listextendedproperty(N'MS_Description', N'schema', :schema, default, default, default, default)
selectTableCommentsSql=SELECT objname as table_name, cast(value as nvarchar(max)) as comments FROM fn_listextendedproperty(N'MS_Description', N'schema', :schema, 'table', null, default, default)
selectColumnCommentsSql=select x.table_name, x.column_name, x.comments from ( select t.name as table_name, c.name as column_name, cast((SELECT value from fn_listextendedproperty(N'MS_Description', N'schema', SCHEMA_NAME(t.schema_id), 'table', t.name, 'column', c.name)) as NVARCHAR(MAX)) as comments from sys.tables t left join sys.columns c on (t.object_id = c.object_id) where SCHEMA_NAME(t.schema_id) = :schema ) x where not x.comments is null
selectViewCommentsSql=SELECT objname as view_name, cast(value as nvarchar(max)) as comments FROM fn_listextendedproperty(N'MS_Description', N'schema', :schema, 'view', null, default, default)
selectViewColumnCommentsSql=select x.view_name, x.column_name, x.comments from ( select v.name as view_name, c.name as column_name, cast((SELECT value from fn_listextendedproperty(N'MS_Description', N'schema', SCHEMA_NAME(v.schema_id), 'view', v.name, 'column', c.name)) as NVARCHAR(MAX)) as comments from sys.views v left join sys.columns c on (v.object_id = c.object_id) where SCHEMA_NAME(v.schema_id) = :schema ) x where not x.comments is null

selectRoutinesSql=SELECT i_s.routine_name, i_s.routine_type, i_s.data_type AS dtd_identifier, i_s.routine_body, i_s.routine_definition, i_s.is_deterministic, i_s.sql_data_access, NULL AS security_type, NULL AS sql_mode, (select cast(value as nvarchar(max)) from fn_listextendedproperty(N'MS_Description', N'schema', i_s.routine_schema, 'procedure', i_s.ROUTINE_NAME, default, default)) AS routine_comment FROM INFORMATION_SCHEMA.ROUTINES i_s WHERE routine_schema = :schema
```

**Comment by NilkOne** [comment]
Thank you very much : 
both of those solutions work perfectly

`java -jar .\schemaspy-6.1.0.jar -connprops encrypt\=false` 👍
