### ISSUE TITLE
Out of memory - Avoid generating the ERM diagram for the whole database

### ISSUE THREAD

**Issue by DanieleGiuffrida** [schemaspy/schemaspy#835]
Recently I'm constantly getting an out of memory when trying to generate the diagrams. Our DB grows constantly and I believe it became too big for generating the diagram with all the tables.

```
ERROR - dot -Tpng table_name.2degrees.dot -otable_name.2degrees.png -Tcmapx: dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.75071 to fit
ERROR - dot -Tpng table_name.2degrees.dot -otable_name.2degrees.png -Tcmapx: dot: failure to create cairo surface: out of memory
```

I don't think that the table"table_name" mentioned in the error above is the problem (it's just a small table and I'm not even counting the rows). I believe it's just the point where the big diagram explodes.

## Possible Solution
Nobody uses the big diagram because it's massive. It would be nice to be able to skip it and only generate the diagrams for each single table (if this is already possible I must have missed it).

**Comment by npetzall** [comment]
I think the error comes from Graphviz. There are multiple reasons. Your computer might be starved in regards to memory.

I did some quick googling. You could test using svg instead of png `-imageformat svg`

Are both errors for the same table?
It would be informative for us if you could check the size of the dot-files that Schemaspy generates. They should be located in `[output]/diagrams/table` or similar.

There is also the option to skip 2nd degree relationships. This table might be small but it will  contain grandparents and grandchildren. So to only include parents and children use `-degree 1`

But we could classify `-degree 0` as a feature request.

**Comment by DanieleGiuffrida** [comment]
Thank you for the quick reply. The .dot file under out\diagrams\summary is 1290KB (the PNG is 42MB) meanwhile the .dot for the mentioned table is 24KB for the 1st degree and 44645KB for the second (PNG 996KB). 

I think you're right the second degree was definitely problem (is that part of the documentation? I must have missed it). Now I managed to pass the relationship part byt I got stuck at the next step "Writing/graphing summary":

```
14:21:23  .ERROR - RelationShipDiagramError
14:21:23  org.schemaspy.output.OutputException: Failed to produce diagram for: out/emptyBFY/diagrams/summary/relationships.real.compact.dot
14:21:23  	at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateSummaryDiagrams(MustacheSummaryDiagramFactory.java:91)
14:21:23  	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:363)
14:21:23  	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:263)
14:21:23  	at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:178)
14:21:23  	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:120)
14:21:23  	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
14:21:23  	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
14:21:23  	at org.schemaspy.Main.main(Main.java:55)
14:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:21:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:21:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
14:21:23  	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
14:21:23  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
14:21:23  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
14:21:23  	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
14:21:23  Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate summary diagram
14:21:23  	at org.schemaspy.output.diagram.DiagramFactory.generateSummaryDiagram(DiagramFactory.java:81)
14:21:23  	at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateSummaryDiagram(MustacheDiagramFactory.java:49)
14:21:23  	at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateSummaryDiagrams(MustacheSummaryDiagramFactory.java:87)
14:21:23  	... 15 common frames omitted
14:21:23  Caused by: org.schemaspy.output.diagram.DiagramException: javax.script.ScriptException: abort(1) at Error
14:21:23  	at jsStackTrace (<eval>:27)
14:21:23  	at stackTrace (<eval>:27)
14:21:23  	at abort (<eval>:50)
14:21:23  	at g7 (<eval>:43)
14:21:23  	at wD (<eval>:34)
14:21:23  	at kD (<eval>:34)
14:21:23  	at EE (<eval>:34)
14:21:23  	at gF (<eval>:34)
14:21:23  	at hF (<eval>:34)
14:21:23  	at WB (<eval>:34)
14:21:23  	at Ib (<eval>:33)
14:21:23  	at ccallFunc (<eval>:27)
14:21:23  	at render (<eval>:87)
14:21:23  	at Viz (<eval>:75)
14:21:23  	at <program> (<eval>:1)
14:21:23  If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information. in <eval> at line number 50 at column number 6466
14:21:23  	at org.schemaspy.output.diagram.vizjs.VizJSDot.generateDiagram(VizJSDot.java:75)
14:21:23  	at org.schemaspy.output.diagram.DiagramFactory.generateSummaryDiagram(DiagramFactory.java:78)
14:21:23  	... 17 common frames omitted
14:21:23  ERROR - RelationShipDiagramError
14:21:23  org.schemaspy.output.OutputException: Failed to produce diagram for: out/emptyBFY/diagrams/summary/relationships.real.large.dot
14:21:23  	at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateRealLarge(MustacheSummaryDiagramFactory.java:125)
14:21:23  	at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateSummaryDiagrams(MustacheSummaryDiagramFactory.java:94)
14:21:23  	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:363)
14:21:23  	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:263)
14:21:23  	at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:178)
14:21:23  	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:120)
14:21:23  	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
14:21:23  	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
14:21:23  	at org.schemaspy.Main.main(Main.java:55)
14:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:21:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:21:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:21:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
14:21:23  	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
14:21:23  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
14:21:23  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
14:21:23  	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
14:21:23  Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate summary diagram
14:21:23  	at org.schemaspy.output.diagram.DiagramFactory.generateSummaryDiagram(DiagramFactory.java:81)
14:21:23  	at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateSummaryDiagram(MustacheDiagramFactory.java:49)
14:21:23  	at org.schemaspy.output.html.mustache.diagrams.MustacheSummaryDiagramFactory.generateRealLarge(MustacheSummaryDiagramFactory.java:120)
14:21:23  	... 16 common frames omitted
14:21:23  Caused by: org.schemaspy.output.diagram.DiagramException: javax.script.ScriptException: abort(1) at Error
14:21:23  	at jsStackTrace (<eval>:27)
14:21:23  	at stackTrace (<eval>:27)
14:21:23  	at abort (<eval>:50)
14:21:23  	at g7 (<eval>:43)
14:21:23  	at wD (<eval>:34)
14:21:23  	at kD (<eval>:34)
14:21:23  	at EE (<eval>:34)
14:21:23  	at gF (<eval>:34)
14:21:23  	at hF (<eval>:34)
14:21:23  	at WB (<eval>:34)
14:21:23  	at Ib (<eval>:33)
14:21:23  	at ccallFunc (<eval>:27)
14:21:23  	at render (<eval>:87)
14:21:23  	at Viz (<eval>:75)
14:21:23  	at <program> (<eval>:1)
14:21:23  If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information. in <eval> at line number 50 at column number 6466
14:21:23  	at org.schemaspy.output.diagram.vizjs.VizJSDot.generateDiagram(VizJSDot.java:75)
14:21:23  	at org.schemaspy.output.diagram.DiagramFactory.generateSummaryDiagram(DiagramFactory.java:78)
14:21:23  	... 18 common frames omitted
```

**Comment by npetzall** [comment]
From the output it seems that you've added the `-vizjs` argument also. 

Which skips the usage of graphviz and uses an embedded Javascript port of graphviz. So it's much more troublesome to troubleshoot.

In the docs there should be information on how you can reduce the information. Less information even excluding parts of the database.

I would need more information about schemaspy version and which database you're using, masked commandline. Best would be to have the dot-file, but that might be sensitive information.

But as for feature request it would be both degree 0 and also an option to skip the summary diagrams. 

Do could you tell me how many tables the database consists of?

**Comment by DanieleGiuffrida** [comment]
Yes I'm using -vizjs because I don't have direct access the server where I run SchemaSpy and I'd have problems to install graphviz myself but if you think it's a better option I can push for that.
This is how I run it:
```
sh "java -Xss4m -jar './lib/schemaspy-6.1.1-SNAPSHOT.jar'" +
                            " -schemas ${dbSchema()} -norows -noviews -degree 1" +
                            " -i \"[a-z].*\"" + // include only tables starting with a letter (i.e. not those starting with _ )
                            " -t mysql -host ${dbHost()} -port ${dbPort()} -db ${dbSchema()} -u ${env.DB_USR} -p ${env.DB_PASSWD}" +
                            " -o out -nopages -imageformat svg -vizjs -debug" +
                            " -dp './lib/mysql-connector-java-8.0.27.jar'"
```

There are about 1030 tables in the DB.

**Comment by DanieleGiuffrida** [comment]
Now I switched to Graphviz but I get another Exception:
```
 org.schemaspy.output.diagram.DiagramException: Failed to generate Orphan diagram
15:05:24  	at org.schemaspy.output.diagram.DiagramFactory.generateOrphanDiagram(DiagramFactory.java:61)
15:05:24  	at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateOrphanDiagram(MustacheDiagramFactory.java:39)
15:05:24  	at org.schemaspy.output.html.mustache.diagrams.MustacheOrphanDiagramFactory.generateOrphanDiagrams(MustacheOrphanDiagramFactory.java:81)
15:05:24  	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:379)
15:05:24  	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:263)
15:05:24  	at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:178)
15:05:24  	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:120)
15:05:24  	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
15:05:24  	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
15:05:24  	at org.schemaspy.Main.main(Main.java:55)
15:05:24  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:05:24  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
15:05:24  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:05:24  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
15:05:24  	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
15:05:24  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
15:05:24  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
15:05:24  	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
15:05:24  Caused by: org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version
15:05:24  	at org.schemaspy.output.diagram.graphviz.GraphvizDot.generateDiagram(GraphvizDot.java:196)
15:05:24  	at org.schemaspy.output.diagram.DiagramFactory.generateOrphanDiagram(DiagramFactory.java:58)
```

**Comment by npetzall** [comment]
I'm unsure about the number of tables, I've created ERD for arts database scheme and I remember it as big. I'll see if I can find it again.

As for the error either you need to add `-gv` to specify the location of the dot binary, or you might have an unsupported version. What version of dot is installed?

**Comment by DanieleGiuffrida** [comment]
Yeah I suspect that the dot.exe wasn't visible so ignore that. We solved anyway the out-of-memory problem which was the first concern. Now I can't finish the build because it times out (I kill the build after 6 hours just in case but it seems not enough). I can see the "Gathered schema details" step (adding foreign key constraint) proceeding so it doesn't get stuck, it's just slow. I suspect something with my DB though, I'm not the only one using it so it may be that. I'll try on a private clone and see how it goes.

**Comment by npetzall** [comment]
I can't at the moment recollect the the order of events.

But for Oracle databases the reverse lookup of foreign keys is super slow. So there is this undocumented argument that will skip it.
`-noexportedkeys` im not sure if it's the problem. But you could try it. In reality the reverse look up isn't needed since you would find it when processing the child table. But if you have multiple schemas or use some exclusions it might be good to do the check. 

BTW, which version of mysql are you using?

**Comment by DanieleGiuffrida** [comment]
-noexportedkeys did the trick. Now it only takes several minutes. Thank you for the help, the problem is solved.

The final solution was to add both -degree 1 and -noexportedkeys and to not use the -vizjs.
