### ISSUE TITLE
jdbc mysql version issue

### ISSUE THREAD

**Issue by lcdiaz2106** [schemaspy/schemaspy#839]
Hello

I already use schemaSpy 6 with postgres and all good, But I try today to do the same with mysql and I have a jdbc error.

The destination DB is AWS RDS Mysql version 5.7
The schemaSpy version is 6.1.0
The version of jdbc connector mysql I use is: mysql-connector-java-8.0.16.jar

and the error is:

WARN  - Connection Failure
org.schemaspy.input.dbms.exceptions.ConnectionFailure: Failed to connect to database URL [jdbc:mysql://myhost/mydb] Communications link failure

The code I use is:

<java -jar schemaspy-6.1.0.jar -t mysql -dp mysql-connector-java-8.0.16.jar -host myhost -u myuser -p xxxxx -db mydb -noschema -debug -o /tmp/output>

My java version
 java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Homebrew (build 17.0.2+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.2+0, mixed mode, sharing)

I hope you can help

Many thanks

**Comment by lcdiaz2106** [comment]
Hello Nils
yes, I can connect and from from the jump server I can also connect via psql.
You know, I try with previous versions of schemaSpy 5 and jdbc version 3 and it works fine. The problem I guess is about jdbc version. When I connect with the mysql jdbc web page there is a lot of versions... I don't know if a matrix of versions exists.

**Comment by npetzall** [comment]
Hade a look and it should work with 8.0.16 unless there is a bug. Schemaspy has no specific requirement for version, since it work with schemaspy 5 and older driver. You could use the older driver with schemaspy 6.

With the `-debug` there should be more information about why it failed (if it wasn't added after release and only exist in snapshot).

The stacktrace could contain details of why it failed. I know they have changed default values that might effect how connections are made.

**Comment by lcdiaz2106** [comment]
Hello Nils
with this command 
 java -jar schemaspy-6.1.0.jar -t mysql -dp mysql-connector-java-3.1.13-bin.jar -host myhost -u myuser -p xxxxx -db mydb -noschema -debug -o /tmp/output

I have this message
DEBUG - Unable to find driverClass 'com.mysql.cj.jdbc.Driver'
DEBUG - supportsSchemasInTableDefinitions: false
DEBUG - supportsCatalogsInTableDefinitions: false
DEBUG - Catalog not provided, queried jdbc driver and got 'mydb'
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.AbstractMethodError: Receiver class com.mysql.jdbc.Connection does not define or inherit an implementation of the resolved method 'abstract java.lang.String getSchema()' of interface java.sql.Connection.
	at org.schemaspy.input.dbms.SchemaResolver.resolveSchema(SchemaResolver.java:44)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:228)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	... 8 more

**Comment by npetzall** [comment]
That exception says that the mysql driver isn't fully implemented, we use methods that are specified in the interface but they aren't implemented in the driver. 3.1.13 is old, this methods were not used in 5.0 that's why it works.

I would suggest to test with jdbc driver versions 6.0.6 or 5.1.59 since they are prior to the bigger changes that are in 8.x.

**Comment by lcdiaz2106** [comment]
With 6.0.6

`INFO  - Starting schema analysis
DEBUG - Resolving dbType: mysql ->
	schemaspy-6.1.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mysql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'myhost' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'mydb' description: 'database name'
Thu Mar 17 10:00:23 CET 2022 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
WARN  - Connection Failure
org.schemaspy.input.dbms.exceptions.ConnectionFailure: Failed to connect to database URL [jdbc:mysql://myhost/mydb] Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:101)
	at org.schemaspy.input.dbms.DbDriverLoader.getConnection(DbDriverLoader.java:75)
	at org.schemaspy.input.dbms.service.SqlService.connect(SqlService.java:70)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:220)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
`

**Comment by lcdiaz2106** [comment]
the 5.1.59 file is not present in the list
<img width="622" alt="image" src="https://user-images.githubusercontent.com/47460692/158774685-f6bd370f-0276-43a5-b4b1-219b11efb628.png">

**Comment by npetzall** [comment]
My bad 5.1.49

**Comment by lcdiaz2106** [comment]
;) don't worry 
So I download this version

`mysql-connector-java-5.1.49 % ls
CHANGES					README					build.xml				mysql-connector-java-5.1.49.jar
COPYING					README.txt				mysql-connector-java-5.1.49-bin.jar	src
`

The correct file is this one correct? mysql-connector-java-5.1.49-bin.jar

**Comment by lcdiaz2106** [comment]
same error with 5.1.49 than 6.0.6
Can I edit the schemaspy/types/mysql.properties file ? where can I find this file in the laptop?

**Comment by npetzall** [comment]
Jar-files can be opened like zip file.

But they are also located here: https://github.com/schemaspy/schemaspy/tree/master/src/main/resources/org/schemaspy/types

https://schemaspy.readthedocs.io/en/latest/advanced_usage.html

**Comment by lcdiaz2106** [comment]
The error can have some thing to do with this ?
`Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)` Should I enable old ciphers in my Java ?

**Comment by lcdiaz2106** [comment]
Ok it works now
I change the file
`/usr/local/Cellar/openjdk/17.0.2/libexec/openjdk.jdk/Contents/Home/conf/security/java.security`
and put jdk.tls.legacyAlgorithms
Then rerun jar and now it's ok.. After the process finish I 'll return to the original java config.
Thanks for your help Nils !!

**Comment by lcdiaz2106** [comment]
Woww look this:

`Connecting relationships....INFO  - Estimated time remaining for connecting tables is 4 hr 1 min 39 s 620 ms, most time might be spent in getExportedKeys, you can disable getExportedKeys with `-noexportedkeys`. The implication of this is that you won't get cross schema relationships where table in analysis is FK, and the remote schema isn't analyzed
...............................................WARN  - Failed to getExportedKeys
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

`
The script fails when creating the exported Keys.
Maybe because we have a lot here, there are 300 tables...

**Comment by lcdiaz2106** [comment]
Hoooo look
I add this option
-noexportedkeys
But I still have this:
...ERROR - Failed to produce diagram for: /tmp/output/diagrams/orphans/prepKBDoc.1degree.dot
Failed to generate Orphan diagram
ERROR - Failed to produce diagram for: /tmp/output/diagrams/orphans/prepKBTag.1degree.dot
Failed to generate Orphan diagram

And in the web site

<img width="470" alt="image" src="https://user-images.githubusercontent.com/47460692/158798801-edfaeb38-85fe-47af-9420-2d182079eda6.png">

**Comment by npetzall** [comment]
Add `-debug` and post the stacktrace for the diagram failure

**Comment by lcdiaz2106** [comment]
hoo sorry

here is

`INFO  - Graphviz rendered set to ''
...ERROR - Failed to produce diagram for: /tmp/output/diagrams/orphans/prepKBDoc.1degree.dot
org.schemaspy.output.diagram.DiagramException: Failed to generate Orphan diagram
	at org.schemaspy.output.diagram.DiagramFactory.generateOrphanDiagram(DiagramFactory.java:61)
	at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateOrphanDiagram(MustacheDiagramFactory.java:39)
	at org.schemaspy.output.html.mustache.diagrams.MustacheOrphanDiagramFactory.generateOrphanDiagrams(MustacheOrphanDiagramFactory.java:80)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:366)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version
	at org.schemaspy.output.diagram.graphviz.GraphvizDot.generateDiagram(GraphvizDot.java:193)
	at org.schemaspy.output.diagram.DiagramFactory.generateOrphanDiagram(DiagramFactory.java:58)
	... 16 common frames omitted
`

**Comment by npetzall** [comment]
> Dot missing or invalid version

Either you need to install graphviz (supported version) or you need to specify the path to it's bin directory using `-gv`

**Comment by lcdiaz2106** [comment]
Ok
I have install graphviz version 
 dot -V
dot - graphviz version 3.0.0 (20220226.1711)
That is ok?

and how is the -gv command?
which dot
/usr/local/bin/dot

So like this?
`java -jar schemaspy-6.1.0.jar -t mysql -dp mysql-connector-java-3.1.13-bin.jar -host myhost -u myuser -p xxxxx -db mydb -noschema -debug --gv /usr/local/bin/dot o /tmp/output

**Comment by npetzall** [comment]
https://schemaspy.readthedocs.io/en/latest/installation.html

https://schemaspy.readthedocs.io/en/latest/configuration/commandline.html#diagram-related

There is also an option to use embedded vizjs. But there are some memory issues with huge databases.

**Comment by lcdiaz2106** [comment]
Hello Nils
I change server from where I execute the script, in this server I have this version of graphviz
dot -V
dot - graphviz version 2.30.1 (20201013.1554)
The dot exe is located in /bin

which dot
/bin/dot

So I try without -gv because /bin is on my path
 echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/bin

It fails

So I add the -gv
with this syntax:
-gv /bin
and 
-gv /bin/dot

And I have

WARN  - Failed to query Graphviz version using '/bin/dot/bin/dot -V'
java.io.IOException: Cannot run program "/bin/dot/bin/dot": error=20, Not a directory

But with -vizjs it works for a postgresql DB, but not for mysql

**Comment by npetzall** [comment]
Late to the party by a lot.
Seems that the `-gv` is more for the windows folks.
The code will actually append `bin/dot` to `-gv`.

It's should be working by just using that path variable.  
But to trick SchemaSpy which seems weird you should be able to specify `-gv /`
