### ISSUE TITLE
Issue with Schemaspy on Mac

### ISSUE THREAD

**Issue by maraimm** [schemaspy/schemaspy#856]
Hi,

I am trying to use schemaspy on Mac, but the relation diagrams are not generated. I am using the following command:
`java -jar schemaspy-6.1.0.jar -s vt -t mysql  -dp mysql-connector-java-8.0.29.jar -db vt -host localhost   -u root -p X -o DB_Documentation -gv /usr/local/Cellar/graphviz/3.0.0 -port 3306`
This is the error:
```
INFO  - Writing/diagramming details
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate Table diagram
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:71)
	at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram(MustacheDiagramFactory.java:44)
	at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams(MustacheTableDiagramFactory.java:80)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:426)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	... 8 more
Caused by: org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version
	at org.schemaspy.output.diagram.graphviz.GraphvizDot.generateDiagram(GraphvizDot.java:193)
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:68)
```

## The Environment

* Version used:
* MacOS catalina (10.15.7)
* Mysql (8.0.24)
* Java(16.0.1)
* schemaspy (6.1.0)
* dot -v ( 3.0.0)

**Comment by npetzall** [comment]
Duplicate of #844, we haven't gotten around to test graphviz 3.0 yet. So it's not supported at the moment.

**Comment by maraimm** [comment]
@npetzall 
Thank you for your reply. May I ask how to downgrade graphviz to lower versions. I tried to install an older package from github but it was not successed.

**Comment by npetzall** [comment]
It's been a long time since I was on OSX and used brew. I did some digging and there are bottles for 2.50.0

I'm guessing, but you need to double check if you can install 2.50.0 you'll need to update the path and you might need to use the switch command.

But as I said you need to verify what I'm saying.

I just Google some stuff.

BTW what was the issue with installing older?

**Comment by maraimm** [comment]
Hi,

I tried to find older versions using `brew` with `brew info graphviz` but I cannot find older build, I can only find the latest release graphviz 3.0.0.  I install graphviz 2.50.0 from Github but I am still having an error. 

```
SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0 on cswireless-39.scss.tcd.ie with PID 71142 (/Users/maraim/Documents/dump/schemaspy-6.1.0.jar started by maraim in /Users/maraim/Documents/dump)
INFO  - The following profiles are active: default
INFO  - Started Main in 2.292 seconds (JVM running for 2.742)
INFO  - Starting schema analysis
INFO  - Connected to MySQL - 8.0.24
INFO  - Gathering schema details
Gathering schema details..........................................................(0sec)
Connecting relationships..........................................................(1sec)
Writing/graphing summary.INFO  - Gathered schema details in 1 seconds
INFO  - Writing/graphing summary
WARN  - Failed to query Graphviz version using '/usr/local/Cellar/graphviz/2.5.0/bin/dot -V'
Cannot run program "/usr/local/Cellar/graphviz/2.5.0/bin/dot": error=2, No such file or directory
INFO  - Graphviz rendered set to ''
..ERROR - RelationShipDiagramError
Failed to produce diagram for: DB_Documentation/diagrams/summary/relationships.real.compact.dot
ERROR - RelationShipDiagramError
Failed to produce diagram for: DB_Documentation/diagrams/summary/relationships.real.large.dot
......(1sec)
Writing/diagramming detailsINFO  - Completed summary in 1 seconds
INFO  - Writing/diagramming details
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate Table diagram
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:71)
	at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram(MustacheDiagramFactory.java:44)
	at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams(MustacheTableDiagramFactory.java:80)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:426)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	... 8 more
Caused by: org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version
	at org.schemaspy.output.diagram.graphviz.GraphvizDot.generateDiagram(GraphvizDot.java:193)
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:68)
	... 16 more

```

**Comment by npetzall** [comment]
> Failed to query Graphviz version using '/usr/local/Cellar/graphviz/2.5.0/bin/dot -V' 

Could you double check that the dot binary is located at that path since it complains that it doesn't. 
`/usr/local/Cellar/graphviz/2.5.0/bin/dot`

**Comment by npetzall** [comment]
#865 has been merged, so you can download the snapshot build, there's a link in the readme and it should now be possible to use Graphviz 3.0
