### ISSUE TITLE
docker container unable to create any files/dirs in output directory

### ISSUE THREAD

**Issue by empusas** [schemaspy/schemaspy#943]
I am using the schemaspy container on a Linux system. I have shared an output  directory with the container and set the permission to 777, so every UserID is allowed.
But still I get the error

```
ERROR - IOException
Unable to create directory /output/tables

```
## Expected Behavior
I would expect that the output is written in the given directory.

## Current Behavior
```
ERROR - IOException
Unable to create directory /output/tables

```
## Possible Solution
I assume the issue is with the UID. I see from the docker file that the User java is created. I think adding a fixed UID and adding the user to a group might enable the user to assign the output directory to the UID used by the java user in the container.

In dockerfile:

```
RUN usermod -u 1000 java
RUN usermod -G staff java
```

that would allow the host user to set the UID of the output directory to 1000:1000 and that should solve the problem.

`sudo chown -R 1000:1000 output`

## Your Environment
running the container in Ubuntu Linux

**Comment by npetzall** [comment]
Could you supply the docker run command so that I can recreate as closely as possible.

777 should be enough, but there might be some added security layer that we need to handle, your proposal seems good. If we going with this, we should check if there is any compability with podman we can piggy back on.

@jesperolsson-se do you use podman?

**Comment by npetzall** [comment]
Workaround could be to specify the user that runs the container but I haven't tried it that much.

I think it's `--user`

**Comment by npetzall** [comment]
@empusas 
Which version of Ubuntu?
Do you use apparmor or SELinux?
Docker run command(don't forget to mask, host, user, password)?

**Comment by jesperolsson-se** [comment]
@npetzall:
> 777 should be enough, but there might be some added security layer that we need to handle, your proposal seems good. If we going with this, we should check if there is any compability with podman we can piggy back on.
>
> **jesperolsson-se** do you use podman?

I do. (Rootless) Podman uses `user namespaces` i.e., a mapping of `UID`s and `GID`s. For example, it's possible to map a non-root user on the host to root in the container. Read more e.g., [here](https://blog.christophersmart.com/2021/01/26/user-ids-and-rootless-containers-with-podman/) and [here](https://www.redhat.com/sysadmin/controlling-access-rootless-podman-users). But let's wait with discussing a solution until we know more about the problem. (I also suspect this issue coming from the host's security policies.)

**Comment by foboni** [comment]
@npetzall 
I'm also facing same issue

```bash
$ docker run -v "$PWD/output:/output" -v "$PWD/drivers:/drivers" -v "$PWD/config/db.properties:/config/db.properties" 
...
...
schemaspy/schemaspy:latest -configFile /config/db.properties -noimplied -nopages -l -debug
ERROR - IOException
java.io.IOException: Unable to create directory /output/tables
        at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:2491)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:232)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by simook** [comment]
OS: Debian 11

I'm encountering the same issue when using this command:
```
docker run --user --rm -it -v "/tmp/output":/output  --network auxo_spiros schemaspy/schemaspy:latest -t pgsql -db {db} -host {host} -s public -u {postgres} -p {secret} -hq -imageformat svg -debug
```
Output:
```
INFO  - Starting Main v6.1.0 on 67f9bc6e8457 with PID 1 (/schemaspy-6.1.0.jar started by java in /)
...
ERROR - IOException
java.io.IOException: Unable to create directory /output/tables
        at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:2491)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:232)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by npetzall** [comment]
@simook Could you check the permissions on `/tmp/output`

Was it created before you executed docker and schemaspy or was it created by docker?

**Comment by jflambert** [comment]
just want to pitch in that I personally don't have any issues with Ubuntu 18.04 and a regular user in a normal directory with this command:

docker run -v "$PWD:/output" schemaspy/schemaspy:latest -t pgsql11 -db xxx -u xxx -host xxx -p yyy -norows -nopages -noimplied -degree 1 -schema public

**Comment by P451M** [comment]
I'm facing the same problem.

**Comment by RMCampos** [comment]
I have the same issue. I'm running with docker compose on Ubuntu (rootless).
