### ISSUE TITLE
Exception in thread "main" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by red-gecko27** [schemaspy/schemaspy#962]
Hello,

Do you know how I can resolve this throw ?

## Started with:

`docker run --net=host -v "$PWD/schemaspy_output:/output" schemaspy/schemaspy:snapshot \
  -t pgsql11 \
  -host 127.0.0.1 \
  -port 5432 \
  -db new \
  -u root \
  -p azerty \
  -vizjs`

## Console output:

```
Using drivers:jtds-1.3.1.jar, mariadb-java-client-1.1.10.jar
mysql-connector-java-8.0.28.jar, postgresql-42.3.5.jar
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.1.1-SNAPSHOT

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.1-SNAPSHOT with PID 1 (/usr/local/lib/schemaspy/schemaspy-6.1.1-SNAPSHOT.jar started by java in /)
INFO  - The following profiles are active: default
INFO  - Started Main in 6.027 seconds (JVM running for 6.377)
INFO  - Starting schema analysis
INFO  - Connected to PostgreSQL - 14.5
INFO  - Gathering schema details
Gathering schema details........................................................................................................................(2sec)
Connecting relationships........................................................................................................................(2sec)
Writing/graphing summary.INFO  - Gathered schema details in 2 seconds
INFO  - Writing/graphing summary
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalArgumentException: viz.js
        at org.schemaspy.output.diagram.vizjs.VizJSDot.<init>(VizJSDot.java:51)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:345)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:280)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:134)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.scriptEngine" is null
        at org.schemaspy.output.diagram.vizjs.VizJSDot.<init>(VizJSDot.java:49)
        ... 14 more
```

**Comment by npetzall** [comment]
remove `-vizjs` graphviz should be included in the image.

**Comment by red-gecko27** [comment]
Thanks it works :)
