### ISSUE TITLE
ERROR - RelationShipDiagramError 

### ISSUE THREAD

**Issue by moamenam** [schemaspy/schemaspy#964]
ERROR - RelationShipDiagramError 
java -jar schemaspy-6.1.0.jar -t pgsql11 -dp postgresql-42.5.0.jar -db axelor -host localhost -port 5432 [-s public] -u username [-p password?] -o C:\Users\mmorsy\Downloads\axelor2 -**vizjs**

## Expected Behavior
generating erd and html files for the DV

## Current Behavior
..ERROR - RelationShipDiagramError
Failed to produce diagram for: C:\Users\mmorsy\Downloads\axelor2\diagrams\summary\relationships.real.compact.dot
......(1185sec)
Writing/diagramming detailsINFO  - Completed summary in 1185 seconds
INFO  - Writing/diagramming details
.Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate Table diagram
        at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:71)
        at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram(MustacheDiagramFactory.java:44)
        at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams(MustacheTableDiagramFactory.java:93)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:426)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
Caused by: org.schemaspy.output.diagram.DiagramException: javax.script.ScriptException: java.lang.StackOverflowError in <eval> at line number 27 at column number 596797
        at org.schemaspy.output.diagram.vizjs.VizJSDot.generateDiagram(VizJSDot.java:72)
        at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:68)
        ... 16 more

## Steps to Reproduce (for bugs)
java -jar schemaspy-6.1.0.jar -t pgsql11 -dp postgresql-42.5.0.jar -db axelor -host localhost -port 5432 [-s public] -u username [-p password?] -o C:\Users\mmorsy\Downloads\axelor2 -**vizjs**
1.
2.used for axelor DB on posgres
3.
4.

## Context

* Database type (e.g. MySQL):
* Database driver version (is you use a special one):
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

## Your Environment

* windows
* DB type: postgres 14.5
* DB application: axelor
* Operating System and version (e.g. Windows 10):windows 10
* jdk8

**Comment by npetzall** [comment]
duplicates #462
