### ISSUE TITLE
mysql: NullPointerException for dangling foreign key

### ISSUE THREAD

**Issue by pyhedgehog** [schemaspy/schemaspy#965]
## Expected Behavior
Skip of linked (by foreign key) "remote" table in skipped schema.

## Current Behavior
```console
DEBUG - Adding foreign key constraint 'hidden_local_table_foreign_key_name' to hidden_schema.hidden_local_table
DEBUG - Creating remote table tmp.hidden_remote_table
DEBUG - Creating RemoteTable tmp.hidden_remote_table
DEBUG - Adding remote table tmp.hidden_remote_table
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NullPointerException
        at org.schemaspy.input.dbms.service.TableService.connectForeignKeysRemoteTable(TableService.java:154)
        at org.schemaspy.input.dbms.service.TableService.addRemoteTable(TableService.java:356)
        at org.schemaspy.input.dbms.service.TableService.addRemoteTable(TableService.java:329)
        at org.schemaspy.input.dbms.service.TableService.connectForeignKeys(TableService.java:126)
        at org.schemaspy.input.dbms.service.DatabaseService.connectTables(DatabaseService.java:297)
        at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(DatabaseService.java:110)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:246)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
```

## Possible Solution
Check nulls! (Have a patch)

## Steps to Reproduce (for bugs)
1. Create table.
2. Refer table from tmp schema.
3. Run schemaspy with debug flag.
4. Stare at stacktrace.

## Context
* schemaspy-6.1.0.jar
* mysql-connector-java-8.0.19.jar

**Comment by npetzall** [comment]
I don't actually understand how this can happen. 
So it would be good with an example. Assume that I have no idea what a `tmp schema` is and I wasn't able to google it either.

Null checks are somewhat good. But from my point of view, something else is wrong.
Adding null check will only hide the real issue.

Only temporary I found was tables.
But based on the logging and how the code looks at that location.
BaseContainer isn't returns null. Can call .equals() on null.
BaseContainer is earlier set with the same value as a variable called schema.
The full name that logged contains `tmp` which is probably catalog.

Mysql has switched catalog and schema, so this might be an issue with the driver or the fact that we aren't creating a correct BaseContainer under certain conditions.

So example as SQL statements so that I can reproduce and find the root cause.

**Comment by pyhedgehog** [comment]
I'll try to cut-down example dump...
