### ISSUE TITLE
Caused by: org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version

### ISSUE THREAD

**Issue by lcdiaz2106** [schemaspy/schemaspy#969]
Hello

I try the tool from macbook 
` sw_vers
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
`

I have dot installed:
` dot -v
dot - graphviz version 7.0.0 (20221023.0053)
libdir = "/usr/local/Cellar/graphviz/7.0.0/lib/graphviz"
Activated plugin library: libgvplugin_dot_layout.6.dylib
Using layout: dot:dot_layout
Activated plugin library: libgvplugin_core.6.dylib
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
	/usr/local/Cellar/graphviz/7.0.0/lib/graphviz/config6
		was successfully loaded.
    render	:  cairo dot dot_json fig gd json json0 map mp pic pov ps quartz svg tk visio vml vrml xdot xdot_json
`

But I have the error you can see in title
The command line I use is:
`java -jar schemaspy-6.1.0.jar -t pgsql -host myhost -port 5432  -db db -u user -p 'xxxxx' -norows -gv /usr/local/bin -schemas public -dp postgresql-42.3.3.jar -o /tmp/test`

Can you tell me what I'm doing wrong?
Many thanks

**Comment by lcdiaz2106** [comment]
Hello

I use this Java version
`java -version
openjdk version "11.0.14.1" 2022-02-08 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.14.1+1-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.14.1+1-LTS, mixed mode, sharing)
`

So I try with -vizjs
But
`ERROR - Failed to produce diagram for: /tmp/test/public/diagrams/orphans/partial_reviews.1degree.dot
Failed to generate Orphan diagram
.....(20sec)
Writing/diagramming detailsINFO  - Completed summary in 20 seconds
INFO  - Writing/diagramming details
.Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate Table diagram
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:71)
	at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram(MustacheDiagramFactory.java:44)
	at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams(MustacheTableDiagramFactory.java:80)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:426)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
	at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:176)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:118)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	... 8 more
Caused by: org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version
	at org.schemaspy.output.diagram.graphviz.GraphvizDot.generateDiagram(GraphvizDot.java:193)
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:`

If I use -vizjs I have to remove -gv correct?

**Comment by npetzall** [comment]
`-gv` shouldn't have any impact on `-vizjs` but according to the output the argument isn't picked up. Which is super strange.

**Comment by npetzall** [comment]
I've downloaded and tested with `-vizjs`

Since you're on Java 11, you should get a message: 
`Warning: Nashorn engine is planned to be removed from a future JDK release`

Could you supply the command line used with `-vizjs` so I can verify that the order or something like that doesn't mess things up.

**Comment by lcdiaz2106** [comment]
Hello
Yes sure, this is the command:
`java -jar schemaspy-6.1.0.jar -t mysql -host myhost -port 3306 -db mydb -u adminuser -p 'xxxxx' -schemas schema -noexportedkeys -vizjs -dp mysql-connector-java-8.0.30.jar -o /tmp/test
`

**Comment by npetzall** [comment]
I've broken by dot just to make sure it's not just silently ignored but I can't reproduce it.

There is no option to force Graphviz usage, so there aren't any overriding settings.
There is no debug logging that relates to cmd arguments, so there is no help there.

So I'm gonna start reaching.
1. I don't know if you used copy & past but could you input the `-vizjs` manually and earlier, right after schemaspy-6.1.0.jar
2. Could you re-download schemaspy, https://github.com/schemaspy/schemaspy/releases/download/v6.1.0/schemaspy-6.1.0.jar

**Comment by lcdiaz2106** [comment]
Hello Nils

I redo without copy paste, but writing all the command and I add -debug at the end:
`Writing/graphing summary.INFO  - Gathered schema details in 1 seconds
INFO  - Writing/graphing summary
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalArgumentException: viz.js
	at org.schemaspy.output.diagram.vizjs.VizJSDot.<init>(VizJSDot.java:49)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:324)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
	at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:176)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:118)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
	at org.schemaspy.Main.main(Main.java:55)
	... 8 more
Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.scriptEngine" is null
	at org.schemaspy.output.diagram.vizjs.VizJSDot.<init>(VizJSDot.java:47)
	... 15 more
`

**Comment by lcdiaz2106** [comment]
Also
I try in a windows machine with (garaphz,java 11)  and it works, so I guess the issue is dependencies with my macbook
I try also in a centos machine but the process is killed because of no enough ram, I'll increase ram and try again

Thanks for your help

**Comment by npetzall** [comment]
> Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.scriptEngine" is null at org.schemaspy.output.diagram.vizjs.VizJSDot.<init>(VizJSDot.java:47) ... 15 more

Is that on the osx machine and did it have Java 11? The Javascript engine in jdk/jre was deprecated in Java 11 and removed in Java 15.

**Comment by lcdiaz2106** [comment]
Hello Nils
Ok it work now, I resolve the RAM issue and now I 'm able to get the graph.. Many thanks for your help on this.
Have a nice week
